//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable, NSString;

@interface _KFSpecItem : NSObject
{
    NSMapTable *_maintenanceBlocksByOwner;
    id _objectValue;
    NSString *_key;
    NSString *_label;
    id _defaultValue;
}

+ (id)propertiesForJSONRepresentation;
@property(retain, nonatomic) id defaultValue; // @synthesize defaultValue=_defaultValue;
@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)jsonRepresentation;
- (id)description;
- (id)tuningView;
@property(retain, nonatomic) id objectValue;
- (void)withOwner:(id)arg1 maintain:(CDUnknownBlockType)arg2;
- (id)init;
- (id)initWithJSONRepresentation:(id)arg1;

@end

