//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_KFSpecItem.h"

@class NSLayoutConstraint, NSNumber, UISlider, UIView, _KFCalloutView;

@interface _KFSilderSpecItem : _KFSpecItem
{
    NSNumber *_sliderMinValue;
    NSNumber *_sliderMaxValue;
    UIView *_container;
    UISlider *_slider;
    _KFCalloutView *_calloutView;
    NSLayoutConstraint *_calloutXCenter;
}

+ (id)propertiesForJSONRepresentation;
@property(retain) NSLayoutConstraint *calloutXCenter; // @synthesize calloutXCenter=_calloutXCenter;
@property(retain) _KFCalloutView *calloutView; // @synthesize calloutView=_calloutView;
@property(retain) UISlider *slider; // @synthesize slider=_slider;
@property(retain) UIView *container; // @synthesize container=_container;
@property(retain, nonatomic) NSNumber *sliderMaxValue; // @synthesize sliderMaxValue=_sliderMaxValue;
@property(retain, nonatomic) NSNumber *sliderMinValue; // @synthesize sliderMinValue=_sliderMinValue;
- (void).cxx_destruct;
- (void)updateCalloutXCenter:(id)arg1;
- (void)hideCallout:(id)arg1;
- (void)showCallout:(id)arg1;
- (void)setSliderValue:(id)arg1;
- (id)sliderValue;
- (void)takeSliderValue:(id)arg1;
- (id)tuningView;
- (id)initWithJSONRepresentation:(id)arg1;

@end

