//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DFPRawHTMLBannerViewDelegate.h"
#import "GADBannerViewDelegate.h"

@class DFPBannerView, DFPRawHTMLAd, NSString, NSURL, SCAdManager, SCAdPlaceholder;

@interface AdController : NSObject <DFPRawHTMLBannerViewDelegate, GADBannerViewDelegate>
{
    BOOL _shouldRecordImpressionWithAdResponse;
    SCAdManager *_adManager;
    SCAdPlaceholder *_adPlaceholder;
    DFPBannerView *_bannerView;
    DFPRawHTMLAd *_rawHTMLAd;
    NSURL *_impressionUrl;
    id <SCAdTransformListener> _listener;
}

@property(nonatomic) BOOL shouldRecordImpressionWithAdResponse; // @synthesize shouldRecordImpressionWithAdResponse=_shouldRecordImpressionWithAdResponse;
@property(retain, nonatomic) id <SCAdTransformListener> listener; // @synthesize listener=_listener;
@property(retain, nonatomic) NSURL *impressionUrl; // @synthesize impressionUrl=_impressionUrl;
@property(retain, nonatomic) DFPRawHTMLAd *rawHTMLAd; // @synthesize rawHTMLAd=_rawHTMLAd;
@property(retain, nonatomic) DFPBannerView *bannerView; // @synthesize bannerView=_bannerView;
@property(retain, nonatomic) SCAdPlaceholder *adPlaceholder; // @synthesize adPlaceholder=_adPlaceholder;
@property(retain, nonatomic) SCAdManager *adManager; // @synthesize adManager=_adManager;
- (void).cxx_destruct;
- (void)handleError:(id)arg1;
- (void)sendError:(id)arg1;
- (void)adView:(id)arg1 didFailToReceiveAdWithError:(id)arg2;
- (void)handleAdResponse:(id)arg1;
- (id)extractJsonData:(id)arg1;
- (void)bannerView:(id)arg1 renderRawHTMLAd:(id)arg2;
- (void)recordImpressionByUrl;
- (void)recordImpression;
- (BOOL)canRecordImpression;
- (void)tryRecordImpression;
- (void)makeAdRequest:(id)arg1 via:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

