//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWTableViewCell.h"

@class Friend, UIActivityIndicatorView, UIButton, UILabel;

@interface AddFriendCell : SWTableViewCell
{
    Friend *_friend;
    id <AddFriendCellDelegate> _addDelegate;
    UILabel *_nameLabel;
    UILabel *_subLabel;
    UIButton *_addFriendButton;
    UIButton *_infoButton;
    UIActivityIndicatorView *_loadingIndicator;
}

@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) UIButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) UIButton *addFriendButton; // @synthesize addFriendButton=_addFriendButton;
@property(retain, nonatomic) UILabel *subLabel; // @synthesize subLabel=_subLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak id <AddFriendCellDelegate> addDelegate; // @synthesize addDelegate=_addDelegate;
@property(retain, nonatomic) Friend *friend; // @synthesize friend=_friend;
- (void).cxx_destruct;
- (void)setAddFriendButtonHidden:(BOOL)arg1;
- (id)getTableView;
- (void)addFriendPressed;
- (void)setHighlightedState:(BOOL)arg1;
- (void)setAlreadyAdded:(BOOL)arg1 addFriendCellType:(int)arg2;
- (void)setNameLabelText:(id)arg1;
- (void)setNeedsInfoButton:(BOOL)arg1;
- (void)setLoadingIndicatorWith:(int)arg1;
- (void)setFriend:(id)arg1 alreadyAdded:(BOOL)arg2;
- (void)setFriend:(id)arg1 alreadyAdded:(BOOL)arg2 pendingSnapsCount:(unsigned int)arg3 key:(id)arg4 inPage:(id)arg5 isSearched:(BOOL)arg6;
- (void)setFriend:(id)arg1 alreadyAdded:(BOOL)arg2 pendingSnapsCount:(unsigned int)arg3 key:(id)arg4 inPage:(id)arg5;
- (void)setLabelFramesForKey:(id)arg1 inPage:(id)arg2;
- (void)infoButtonPressed;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 key:(id)arg3 page:(id)arg4;

@end

