//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "FriendsTabBarDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SendTextControllerDelegate.h"

@class AddContactsViewController, AddFriendsDelegateObject, FriendsTabBar, NSArray, NSString, RequestTableViewController, SCHeader, SearchUsersViewController, UISwipeGestureRecognizer, UIView, UIViewController<Subview>;

@interface AddFriendsViewController : UIViewController <FriendsTabBarDelegate, SendTextControllerDelegate, SCHeaderDataSource, SCHeaderDelegate>
{
    BOOL _logOnViewDidAppearFlag;
    BOOL _didShowInitialVC;
    AddFriendsDelegateObject *_addFriendsDelegate;
    int _context;
    id <BulkAddFriendsDelegate> _delegate;
    AddContactsViewController *_addContactsVC;
    NSArray *_addedFriends;
    UIView *_blackHeader;
    UIViewController<Subview> *_displayedVC;
    FriendsTabBar *_friendsTabBar;
    NSArray *_friendsToInvite;
    SCHeader *_header;
    NSArray *_removedFriends;
    RequestTableViewController *_requestTableVC;
    SearchUsersViewController *_searchUsersVC;
    UISwipeGestureRecognizer *_leftSwipeGestureRecognizer;
}

@property(retain, nonatomic) UISwipeGestureRecognizer *leftSwipeGestureRecognizer; // @synthesize leftSwipeGestureRecognizer=_leftSwipeGestureRecognizer;
@property(nonatomic) BOOL didShowInitialVC; // @synthesize didShowInitialVC=_didShowInitialVC;
@property(retain, nonatomic) SearchUsersViewController *searchUsersVC; // @synthesize searchUsersVC=_searchUsersVC;
@property(retain, nonatomic) RequestTableViewController *requestTableVC; // @synthesize requestTableVC=_requestTableVC;
@property(retain, nonatomic) NSArray *removedFriends; // @synthesize removedFriends=_removedFriends;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(retain, nonatomic) NSArray *friendsToInvite; // @synthesize friendsToInvite=_friendsToInvite;
@property(retain, nonatomic) FriendsTabBar *friendsTabBar; // @synthesize friendsTabBar=_friendsTabBar;
@property(retain, nonatomic) UIViewController<Subview> *displayedVC; // @synthesize displayedVC=_displayedVC;
@property(retain, nonatomic) UIView *blackHeader; // @synthesize blackHeader=_blackHeader;
@property(retain, nonatomic) NSArray *addedFriends; // @synthesize addedFriends=_addedFriends;
@property(retain, nonatomic) AddContactsViewController *addContactsVC; // @synthesize addContactsVC=_addContactsVC;
@property(nonatomic) BOOL logOnViewDidAppearFlag; // @synthesize logOnViewDidAppearFlag=_logOnViewDidAppearFlag;
@property(nonatomic) __weak id <BulkAddFriendsDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int context; // @synthesize context=_context;
@property(retain, nonatomic) AddFriendsDelegateObject *addFriendsDelegate; // @synthesize addFriendsDelegate=_addFriendsDelegate;
- (void).cxx_destruct;
- (BOOL)shouldPopToRootViewController;
- (void)saveSentInvites;
- (void)sendTextController:(id)arg1 compeletedWithStatus:(int)arg2;
- (void)sendInvitesToFriends;
- (void)processInvites;
- (void)processAddsAndInvites;
- (BOOL)shouldSendInvites;
- (struct CGRect)frameForSubview;
- (void)showVC:(id)arg1 viewAppearingCalls:(BOOL)arg2;
- (void)showSearch:(BOOL)arg1 updateFriendsTabBar:(BOOL)arg2;
- (void)showContacts:(BOOL)arg1 updateFriendsTabBar:(BOOL)arg2;
- (void)showRequests:(BOOL)arg1 updateFriendsTabBar:(BOOL)arg2;
- (void)searchPressedOnFriendsTabBar:(id)arg1;
- (void)contactsPressedOnFriendsTabBar:(id)arg1;
- (void)requestsPressedOnFriendsTabBar:(id)arg1;
- (void)leftButtonPressed;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)leftSwipe:(id)arg1;
- (void)popViewController;
- (void)handleLeaveScreen:(BOOL)arg1;
- (void)showSearch:(BOOL)arg1 withSearchText:(id)arg2 promptToAdd:(BOOL)arg3;
- (void)showSearch:(BOOL)arg1;
- (void)showContacts:(BOOL)arg1;
- (void)showRequests:(BOOL)arg1;
- (id)newSearchUsersVC;
- (id)newAddContactsVC;
- (id)newRequestTableVC;
- (void)initFriendContainers;
- (void)showInitialVC;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)initHeader;
- (void)loadView;
- (BOOL)logOnViewDidAppear;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

