//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "CrittercismDelegate.h"
#import "SCEmailCrashReporterDelegate.h"
#import "UIApplicationDelegate.h"

@class NSDictionary, NSString, NavigationController, UIWindow;

@interface AppDelegate : UIResponder <CrittercismDelegate, SCEmailCrashReporterDelegate, UIApplicationDelegate>
{
    BOOL didLaunchWithDidFinishLaunching;
    BOOL didLaunchWhenProtectedDataUnavailable;
    BOOL didDisplayViewControllerForRemoteNotifcation;
    BOOL didBeginEnteringForeground;
    NSDictionary *savedLaunchOptions;
    BOOL _didCrashOnLastLoad;
    NavigationController *_navController;
    UIWindow *_window;
    NSDictionary *_remoteNotification;
}

@property(nonatomic) BOOL didCrashOnLastLoad; // @synthesize didCrashOnLastLoad=_didCrashOnLastLoad;
@property(retain, nonatomic) NSDictionary *remoteNotification; // @synthesize remoteNotification=_remoteNotification;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) NavigationController *navController; // @synthesize navController=_navController;
- (void).cxx_destruct;
- (void)kidDidLogin:(id)arg1;
- (void)didReload:(id)arg1;
- (void)didLogout:(id)arg1;
- (void)didLogin:(id)arg1;
- (id)getKidMainViewController;
- (id)getMainViewController;
- (id)getReloadViewController;
- (id)getServiceTermsController;
- (id)getLoginViewController;
- (void)addLoginLogoutReloadListeners;
- (id)getRootViewController;
- (void)initializeViewStackWithLaunchOptions:(id)arg1;
- (void)initializeWithOptions:(id)arg1;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)presentViewControllerForUserInfo:(id)arg1;
- (void)registerforDeviceLockNotif;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)showDefaultWindow;
- (void)cacheKeyboard;
- (void)reportPreviousMemoryCrashIfNecessary;
- (void)crittercismDidCrashOnLastLoad;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (unsigned int)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

