//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVCamCaptureManager, NSData, NSError, NSURL, UIImage;

@protocol AVCamCaptureManagerDelegate <NSObject>

@optional
- (void)toggledCamera:(BOOL)arg1;
- (void)captureManagerDeviceConfigurationChanged:(AVCamCaptureManager *)arg1;
- (void)captureManagerStillImageCaptured:(AVCamCaptureManager *)arg1;
- (void)captureManager:(AVCamCaptureManager *)arg1 didUpdateFrameRate:(int)arg2;
- (void)captureManager:(AVCamCaptureManager *)arg1 didRenderDataImage:(UIImage *)arg2;
- (void)captureManager:(AVCamCaptureManager *)arg1 didDetectSnapcode:(NSData *)arg2 withVersion:(int)arg3;
- (void)captureManagerRecordingFinished:(AVCamCaptureManager *)arg1 toOutputFileURL:(NSURL *)arg2 error:(NSError *)arg3;
- (void)captureManagerRecordingBegan:(AVCamCaptureManager *)arg1;
- (void)captureManager:(AVCamCaptureManager *)arg1 didFailWithError:(NSError *)arg2;
- (void)captureManagerSessionInterruptionWasEnded:(AVCamCaptureManager *)arg1;
- (void)captureManagerSessionWasInterrupted:(AVCamCaptureManager *)arg1;
@end

