//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView;

@protocol BCOVPlaybackController <NSObject>
@property(readonly, copy, nonatomic) id <BCOVMutableAnalytics> analytics;
@property(readonly, nonatomic) UIView *view;
@property(nonatomic, getter=isAutoPlay) BOOL autoPlay;
@property(nonatomic, getter=isAutoAdvance) BOOL autoAdvance;
@property(nonatomic) id <BCOVPlaybackControllerDelegate> delegate;
- (void)pauseAd;
- (void)resumeAd;
- (void)setVideos:(id <NSFastEnumeration>)arg1;
- (void)pause;
- (void)play;
- (void)advanceToNext;
- (void)setAllowsExternalPlayback:(BOOL)arg1;
- (void)removeSessionConsumer:(id <BCOVPlaybackSessionConsumer>)arg1;
- (void)addSessionConsumer:(id <BCOVPlaybackSessionConsumer>)arg1;
@end

