//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BCOVPlaybackSessionConsumer.h"

@class NSString;

@interface BCOVDelegatingSessionConsumer : NSObject <BCOVPlaybackSessionConsumer>
{
}

- (void)unsubscribeDelegate:(id)arg1;
- (void)invoke:(id)arg1 onTarget:(id)arg2 withSessionAndValue:(id)arg3;
- (void)subscribeDelegate:(id)arg1;
- (void)didAdvanceToPlaybackSession:(id)arg1;
- (id)init;
- (id)initWithDelegate:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

