//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCBlockedFriendTableViewCellDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class Friend, NSArray, NSString, SCHeader, UITableView, UIView;

@interface BlockedFriendsViewController : UIViewController <SCHeaderDataSource, SCHeaderDelegate, SCBlockedFriendTableViewCellDelegate, UITableViewDataSource, UITableViewDelegate>
{
    SCHeader *_navHeader;
    UITableView *_tableView;
    NSArray *_friendIndex;
    Friend *_parolee;
    UIView *_noBlockedFriendsView;
}

@property(retain, nonatomic) UIView *noBlockedFriendsView; // @synthesize noBlockedFriendsView=_noBlockedFriendsView;
@property(retain, nonatomic) Friend *parolee; // @synthesize parolee=_parolee;
@property(retain, nonatomic) NSArray *friendIndex; // @synthesize friendIndex=_friendIndex;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) SCHeader *navHeader; // @synthesize navHeader=_navHeader;
- (void).cxx_destruct;
- (BOOL)shouldPopToRootViewControllerLater;
- (BOOL)shouldPopToRootViewController;
- (void)hideNoBlockedFriends;
- (void)showNoBlockedFriendsView;
- (void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)pressedUnblockForCell:(id)arg1;
- (void)leftButtonPressed;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (void)updateForEmptyList;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

