//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AddFriendByNameCellDelegate.h"
#import "EGORefreshTableHeaderDelegate.h"
#import "SCAddFriendCellDelegate.h"
#import "SCAddFriendsInterstitialViewDelegate.h"
#import "SCIndexedTableViewDataSource.h"
#import "SCIndexedTableViewDelegate.h"
#import "SCSearchFriendsSubViewControllerDelegate.h"
#import "SendTextControllerDelegate.h"
#import "Subview.h"

@class AddFriendsDelegateObject, EGORefreshTableHeaderView, Friend, NSDictionary, NSMutableSet, NSString, SCAddFriendsInterstitialView, SCIndexedTableView, SCSearchFriendsSubViewController;

@interface ContactsViewController : UIViewController <AddFriendByNameCellDelegate, EGORefreshTableHeaderDelegate, SCAddFriendCellDelegate, SCAddFriendsInterstitialViewDelegate, SCIndexedTableViewDataSource, SCIndexedTableViewDelegate, SCSearchFriendsSubViewControllerDelegate, SendTextControllerDelegate, Subview>
{
    BOOL _hasInteractedWithTable;
    BOOL _reloading;
    int _context;
    AddFriendsDelegateObject *_addFriendsDelegate;
    id <ContactsVCUserActionDelegate> _superViewDelegate;
    SCAddFriendsInterstitialView *_addFriendsInterstitialView;
    Friend *_friendBeingInvited;
    NSMutableSet *_temporarilyAddedFriends;
    NSDictionary *_findFriendsResults;
    SCIndexedTableView *_unAddedContactsTableView;
    EGORefreshTableHeaderView *_refreshHeaderView;
    SCSearchFriendsSubViewController *_searchFriendsSVC;
}

+ (id)searchContext;
+ (id)contactsContext;
@property(nonatomic) BOOL reloading; // @synthesize reloading=_reloading;
@property(retain, nonatomic) SCSearchFriendsSubViewController *searchFriendsSVC; // @synthesize searchFriendsSVC=_searchFriendsSVC;
@property(retain, nonatomic) EGORefreshTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
@property(retain, nonatomic) SCIndexedTableView *unAddedContactsTableView; // @synthesize unAddedContactsTableView=_unAddedContactsTableView;
@property(retain, nonatomic) NSDictionary *findFriendsResults; // @synthesize findFriendsResults=_findFriendsResults;
@property(retain, nonatomic) NSMutableSet *temporarilyAddedFriends; // @synthesize temporarilyAddedFriends=_temporarilyAddedFriends;
@property(nonatomic) __weak Friend *friendBeingInvited; // @synthesize friendBeingInvited=_friendBeingInvited;
@property(nonatomic) BOOL hasInteractedWithTable; // @synthesize hasInteractedWithTable=_hasInteractedWithTable;
@property(retain, nonatomic) SCAddFriendsInterstitialView *addFriendsInterstitialView; // @synthesize addFriendsInterstitialView=_addFriendsInterstitialView;
@property(nonatomic) __weak id <ContactsVCUserActionDelegate> superViewDelegate; // @synthesize superViewDelegate=_superViewDelegate;
@property(nonatomic) __weak AddFriendsDelegateObject *addFriendsDelegate; // @synthesize addFriendsDelegate=_addFriendsDelegate;
@property(nonatomic) int context; // @synthesize context=_context;
- (void).cxx_destruct;
- (BOOL)egoRefreshTableHeaderDataSourceIsLoading:(id)arg1;
- (void)egoRefreshTableHeaderDidTriggerRefresh:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didFindFriends:(id)arg1;
- (void)sendTextController:(id)arg1 compeletedWithStatus:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForViewModel:(id)arg2 atIndexPath:(id)arg3;
- (void)infoButtonPressed:(id)arg1 forFriend:(id)arg2;
- (void)didSelectAddFriendCell:(id)arg1;
- (void)didSelectAddFriendByNameCell:(id)arg1;
- (id)friendForIndexPath:(id)arg1 andTableView:(id)arg2;
- (BOOL)userHasFriendsOnService;
- (id)getSearchResultsBySection:(id)arg1 withSearchText:(id)arg2;
- (void)resetFriendFilter;
- (void)sendInvitesToFriend:(id)arg1;
- (id)addFriendCellForFriend:(id)arg1 onTableView:(id)arg2;
- (id)cellForModelView:(id)arg1 onTableView:(id)arg2 forRowAtindexPath:(id)arg3;
- (id)pageName;
- (void)handleChangeToFindFriendsResults:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeFindFriendsObservers;
- (void)addFindFriendsObservers;
- (void)didDismissSearch;
- (void)didBeginEditingSearchBox;
- (void)reloadData;
- (void)subviewDidAppear;
- (void)subviewWillAppear;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadView;
- (BOOL)logOnViewDidAppear;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

