//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPickerView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSArray, NSString;

@interface CountryCodePickerView : UIPickerView <UIPickerViewDelegate, UIPickerViewDataSource, UIGestureRecognizerDelegate>
{
    id <CountryCodePickerViewDelegate> _countryCodeDelegate;
    NSArray *_countryCodes;
}

@property(retain, nonatomic) NSArray *countryCodes; // @synthesize countryCodes=_countryCodes;
@property(nonatomic) __weak id <CountryCodePickerViewDelegate> countryCodeDelegate; // @synthesize countryCodeDelegate=_countryCodeDelegate;
- (void).cxx_destruct;
- (BOOL)isSpinning;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (float)pickerView:(id)arg1 rowHeightForComponent:(int)arg2;
- (id)pickerView:(id)arg1 titleForRow:(int)arg2 forComponent:(int)arg3;
- (void)pickerView:(id)arg1 didSelectRow:(int)arg2 inComponent:(int)arg3;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (void)didTapRow:(id)arg1;
- (void)setSelectedCountryCode:(id)arg1 animated:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

