//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "EGORefreshTableHeaderDelegate.h"
#import "FeedTableViewCellDelegate.h"
#import "SCAnimatedFeedBackgroundViewAnimationDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCSearchBarDelegate.h"
#import "SKStoreProductViewControllerDelegate.h"
#import "SwipeView.h"
#import "UIAlertViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class EGORefreshTableHeaderView, NSArray, NSMutableArray, NSString, SCAnimatedFeedBackgroundView, SCHeader, SCMediaView, SCSearchBar, Snap, UIButton, UIImageView, UILabel, UILongPressGestureRecognizer, UITableView, UITapGestureRecognizer;

@interface FeedViewController : UIViewController <EGORefreshTableHeaderDelegate, FeedTableViewCellDelegate, SCSearchBarDelegate, SCHeaderDataSource, SCHeaderDelegate, SCAnimatedFeedBackgroundViewAnimationDelegate, SKStoreProductViewControllerDelegate, SwipeView, UIAlertViewDelegate, UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate>
{
    BOOL _addedChatsObservers;
    BOOL _animationInProgress;
    BOOL _cellSwiping;
    BOOL _delayedReload;
    BOOL _delayedResetChats;
    BOOL _firstFetchUpdatesRequest;
    BOOL _reloading;
    BOOL _searching;
    BOOL _shouldBounceTeamSnapchatCell;
    BOOL _showingSearchBar;
    BOOL _didLogFirstChatReadyToView;
    BOOL _didAddObserver;
    id <FeedViewControllerDelegate> _delegate;
    id <FeedTableViewCellDelegate> _feedCellDelegate;
    SCMediaView *_mediaView;
    id <SwipeViewParentDelegate> _parentDelegate;
    id <ReplyDelegate> _replyDelegate;
    id <SCStartChatDelegate> _startChatDelegate;
    SCAnimatedFeedBackgroundView *_animatedBackgroundView;
    NSMutableArray *_chats;
    UITapGestureRecognizer *_doubleTapGestureRecognizer;
    NSArray *_filteredChats;
    SCHeader *_header;
    Snap *_lastVisibleSnap;
    float _lastScrolledYOffset;
    float _lastYOffsetBeforeScrolling;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UIButton *_moreSnapsButton;
    unsigned int _moreSnapsCount;
    UILabel *_noSnaps;
    EGORefreshTableHeaderView *_refreshHeaderView;
    UILabel *_receivedLabel;
    Snap *_replaySnap;
    UIButton *_scoreButton;
    UILabel *_scoreDivider;
    SCSearchBar *_searchBar;
    UILabel *_sentLabel;
    UIImageView *_snapchatLabel;
    UITableView *_tableView;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UITapGestureRecognizer *_tapToSkipGestureRecognizer;
    Snap *_visibleSnap;
}

@property(nonatomic) BOOL didAddObserver; // @synthesize didAddObserver=_didAddObserver;
@property(nonatomic) BOOL didLogFirstChatReadyToView; // @synthesize didLogFirstChatReadyToView=_didLogFirstChatReadyToView;
@property(retain, nonatomic) Snap *visibleSnap; // @synthesize visibleSnap=_visibleSnap;
@property(retain, nonatomic) UITapGestureRecognizer *tapToSkipGestureRecognizer; // @synthesize tapToSkipGestureRecognizer=_tapToSkipGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIImageView *snapchatLabel; // @synthesize snapchatLabel=_snapchatLabel;
@property(nonatomic) BOOL showingSearchBar; // @synthesize showingSearchBar=_showingSearchBar;
@property(nonatomic) BOOL shouldBounceTeamSnapchatCell; // @synthesize shouldBounceTeamSnapchatCell=_shouldBounceTeamSnapchatCell;
@property(retain, nonatomic) UILabel *sentLabel; // @synthesize sentLabel=_sentLabel;
@property(nonatomic) BOOL searching; // @synthesize searching=_searching;
@property(retain, nonatomic) SCSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UILabel *scoreDivider; // @synthesize scoreDivider=_scoreDivider;
@property(retain, nonatomic) UIButton *scoreButton; // @synthesize scoreButton=_scoreButton;
@property(retain, nonatomic) Snap *replaySnap; // @synthesize replaySnap=_replaySnap;
@property(nonatomic) BOOL reloading; // @synthesize reloading=_reloading;
@property(retain, nonatomic) UILabel *receivedLabel; // @synthesize receivedLabel=_receivedLabel;
@property(retain, nonatomic) EGORefreshTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
@property(retain, nonatomic) UILabel *noSnaps; // @synthesize noSnaps=_noSnaps;
@property(nonatomic) unsigned int moreSnapsCount; // @synthesize moreSnapsCount=_moreSnapsCount;
@property(retain, nonatomic) UIButton *moreSnapsButton; // @synthesize moreSnapsButton=_moreSnapsButton;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(nonatomic) float lastYOffsetBeforeScrolling; // @synthesize lastYOffsetBeforeScrolling=_lastYOffsetBeforeScrolling;
@property(nonatomic) float lastScrolledYOffset; // @synthesize lastScrolledYOffset=_lastScrolledYOffset;
@property(retain, nonatomic) Snap *lastVisibleSnap; // @synthesize lastVisibleSnap=_lastVisibleSnap;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(nonatomic) BOOL firstFetchUpdatesRequest; // @synthesize firstFetchUpdatesRequest=_firstFetchUpdatesRequest;
@property(retain, nonatomic) NSArray *filteredChats; // @synthesize filteredChats=_filteredChats;
@property(retain, nonatomic) UITapGestureRecognizer *doubleTapGestureRecognizer; // @synthesize doubleTapGestureRecognizer=_doubleTapGestureRecognizer;
@property(nonatomic) BOOL delayedResetChats; // @synthesize delayedResetChats=_delayedResetChats;
@property(nonatomic) BOOL delayedReload; // @synthesize delayedReload=_delayedReload;
@property(retain, nonatomic) NSMutableArray *chats; // @synthesize chats=_chats;
@property(nonatomic) BOOL cellSwiping; // @synthesize cellSwiping=_cellSwiping;
@property(nonatomic) BOOL animationInProgress; // @synthesize animationInProgress=_animationInProgress;
@property(retain, nonatomic) SCAnimatedFeedBackgroundView *animatedBackgroundView; // @synthesize animatedBackgroundView=_animatedBackgroundView;
@property(nonatomic) BOOL addedChatsObservers; // @synthesize addedChatsObservers=_addedChatsObservers;
@property(nonatomic) __weak id <SCStartChatDelegate> startChatDelegate; // @synthesize startChatDelegate=_startChatDelegate;
@property(nonatomic) __weak id <ReplyDelegate> replyDelegate; // @synthesize replyDelegate=_replyDelegate;
@property(nonatomic) __weak id <SwipeViewParentDelegate> parentDelegate; // @synthesize parentDelegate=_parentDelegate;
@property(retain, nonatomic) SCMediaView *mediaView; // @synthesize mediaView=_mediaView;
@property(nonatomic) __weak id <FeedTableViewCellDelegate> feedCellDelegate; // @synthesize feedCellDelegate=_feedCellDelegate;
@property(nonatomic) __weak id <FeedViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showCameraForChat:(id)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)updateNoSnapsVisibility;
- (void)updateNoSnapsFrame;
- (id)filterChatsForQuery:(id)arg1;
- (void)filterSearch:(id)arg1;
- (void)filterResults:(id)arg1;
- (void)searchBarKeyboardWillHide:(id)arg1;
- (void)searchBarDidBeginSearch:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBar:(id)arg1 didSearch:(id)arg2;
- (void)cellDidEndPulling:(id)arg1;
- (void)cell:(id)arg1 didChangePullingOffset:(float)arg2;
- (void)cellDidBeginPulling:(id)arg1;
- (void)cellDidEndScrolling:(id)arg1;
- (void)cellDidBeginScrolling:(id)arg1;
- (void)feedBackgroundAnimationDidStop;
- (void)feedBackgroundAnimationDidStart;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (BOOL)egoRefreshTableHeaderDataSourceIsLoading:(id)arg1;
- (void)egoRefreshTableHeaderDidTriggerRefresh:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)doneLoadingTableViewData;
- (BOOL)isSnapCountingDown;
- (unsigned int)newSnapCount;
- (BOOL)isScrolledToTop;
- (void)didBecomeActive;
- (void)didInitializeUnstartedChats;
- (void)didFetchConversations;
- (void)reloadTableViewDataSource;
- (id)chatForIndexPath:(id)arg1;
- (id)chatForCell:(id)arg1;
- (id)chatForPoint:(struct CGPoint)arg1;
- (BOOL)isNearLoadingCellIndexPath:(id)arg1;
- (BOOL)isLoadingCellIndexPath:(id)arg1;
- (BOOL)isLoadingCellAtPoint:(struct CGPoint)arg1;
- (void)userDidTakeScreenshot;
- (void)touchesCancelledForCellWithSnap:(id)arg1;
- (void)touchesEndedForCellWithSnap:(id)arg1;
- (BOOL)touchesBeganForCellWithChat:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)setLabels;
- (void)toggleSnapchatLogo;
- (void)snapchatButtonPressed:(id)arg1;
- (void)doReloadTableView;
- (void)reloadTableView;
- (void)snapFailedToPlay:(id)arg1 withError:(id)arg2;
- (id)replayableSnapsForUsername:(id)arg1;
- (id)allSnaps;
- (void)loadNextSnapStack;
- (id)chatForUsername:(id)arg1;
- (void)snapExpired:(id)arg1;
- (void)promptReplaySnap:(id)arg1;
- (void)hideSnap:(id)arg1;
- (void)showSnap:(id)arg1;
- (BOOL)shouldShowNotificationInCurrentMediaState;
- (BOOL)showingMediaView;
- (float)preferredLeftButtonWidth;
- (void)rightButtonPressed;
- (void)leftButtonPressed;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)synced:(id)arg1;
- (void)updateCellDisplayForRecipient:(id)arg1;
- (void)didReadMessages:(id)arg1;
- (void)chatDidChange:(id)arg1;
- (void)chatsDidChange:(id)arg1;
- (void)friendsDidChange:(id)arg1;
- (void)userPreviewStatusChanged:(id)arg1;
- (void)viewWillResignActive;
- (int)indexOfChatForRecipient:(id)arg1;
- (void)handleChange:(id)arg1 toSnap:(id)arg2 withKey:(id)arg3;
- (void)handleKeyChangeToLastSnap:(id)arg1 inChat:(id)arg2;
- (void)handleChangeToSnaps:(id)arg1;
- (void)handleChangeToChats:(id)arg1;
- (void)handleChangeToUserChats:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeIndividualSnapsObservers:(id)arg1;
- (void)removeChatObservers:(id)arg1;
- (void)removeIndividualChatsObservers:(id)arg1;
- (void)removeChatsObservers;
- (void)addIndividualSnapsObservers:(id)arg1;
- (void)addChatObservers:(id)arg1;
- (void)addIndividualChatsObservers:(id)arg1;
- (void)addChatsObservers;
- (void)resetMoreSnapsCountButton;
- (void)resetMoreSnapsCount;
- (void)snapSent:(id)arg1;
- (void)resetChats;
- (void)moreSnapsButtonPressed;
- (void)resetChatsIfNecessary;
- (void)scrollToTop;
- (void)viewDidFullyDisappear;
- (void)viewDidFullyAppear;
- (void)viewDidPartiallyAppear;
- (void)viewCanAppear;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)tapToSkip:(id)arg1;
- (void)handleTapForLoadingCellAtPoint:(struct CGPoint)arg1;
- (void)tap:(id)arg1;
- (void)doubleTap:(id)arg1;
- (void)longPress:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)initGestures;
- (void)initMoreSnapsButton;
- (void)initSearchBar;
- (void)initTableViewAndRefreshHeader;
- (void)initNoSnapsLabel;
- (void)initHeader;
- (void)loadView;
- (BOOL)logOnViewDidAppear;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

