//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FeedTableViewCell;

@protocol FeedTableViewCellDelegate <NSObject>
- (void)cellDidEndPulling:(FeedTableViewCell *)arg1;
- (void)cell:(FeedTableViewCell *)arg1 didChangePullingOffset:(float)arg2;
- (void)cellDidBeginPulling:(FeedTableViewCell *)arg1;

@optional
- (void)cellDidEndScrolling:(FeedTableViewCell *)arg1;
- (void)cellDidBeginScrolling:(FeedTableViewCell *)arg1;
@end

