//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSString, NSTimer, SCAnimatingReplaySnapView, SCChat, UIActivityIndicatorView, UIImageView, UILabel, UIScrollView, UIView;

@interface FeedTableViewCell : UITableViewCell <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    BOOL _animatingSublabel;
    BOOL _canEnableScroll;
    BOOL _deceleratingToZero;
    BOOL _hideSublabel;
    BOOL _pulling;
    BOOL _searching;
    BOOL _scrolling;
    id <FeedTableViewCellDelegate> _delegate;
    UIActivityIndicatorView *_activity;
    SCAnimatingReplaySnapView *_animatingReplaySnapView;
    UIView *_containerView;
    SCChat *_chat;
    UIImageView *_chatIcon;
    UIView *_chatView;
    float _decelerationDistanceRatio;
    float _displayedMessageExpiration;
    NSTimer *_expirationTimer;
    UIImageView *_iconView;
    UILabel *_iconLabel;
    UILabel *_label;
    NSArray *_messagesToDisplay;
    int _messageIndex;
    UIScrollView *_scrollView;
    UIView *_solidBackgroundView;
    UILabel *_subLabel;
}

+ (id)chatNotificationColor;
@property(retain, nonatomic) UILabel *subLabel; // @synthesize subLabel=_subLabel;
@property(retain, nonatomic) UIView *solidBackgroundView; // @synthesize solidBackgroundView=_solidBackgroundView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) BOOL scrolling; // @synthesize scrolling=_scrolling;
@property(nonatomic) BOOL searching; // @synthesize searching=_searching;
@property(nonatomic) BOOL pulling; // @synthesize pulling=_pulling;
@property(nonatomic) int messageIndex; // @synthesize messageIndex=_messageIndex;
@property(retain, nonatomic) NSArray *messagesToDisplay; // @synthesize messagesToDisplay=_messagesToDisplay;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UILabel *iconLabel; // @synthesize iconLabel=_iconLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) BOOL hideSublabel; // @synthesize hideSublabel=_hideSublabel;
@property(retain, nonatomic) NSTimer *expirationTimer; // @synthesize expirationTimer=_expirationTimer;
@property(nonatomic) float displayedMessageExpiration; // @synthesize displayedMessageExpiration=_displayedMessageExpiration;
@property(nonatomic) float decelerationDistanceRatio; // @synthesize decelerationDistanceRatio=_decelerationDistanceRatio;
@property(nonatomic) BOOL deceleratingToZero; // @synthesize deceleratingToZero=_deceleratingToZero;
@property(retain, nonatomic) UIView *chatView; // @synthesize chatView=_chatView;
@property(retain, nonatomic) UIImageView *chatIcon; // @synthesize chatIcon=_chatIcon;
@property(retain, nonatomic) SCChat *chat; // @synthesize chat=_chat;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) BOOL canEnableScroll; // @synthesize canEnableScroll=_canEnableScroll;
@property(nonatomic) BOOL animatingSublabel; // @synthesize animatingSublabel=_animatingSublabel;
@property(retain, nonatomic) SCAnimatingReplaySnapView *animatingReplaySnapView; // @synthesize animatingReplaySnapView=_animatingReplaySnapView;
@property(retain, nonatomic) UIActivityIndicatorView *activity; // @synthesize activity=_activity;
@property(nonatomic) __weak id <FeedTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (float)contentPageWidth;
- (void)setFrame:(struct CGRect)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollingEnded;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)animateReplayWithSnapIfNecessary:(id)arg1;
- (void)centerIconLabelForTime:(unsigned int)arg1;
- (void)expirationTimerFired:(id)arg1;
- (void)updateDisplayWithMessage:(id)arg1 searching:(BOOL)arg2 newSnap:(BOOL)arg3;
- (void)updateDisplayWithChat:(id)arg1 searching:(BOOL)arg2;
- (void)showTapToReplyLabelBrieflyIfNecessary;
- (void)finishedDisplayingSubLabelBriefly;
- (void)showSubLabelBriefly;
- (void)showSubLabelBrieflyIfNecessary;
- (void)bounceWithMagnitude:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)bounceWithCompletion:(CDUnknownBlockType)arg1;
- (void)bounce;
- (void)repeatedBounceAfterDelays:(id)arg1;
- (void)repeatedBounce;
- (void)setScrollingEnabled:(BOOL)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

