//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableArray, NSMutableDictionary;

@interface FriendStoriesCollection : NSObject <NSCoding>
{
    NSMutableArray *_friendUsernamesWithUnviewedStories;
    NSMutableArray *_sharedUsernamesWithUnviewedStories;
    NSMutableDictionary *_friendsStories;
    NSMutableArray *_replayableSponsoredStories;
    unsigned int _viewingStoriesNumber;
    NSMutableDictionary *_removedStories;
    NSMutableArray *_sponsoredImpressionsNotYetReported;
    NSMutableDictionary *_storiesBeingViewedDictionary;
    NSMutableArray *_storiesViewedButNotMarkedAsViewed;
    NSMutableArray *_storiesViewedAndBeingMarkedAsViewed;
    NSMutableDictionary *_viewedStoriesDictionary;
    NSMutableDictionary *_toBeRemovedFriendStories;
}

@property(retain, nonatomic) NSMutableDictionary *toBeRemovedFriendStories; // @synthesize toBeRemovedFriendStories=_toBeRemovedFriendStories;
@property(retain, nonatomic) NSMutableDictionary *viewedStoriesDictionary; // @synthesize viewedStoriesDictionary=_viewedStoriesDictionary;
@property(retain, nonatomic) NSMutableArray *storiesViewedAndBeingMarkedAsViewed; // @synthesize storiesViewedAndBeingMarkedAsViewed=_storiesViewedAndBeingMarkedAsViewed;
@property(retain, nonatomic) NSMutableArray *storiesViewedButNotMarkedAsViewed; // @synthesize storiesViewedButNotMarkedAsViewed=_storiesViewedButNotMarkedAsViewed;
@property(retain, nonatomic) NSMutableDictionary *storiesBeingViewedDictionary; // @synthesize storiesBeingViewedDictionary=_storiesBeingViewedDictionary;
@property(retain, nonatomic) NSMutableArray *sponsoredImpressionsNotYetReported; // @synthesize sponsoredImpressionsNotYetReported=_sponsoredImpressionsNotYetReported;
@property(retain, nonatomic) NSMutableDictionary *removedStories; // @synthesize removedStories=_removedStories;
@property(nonatomic) unsigned int viewingStoriesNumber; // @synthesize viewingStoriesNumber=_viewingStoriesNumber;
@property(retain, nonatomic) NSMutableArray *replayableSponsoredStories; // @synthesize replayableSponsoredStories=_replayableSponsoredStories;
@property(retain, nonatomic) NSMutableDictionary *friendsStories; // @synthesize friendsStories=_friendsStories;
@property(retain, nonatomic) NSMutableArray *sharedUsernamesWithUnviewedStories; // @synthesize sharedUsernamesWithUnviewedStories=_sharedUsernamesWithUnviewedStories;
@property(retain, nonatomic) NSMutableArray *friendUsernamesWithUnviewedStories; // @synthesize friendUsernamesWithUnviewedStories=_friendUsernamesWithUnviewedStories;
- (void).cxx_destruct;
- (id)mostRecentTimestampForAllFriendStories;
- (unsigned int)friendsWithNewStoriesCount;
- (id)storiesBeingViewed;
- (void)addToSponsoredImpressionsNotYetReported:(id)arg1;
- (id)getAndClearUnreportedSponsoredImpressions;
- (void)markedStoriesViewed:(id)arg1 withSuccess:(BOOL)arg2;
- (id)getAndClearUnreportedViewedStories;
- (id)sharedStoriesForIndex:(unsigned int)arg1;
- (id)friendStoriesForIndex:(unsigned int)arg1;
- (void)fetchMediaForBatches:(unsigned int)arg1;
- (id)friendStoriesForUsername:(id)arg1;
- (BOOL)firstRecentUpdateReadyToPlay;
- (BOOL)shouldStoryBeViewed:(id)arg1;
- (void)resetRecentlyViewedState;
- (void)clearViewedStories;
- (void)clearExpiredStories;
- (void)removeStory:(id)arg1;
- (void)reinsertRemovedFriendStoriesForUsername:(id)arg1;
- (void)clearRemovedFriendStoriesForUsername:(id)arg1;
- (void)removeAllStoriesForUsername:(id)arg1;
- (void)markStoryViewed:(id)arg1 forViewingType:(int)arg2;
- (void)markStoryViewed:(id)arg1;
- (void)markAllViewingStoriesViewed;
- (void)removeViewingStory:(id)arg1;
- (void)addViewingStory:(id)arg1;
- (unsigned int)unviewedSharedStoriesCount;
- (unsigned int)unviewedFriendStoriesCount;
- (CDUnknownBlockType)usernameComparatorWithFriendsStories:(id)arg1;
- (void)insertUsername:(id)arg1 intoUsernames:(id)arg2 sortedBy:(CDUnknownBlockType)arg3;
- (void)insertAdditionalFriendStories:(id)arg1;
- (void)updateWithFriendsStories:(id)arg1 isDelta:(BOOL)arg2;
- (void)ensureNonNilObjects;
- (void)ensureNoStoriesBeingMarkedExists;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

