//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FriendsTabBar;

@protocol FriendsTabBarDelegate <NSObject>
- (void)searchPressedOnFriendsTabBar:(FriendsTabBar *)arg1;
- (void)contactsPressedOnFriendsTabBar:(FriendsTabBar *)arg1;
- (void)requestsPressedOnFriendsTabBar:(FriendsTabBar *)arg1;
@end

