//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADAdNetworkExtras.h"

@class NSDictionary;

@interface GADAdMobExtras : NSObject <GADAdNetworkExtras>
{
    NSDictionary *_additionalParameters;
}

@property(copy, nonatomic) NSDictionary *additionalParameters; // @synthesize additionalParameters=_additionalParameters;
- (void).cxx_destruct;

@end

