//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSURL;

@interface GADMRAIDPicture : NSObject <NSURLConnectionDataDelegate, UIAlertViewDelegate>
{
    BOOL _downloadStarted;
    id <GADMRAIDPictureDelegate> _delegate;
    NSURL *_pictureURL;
}

@property(copy, nonatomic) NSURL *pictureURL; // @synthesize pictureURL=_pictureURL;
@property(nonatomic) __weak id <GADMRAIDPictureDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)storeImage:(id)arg1;
- (void)downloadImageWithURL:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)storeInPhotoAlbum;
- (id)initWithURL:(id)arg1;

@end

