//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIAlertViewDelegate.h"
#import "UIWebViewDelegate.h"

@class GADImpressionTicketGestureRecognizer, GADUIWebViewGestureDelegate, NSString, NSURL, NSURLRequest, UIAlertView, UIScrollView, UIViewController, UIWebView;

@interface GADWebView : UIView <UIAlertViewDelegate, UIWebViewDelegate>
{
    UIWebView *_webView;
    BOOL _touched;
    BOOL _showDebug;
    BOOL _didReceiveLoadEvent;
    BOOL _savedState;
    BOOL _activeViewUnloadPingReceived;
    BOOL _activeViewVisibility;
    UIViewController *_viewController;
    NSString *_adDebugDialog;
    int _orientation;
    GADUIWebViewGestureDelegate *_gestureDelegate;
    GADImpressionTicketGestureRecognizer *_gesture;
    UIAlertView *_alertView;
    UIView *_savedSuperview;
    id <GADWebViewDelegate> _savedDelegate;
    NSURL *_url;
    id <GADWebViewActiveViewMonitoring> _activeViewObserver;
    id <GADWebViewDelegate> _delegate;
    NSURL *_URL;
    UIViewController *_viewControllerBeforeExpanded;
    struct CGRect _savedFrame;
}

+ (void)cacheWebView:(id)arg1;
+ (id)cachedWebView;
+ (id)webViewCache;
@property(nonatomic) __weak UIViewController *viewControllerBeforeExpanded; // @synthesize viewControllerBeforeExpanded=_viewControllerBeforeExpanded;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(nonatomic) __weak id <GADWebViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <GADWebViewActiveViewMonitoring> activeViewObserver; // @synthesize activeViewObserver=_activeViewObserver;
@property(nonatomic) BOOL activeViewVisibility; // @synthesize activeViewVisibility=_activeViewVisibility;
@property(nonatomic) BOOL activeViewUnloadPingReceived; // @synthesize activeViewUnloadPingReceived=_activeViewUnloadPingReceived;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) id <GADWebViewDelegate> savedDelegate; // @synthesize savedDelegate=_savedDelegate;
@property(retain, nonatomic) UIView *savedSuperview; // @synthesize savedSuperview=_savedSuperview;
@property(nonatomic) struct CGRect savedFrame; // @synthesize savedFrame=_savedFrame;
@property(nonatomic) BOOL savedState; // @synthesize savedState=_savedState;
@property(retain, nonatomic) UIAlertView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) GADImpressionTicketGestureRecognizer *gesture; // @synthesize gesture=_gesture;
@property(retain, nonatomic) GADUIWebViewGestureDelegate *gestureDelegate; // @synthesize gestureDelegate=_gestureDelegate;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(nonatomic) BOOL didReceiveLoadEvent; // @synthesize didReceiveLoadEvent=_didReceiveLoadEvent;
@property(nonatomic) BOOL showDebug; // @synthesize showDebug=_showDebug;
@property(copy, nonatomic) NSString *adDebugDialog; // @synthesize adDebugDialog=_adDebugDialog;
@property(nonatomic) BOOL touched; // @synthesize touched=_touched;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSURLRequest *request;
@property(readonly, nonatomic, getter=isLoading) BOOL loading;
@property(readonly, nonatomic, getter=canGoForward) BOOL canGoForward;
@property(readonly, nonatomic, getter=canGoBack) BOOL canGoBack;
@property(nonatomic) BOOL mediaPlaybackRequiresUserAction;
- (void)setFrame:(struct CGRect)arg1;
@property(nonatomic) unsigned int dataDetectorTypes;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (BOOL)isOpaque;
- (void)setOpaque:(BOOL)arg1;
@property(readonly, retain, nonatomic) UIScrollView *scrollView;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)reload;
- (void)stopLoading;
- (void)goForward;
- (void)goBack;
- (void)loadRequest:(id)arg1;
- (id)stringByEvaluatingJavaScriptFromString:(id)arg1;
- (void)setURL:(id)arg1 forView:(id)arg2;
- (void)handleGesture:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)createGestureRecognizer;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)didRotateToOrientation:(int)arg1;
- (void)forceRotateToOrientation:(int)arg1;
- (void)setHTMLWindowOrientation:(int)arg1 shouldDispatchOrientationChangeEvent:(BOOL)arg2;
- (void)notifyOfSdkEvent:(id)arg1;
- (void)restoreState;
- (void)saveState;
- (void)dealloc;
- (void)reset;
- (void)reportBadAd:(id)arg1;
- (void)loadHTMLString:(id)arg1 baseURL:(id)arg2;
- (void)configureAsBannerAdView;
- (void)configureAsInterstitialAdView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

