//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "UIWebViewDelegate.h"

@class NSString, NSURL, NSURLRequest, SCHeader, UIActivityIndicatorView, UIWebView;

@interface InformationSettingsViewController : UIViewController <SCHeaderDataSource, SCHeaderDelegate, UIWebViewDelegate>
{
    BOOL _snapcash;
    SCHeader *_header;
    UIWebView *_webView;
    NSURL *_url;
    UIActivityIndicatorView *_activityIndicatorView;
    NSURLRequest *_request;
    NSString *_implicitTitle;
}

@property(retain, nonatomic) NSString *implicitTitle; // @synthesize implicitTitle=_implicitTitle;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(nonatomic) BOOL snapcash; // @synthesize snapcash=_snapcash;
- (void).cxx_destruct;
- (BOOL)shouldPopToRootViewControllerLater;
- (BOOL)shouldPopToRootViewController;
- (void)leftButtonPressed;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)viewWillAppear:(BOOL)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (void)dealloc;
- (void)initHeader;
- (void)loadView;
- (id)getPageViewName;
- (id)initWithRequest:(id)arg1;
- (id)initWithURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

