//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CaptionDelegate.h"
#import "SCDrawingDelegate.h"
#import "SnapVideoFilterDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITextFieldDelegate.h"

@class AVPlayerLayer, CaptionTextField, DrawingButton, LoadingView, NSString, NSURL, SCDrawingView, SCGrowingButton, SCImageSwipeFilterView, SnapVideoFilter, UIButton, UIImage, UIImageView, UILabel, UIView;

@interface KidPreviewViewController : UIViewController <UITextFieldDelegate, UIAlertViewDelegate, CaptionDelegate, SCDrawingDelegate, SnapVideoFilterDelegate>
{
    BOOL _didInvert;
    BOOL _audioEnabled;
    BOOL _captionPresent;
    BOOL _drawing;
    BOOL _mirrorVideo;
    BOOL _savingVideo;
    UIButton *_audioButton;
    UILabel *_captionHelp;
    CaptionTextField *_captionTextField;
    UIView *_containerView;
    DrawingButton *_drawingButton;
    SCDrawingView *_drawingView;
    LoadingView *_loadingView;
    UIView *_optionsView;
    UIImageView *_overlayView;
    AVPlayerLayer *_playerLayer;
    UIButton *_saveButton;
    SnapVideoFilter *_snapVideoFilter;
    UIImage *_sourceImage;
    SCImageSwipeFilterView *_imageSwipeFilterView;
    NSURL *_videoURL;
    SCGrowingButton *_xButton;
}

@property(retain, nonatomic) SCGrowingButton *xButton; // @synthesize xButton=_xButton;
@property(retain, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(retain, nonatomic) SCImageSwipeFilterView *imageSwipeFilterView; // @synthesize imageSwipeFilterView=_imageSwipeFilterView;
@property(retain, nonatomic) UIImage *sourceImage; // @synthesize sourceImage=_sourceImage;
@property(retain, nonatomic) SnapVideoFilter *snapVideoFilter; // @synthesize snapVideoFilter=_snapVideoFilter;
@property(nonatomic) BOOL savingVideo; // @synthesize savingVideo=_savingVideo;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(retain, nonatomic) UIImageView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) UIView *optionsView; // @synthesize optionsView=_optionsView;
@property(nonatomic) BOOL mirrorVideo; // @synthesize mirrorVideo=_mirrorVideo;
@property(retain, nonatomic) LoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) SCDrawingView *drawingView; // @synthesize drawingView=_drawingView;
@property(retain, nonatomic) DrawingButton *drawingButton; // @synthesize drawingButton=_drawingButton;
@property(nonatomic) BOOL drawing; // @synthesize drawing=_drawing;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) CaptionTextField *captionTextField; // @synthesize captionTextField=_captionTextField;
@property(nonatomic) BOOL captionPresent; // @synthesize captionPresent=_captionPresent;
@property(retain, nonatomic) UILabel *captionHelp; // @synthesize captionHelp=_captionHelp;
@property(nonatomic) BOOL audioEnabled; // @synthesize audioEnabled=_audioEnabled;
@property(retain, nonatomic) UIButton *audioButton; // @synthesize audioButton=_audioButton;
@property(nonatomic) BOOL didInvert; // @synthesize didInvert=_didInvert;
- (void).cxx_destruct;
- (void)setActionButtonsForDrawingHidden:(BOOL)arg1;
- (void)didEndDrawing;
- (void)didStartDrawing;
- (void)didAlterDrawing;
- (void)drawingEnabled:(BOOL)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)textFieldShouldEndEditing:(id)arg1;
- (BOOL)textFieldShouldBeginEditing:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)shouldShowCaption;
- (void)captionTapped;
- (void)didStartEditingCaption;
- (void)didStopEditingCaption;
- (void)didAlterCaption;
- (BOOL)canStartEditingCaption;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)showVideo;
- (void)removeVideo;
- (void)resetVideo;
- (void)setVideo:(id)arg1 front:(BOOL)arg2;
- (void)setImage:(id)arg1;
- (void)didBecomeActive:(id)arg1;
- (void)playerItemDidReachEnd:(id)arg1;
- (void)viewDidLoad;
- (void)exitPreview;
- (void)xPressed;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)savePressed;
- (void)setActionButtonsHidden:(BOOL)arg1;
- (void)saveVideo;
- (id)getImage:(BOOL)arg1 withCaption:(BOOL)arg2;
- (id)getImage;
- (void)willHideKeyboard:(id)arg1;
- (void)willShowKeyboard:(id)arg1;
- (void)audioPressed;
- (BOOL)shouldPopToRootViewController;
- (void)dealloc;
- (void)loadView;
- (void)filterVideo:(BOOL)arg1 withCaption:(BOOL)arg2;
- (void)didFinishSavingSnapToAlbumWithError:(id)arg1 isVideo:(BOOL)arg2;
- (void)videoProcessingDidFailForSnapVideoFilter:(id)arg1 error:(id)arg2;
- (void)videoProcessingDidSucceedForSnapVideoFilter:(id)arg1 data:(id)arg2;
- (void)isImage:(BOOL)arg1;
- (id)getPageViewParams;
- (id)getPageViewName;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

