//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCCameraBackgroundViewController.h"

@class UIColor, UIImageView;

@interface LoginRegisterViewController : SCCameraBackgroundViewController
{
    UIColor *_backgroundPatternColor;
    UIImageView *_ghostFaceImageView;
}

@property(retain, nonatomic) UIImageView *ghostFaceImageView; // @synthesize ghostFaceImageView=_ghostFaceImageView;
@property(retain, nonatomic) UIColor *backgroundPatternColor; // @synthesize backgroundPatternColor=_backgroundPatternColor;
- (void).cxx_destruct;
- (void)removeObservers;
- (void)addObservers;
- (void)newMemberButtonClicked;
- (void)snapchatterButtonClicked;
- (void)touchUpOutside;
- (void)touchDownInsideButton;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (void)loadView;
- (id)getPageViewName;

@end

