//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class AVPlayer, NSCondition, NSData, NSDate, NSMutableDictionary, NSString, NSTimer, User;

@interface Manager : NSObject <UIAlertViewDelegate>
{
    BOOL _didAppStartupComplete;
    BOOL _processingVideo;
    BOOL _shouldRecordFirstSnapWhenLaunchApp;
    BOOL _shouldRecordFirstStoryWhenLaunchApp;
    BOOL _didMainViewAppear;
    BOOL _didCameraOpen;
    BOOL _didAutoLoadViewsComplete;
    BOOL _fetchingAllUpdatesFromServer;
    NSTimer *_snapDataTimer;
    User *_user;
    NSMutableDictionary *_times;
    AVPlayer *_centralPlayerA;
    AVPlayer *_centralPlayerB;
    AVPlayer *_centralPlayerC;
    NSTimer *_centralTimer;
    NSDate *_referenceDateForFeedTimestamps;
    NSData *_pushNotificationDeviceToken;
    unsigned int _seqno;
    NSCondition *_appStartupCondition;
}

+ (void)clearUnusedVideoURLsFromSnaps:(id)arg1;
+ (id)shared;
@property(retain, nonatomic) NSCondition *appStartupCondition; // @synthesize appStartupCondition=_appStartupCondition;
@property(nonatomic) unsigned int seqno; // @synthesize seqno=_seqno;
@property(retain, nonatomic) NSData *pushNotificationDeviceToken; // @synthesize pushNotificationDeviceToken=_pushNotificationDeviceToken;
@property(nonatomic) BOOL fetchingAllUpdatesFromServer; // @synthesize fetchingAllUpdatesFromServer=_fetchingAllUpdatesFromServer;
@property(nonatomic) BOOL didAutoLoadViewsComplete; // @synthesize didAutoLoadViewsComplete=_didAutoLoadViewsComplete;
@property(nonatomic) BOOL didCameraOpen; // @synthesize didCameraOpen=_didCameraOpen;
@property(nonatomic) BOOL didMainViewAppear; // @synthesize didMainViewAppear=_didMainViewAppear;
@property(nonatomic) BOOL shouldRecordFirstStoryWhenLaunchApp; // @synthesize shouldRecordFirstStoryWhenLaunchApp=_shouldRecordFirstStoryWhenLaunchApp;
@property(nonatomic) BOOL shouldRecordFirstSnapWhenLaunchApp; // @synthesize shouldRecordFirstSnapWhenLaunchApp=_shouldRecordFirstSnapWhenLaunchApp;
@property(retain, nonatomic) NSDate *referenceDateForFeedTimestamps; // @synthesize referenceDateForFeedTimestamps=_referenceDateForFeedTimestamps;
@property(retain, nonatomic) NSTimer *centralTimer; // @synthesize centralTimer=_centralTimer;
@property(retain, nonatomic) AVPlayer *centralPlayerC; // @synthesize centralPlayerC=_centralPlayerC;
@property(retain, nonatomic) AVPlayer *centralPlayerB; // @synthesize centralPlayerB=_centralPlayerB;
@property(retain, nonatomic) AVPlayer *centralPlayerA; // @synthesize centralPlayerA=_centralPlayerA;
@property(retain, nonatomic) NSMutableDictionary *times; // @synthesize times=_times;
@property(retain, nonatomic) User *user; // @synthesize user=_user;
@property(retain, nonatomic) NSTimer *snapDataTimer; // @synthesize snapDataTimer=_snapDataTimer;
@property(nonatomic) BOOL processingVideo; // @synthesize processingVideo=_processingVideo;
- (void).cxx_destruct;
- (void)postServerChallenge;
- (void)signalWhenAppStartupComplete;
- (void)waitUntilAppStartupCompleteWithCallback:(CDUnknownBlockType)arg1;
@property(nonatomic) BOOL didAppStartupComplete; // @synthesize didAppStartupComplete=_didAppStartupComplete;
- (void)logConversationsResponse:(id)arg1;
- (void)clearInactiveFilteredVideos;
- (void)clearViewedStories;
- (void)clearExpiredStories;
- (void)clearExpiredAndViewedStories;
- (BOOL)userHasValidRequest;
- (void)willEnterForeground;
- (void)didEnterBackground;
- (void)prepareForBecomeActiveWithRemoteNotification:(id)arg1;
- (void)prepareForResignActive;
- (void)startTimer:(id)arg1;
- (void)startTimerIfNecessary;
- (void)markSnapAsViewed:(id)arg1;
- (void)tick:(id)arg1;
- (BOOL)hasUnviewedChats;
- (BOOL)hasUnviewedCash;
- (int)hasUnviewedSnaps;
- (int)unreadCount;
- (void)registerDeviceToken:(id)arg1;
- (void)loadStories;
- (void)loadMySharedStories;
- (void)loadMyStories;
- (void)loadUnviewedStoriesWithLimit:(int)arg1 sharedStories:(BOOL)arg2;
- (void)loadUnviewedStories;
- (void)loadRecentSnapStacks;
- (void)checkMobile;
- (void)verifyMobile:(id)arg1;
- (void)setMobile:(id)arg1 withCountryCode:(id)arg2 phoneCall:(BOOL)arg3 reverified:(BOOL)arg4;
- (void)verifyCaptchaWithId:(id)arg1 solution:(id)arg2 successQueue:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)fetchCaptchaImagesWithSuccessQueue:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)deleteKidsAccountWithHashedEmail:(id)arg1;
- (void)deleteKidsAccount;
- (void)doLogoutRequest;
- (void)kidLogout;
- (void)logout;
- (CDUnknownBlockType)fetchConversationsFailureBlock;
- (CDUnknownBlockType)fetchStoriesFailureBlock;
- (CDUnknownBlockType)fetchUpdatesFailureBlock;
- (CDUnknownBlockType)fetchStoriesSuccessBlock;
- (CDUnknownBlockType)fetchConversationsSuccessBlock;
- (CDUnknownBlockType)fetchUpdatesSuccessBlock;
- (void)fetchStoriesWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)fetchStories;
- (void)fetchUpdatesWithCompletionHandler:(CDUnknownBlockType)arg1 includeStories:(BOOL)arg2 didHappendWhenAppLaunch:(BOOL)arg3;
- (void)fetchUpdates;
- (void)fetchUpdatesAndStoriesFromLaunch;
- (void)fetchUpdatesAndStories;
- (id)parametersForFetchUpdates;
- (void)reportSponsoredStoriesImpressionsRequired:(BOOL)arg1;
- (void)markViewedStories;
- (void)markViewedSnaps;
- (id)getUpdatedSnapsJsonWithUpdatedSnaps:(id)arg1;
- (id)getUpdatedSnapsDictionaryWithUpdatedSnaps:(id)arg1;
- (id)jsonStringForEvents:(id)arg1;
- (void)handlePushNotificationWithInfo:(id)arg1;
- (BOOL)compareSeqno:(unsigned int)arg1;
- (void)incSeqno;
- (unsigned int)getSeqno;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

