//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class AVPlayerItem, NSData, NSNumber, NSString;

@interface Media : NSObject <NSCoding>
{
    BOOL _isLoading;
    BOOL _overlayPresent;
    BOOL _isThumbnail;
    id <MediaDataSource> _dataSource;
    NSData *_mediaDataToUpload;
    id <MediaDelegate> _delegate;
    NSNumber *_captionScreenPosition;
    NSNumber *_captionOrientation;
    NSString *_captionText;
    NSData *_overlayDataToUpload;
    AVPlayerItem *_playerItem;
    id <MediaUploadDelegate> _uploadDelegate;
    id <MediaImageProcessingDelegate> _imageProcessingDelegate;
    int _loadContext;
}

+ (id)mediaKeyFromFilename:(id)arg1;
+ (id)imageWithImage:(id)arg1 scaledToSize:(struct CGSize)arg2;
+ (id)thumbnailFromMedia:(id)arg1 videoFilter:(id)arg2;
@property(nonatomic) BOOL isThumbnail; // @synthesize isThumbnail=_isThumbnail;
@property(nonatomic) int loadContext; // @synthesize loadContext=_loadContext;
@property(nonatomic) __weak id <MediaImageProcessingDelegate> imageProcessingDelegate; // @synthesize imageProcessingDelegate=_imageProcessingDelegate;
@property(nonatomic) __weak id <MediaUploadDelegate> uploadDelegate; // @synthesize uploadDelegate=_uploadDelegate;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) NSData *overlayDataToUpload; // @synthesize overlayDataToUpload=_overlayDataToUpload;
@property(nonatomic) BOOL overlayPresent; // @synthesize overlayPresent=_overlayPresent;
@property(nonatomic) BOOL isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) NSString *captionText; // @synthesize captionText=_captionText;
@property(retain, nonatomic) NSNumber *captionOrientation; // @synthesize captionOrientation=_captionOrientation;
@property(retain, nonatomic) NSNumber *captionScreenPosition; // @synthesize captionScreenPosition=_captionScreenPosition;
@property(nonatomic) __weak id <MediaDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSData *mediaDataToUpload; // @synthesize mediaDataToUpload=_mediaDataToUpload;
@property(nonatomic) __weak id <MediaDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (BOOL)isImage;
- (BOOL)isVideoWithSound;
- (BOOL)isVideo;
- (void)fetchMedia;
- (void)uploadWithDataAndParameters:(id)arg1 parameters:(id)arg2;
- (void)upload;
- (void)imageProcessingDone;
- (void)imageFromCacheWithCompletion:(CDUnknownBlockType)arg1;
- (id)videoPath;
- (void)initPlayerItemWithCompletion:(CDUnknownBlockType)arg1;
- (void)writeVideoToURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)saveDataToCache:(id)arg1;
- (void)mediaFromCacheWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)archiveSnapData:(id)arg1 overlayData:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)unarchiveSnapAndOverlayFromData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)copyDataFromMedia:(id)arg1;
- (void)setArchivedDataToUpload:(id)arg1;
- (id)dataToUpload;
- (BOOL)isBroadcast;
- (id)mediaId;
- (BOOL)isLoaded;
- (void)removeFromDisk;
- (void)removeFromCache;
- (BOOL)hasSeparateCaption;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;

@end

