//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Media, NSData, NSDictionary, NSString, NSURL;

@protocol MediaDataSource <NSObject>
- (BOOL)encrypt;
- (BOOL)persist;
- (NSDictionary *)encryptionDictionaryForMedia:(Media *)arg1;
- (NSData *)decryptData:(NSData *)arg1 forMedia:(Media *)arg2;
- (NSString *)mediaIdForMedia:(Media *)arg1;

@optional
- (NSDictionary *)endpointParamsForMedia:(Media *)arg1;
- (NSString *)endpointForMedia:(Media *)arg1;
- (NSURL *)URLForMedia:(Media *)arg1;
@end

