//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AddFriendCellDelegate.h"
#import "EGORefreshTableHeaderDelegate.h"
#import "FriendsTableIndexDelegate.h"
#import "MyProfileStoryCellDelegate.h"
#import "SCFriendSearcherDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCSearchBarDelegate.h"
#import "SCStoryExporterDelegate.h"
#import "SendTextControllerDelegate.h"
#import "StoriesCellDelegate.h"
#import "SwipeView.h"
#import "UIAlertViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class AddFriendsDelegateObject, EGORefreshTableHeaderView, Friend, FriendsTableIndex, LoadingView, NSArray, NSString, SCAlertView, SCButton, SCFriendFilter, SCFriendSearcher, SCHeader, SCMediaView, SCNoFriendStoriesView, SCPurpleTooltipBalloon, SCSearchBar, SCStoryExporter, Story, UIImageView, UILabel, UILongPressGestureRecognizer, UITableView, UITapGestureRecognizer;

@interface MyFriendsViewController : UIViewController <SCSearchBarDelegate, UITextFieldDelegate, UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate, FriendsTableIndexDelegate, UIScrollViewDelegate, SendTextControllerDelegate, UIGestureRecognizerDelegate, EGORefreshTableHeaderDelegate, StoriesCellDelegate, MyProfileStoryCellDelegate, AddFriendCellDelegate, SCHeaderDataSource, SCHeaderDelegate, SCFriendSearcherDelegate, SCStoryExporterDelegate, SwipeView>
{
    BOOL _addingFriend;
    BOOL _addingRecent;
    BOOL _animationInProgress;
    BOOL _didEditDisplayName;
    BOOL _reloading;
    BOOL _searching;
    BOOL _selectedFriendError;
    BOOL _showingSearchBar;
    BOOL _firstFetchUpdatesRequest;
    BOOL _didLogFirstRecentUpdateReady;
    BOOL _didAddObserver;
    id <NavigationDelegate> _navigationDelegate;
    id <ReplyDelegate> _replyDelegate;
    id <SwipeViewParentDelegate> _parentDelegate;
    AddFriendsDelegateObject *_addFriendsDelegate;
    UIImageView *_stillBackgroundImageView;
    UIImageView *_animatedBackgroundImageView;
    Friend *_editingFriend;
    SCPurpleTooltipBalloon *_discoverButtonTooltip;
    NSArray *_filteredFriends;
    NSArray *_friendKeys;
    NSArray *_friends;
    SCFriendFilter *_friendFilter;
    int _friendStoriesViewingType;
    SCHeader *_header;
    Story *_lastVisibleStory;
    float _lastYOffsetBeforeScrolling;
    LoadingView *_loadingView;
    UITapGestureRecognizer *_doubleTapGestureRecognizer;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UITapGestureRecognizer *_tapToSkipGestureRecognizer;
    SCMediaView *_mediaView;
    EGORefreshTableHeaderView *_refreshHeaderView;
    SCSearchBar *_searchBar;
    SCFriendSearcher *_friendSearcher;
    UILabel *_noSearchResultsLabel;
    SCButton *_addFriendsButton;
    SCNoFriendStoriesView *_noFriendStoriesView;
    int _sectionForExpandedStoriesGroup;
    Friend *_selectedFriend;
    Friend *_selectedSharedStoryFriend;
    FriendsTableIndex *_tableIndex;
    UITableView *_tableView;
    NSString *_viewingStoriesUsername;
    Story *_selectedMyStory;
    Story *_visibleStory;
    Story *_visibleMyStory;
    SCAlertView *_displayNameAlertView;
    SCStoryExporter *_myStoryExporter;
}

@property(retain, nonatomic) SCStoryExporter *myStoryExporter; // @synthesize myStoryExporter=_myStoryExporter;
@property(nonatomic) BOOL didAddObserver; // @synthesize didAddObserver=_didAddObserver;
@property(nonatomic) BOOL didLogFirstRecentUpdateReady; // @synthesize didLogFirstRecentUpdateReady=_didLogFirstRecentUpdateReady;
@property(nonatomic) BOOL firstFetchUpdatesRequest; // @synthesize firstFetchUpdatesRequest=_firstFetchUpdatesRequest;
@property(retain, nonatomic) SCAlertView *displayNameAlertView; // @synthesize displayNameAlertView=_displayNameAlertView;
@property(retain, nonatomic) Story *visibleMyStory; // @synthesize visibleMyStory=_visibleMyStory;
@property(retain, nonatomic) Story *visibleStory; // @synthesize visibleStory=_visibleStory;
@property(retain, nonatomic) Story *selectedMyStory; // @synthesize selectedMyStory=_selectedMyStory;
@property(retain, nonatomic) NSString *viewingStoriesUsername; // @synthesize viewingStoriesUsername=_viewingStoriesUsername;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) FriendsTableIndex *tableIndex; // @synthesize tableIndex=_tableIndex;
@property(nonatomic) BOOL showingSearchBar; // @synthesize showingSearchBar=_showingSearchBar;
@property(retain, nonatomic) Friend *selectedSharedStoryFriend; // @synthesize selectedSharedStoryFriend=_selectedSharedStoryFriend;
@property(nonatomic) BOOL selectedFriendError; // @synthesize selectedFriendError=_selectedFriendError;
@property(retain, nonatomic) Friend *selectedFriend; // @synthesize selectedFriend=_selectedFriend;
@property(nonatomic) int sectionForExpandedStoriesGroup; // @synthesize sectionForExpandedStoriesGroup=_sectionForExpandedStoriesGroup;
@property(retain, nonatomic) SCNoFriendStoriesView *noFriendStoriesView; // @synthesize noFriendStoriesView=_noFriendStoriesView;
@property(retain, nonatomic) SCButton *addFriendsButton; // @synthesize addFriendsButton=_addFriendsButton;
@property(retain, nonatomic) UILabel *noSearchResultsLabel; // @synthesize noSearchResultsLabel=_noSearchResultsLabel;
@property(nonatomic) BOOL searching; // @synthesize searching=_searching;
@property(retain, nonatomic) SCFriendSearcher *friendSearcher; // @synthesize friendSearcher=_friendSearcher;
@property(retain, nonatomic) SCSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) BOOL reloading; // @synthesize reloading=_reloading;
@property(retain, nonatomic) EGORefreshTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
@property(retain, nonatomic) SCMediaView *mediaView; // @synthesize mediaView=_mediaView;
@property(retain, nonatomic) UITapGestureRecognizer *tapToSkipGestureRecognizer; // @synthesize tapToSkipGestureRecognizer=_tapToSkipGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *doubleTapGestureRecognizer; // @synthesize doubleTapGestureRecognizer=_doubleTapGestureRecognizer;
@property(retain, nonatomic) LoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) float lastYOffsetBeforeScrolling; // @synthesize lastYOffsetBeforeScrolling=_lastYOffsetBeforeScrolling;
@property(retain, nonatomic) Story *lastVisibleStory; // @synthesize lastVisibleStory=_lastVisibleStory;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(nonatomic) int friendStoriesViewingType; // @synthesize friendStoriesViewingType=_friendStoriesViewingType;
@property(retain, nonatomic) SCFriendFilter *friendFilter; // @synthesize friendFilter=_friendFilter;
@property(retain, nonatomic) NSArray *friends; // @synthesize friends=_friends;
@property(retain, nonatomic) NSArray *friendKeys; // @synthesize friendKeys=_friendKeys;
@property(retain, nonatomic) NSArray *filteredFriends; // @synthesize filteredFriends=_filteredFriends;
@property(retain, nonatomic) SCPurpleTooltipBalloon *discoverButtonTooltip; // @synthesize discoverButtonTooltip=_discoverButtonTooltip;
@property(nonatomic) BOOL didEditDisplayName; // @synthesize didEditDisplayName=_didEditDisplayName;
@property(retain, nonatomic) Friend *editingFriend; // @synthesize editingFriend=_editingFriend;
@property(nonatomic) BOOL animationInProgress; // @synthesize animationInProgress=_animationInProgress;
@property(retain, nonatomic) UIImageView *animatedBackgroundImageView; // @synthesize animatedBackgroundImageView=_animatedBackgroundImageView;
@property(retain, nonatomic) UIImageView *stillBackgroundImageView; // @synthesize stillBackgroundImageView=_stillBackgroundImageView;
@property(nonatomic) BOOL addingRecent; // @synthesize addingRecent=_addingRecent;
@property(nonatomic) BOOL addingFriend; // @synthesize addingFriend=_addingFriend;
@property(retain, nonatomic) AddFriendsDelegateObject *addFriendsDelegate; // @synthesize addFriendsDelegate=_addFriendsDelegate;
@property(nonatomic) __weak id <SwipeViewParentDelegate> parentDelegate; // @synthesize parentDelegate=_parentDelegate;
@property(nonatomic) __weak id <ReplyDelegate> replyDelegate; // @synthesize replyDelegate=_replyDelegate;
@property(nonatomic) __weak id <NavigationDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
- (void).cxx_destruct;
- (void)addFriendsButtonPressed;
- (BOOL)egoRefreshTableHeaderDataSourceIsLoading:(id)arg1;
- (void)egoRefreshTableHeaderDidTriggerRefresh:(id)arg1;
- (void)infoButtonPressed:(id)arg1;
- (void)didSelectAddFriendCell:(id)arg1;
- (void)storyExporter:(id)arg1 didFinishExportingToURL:(id)arg2 withError:(id)arg3;
- (void)storyExporter:(id)arg1 didProceedToProgress:(float)arg2;
- (void)saveEntireStoryAlertView:(id)arg1 didClickButtonWithIndex:(int)arg2;
- (void)handleUnblockOption;
- (void)handleBlockOption;
- (void)handleEditNameOption;
- (void)handleDeleteOption;
- (void)friendOptionsAlertView:(id)arg1 didClickButtonWithIndex:(int)arg2;
- (void)displayNameAlertView:(id)arg1 didClickButtonWithIndex:(int)arg2;
- (void)myStoryAlertView:(id)arg1 didClickButtonWithIndex:(int)arg2;
- (void)sharedStoryInfoAlertView:(id)arg1 didClickButtonWithIndex:(int)arg2;
- (BOOL)alertViewShouldEnableFirstOtherButton:(id)arg1;
- (void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (id)getHeaderTextForSection:(int)arg1;
- (void)validateDisplayNameInTextField:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)mySharedStoryInfoPressedForStoriesCell:(id)arg1;
- (void)sharedStoryInfoPressedForStoriesCell:(id)arg1;
- (void)savePressedForStoriesCell:(id)arg1;
- (void)settingsPressedForStoriesCell:(id)arg1;
- (void)replySnapButtonPressedForStoriesCell:(id)arg1;
- (void)handleDidSelectFriendStoriesCellAtIndexPath:(id)arg1;
- (void)handleTableViewScrollUpdateForStory:(id)arg1;
- (void)handleDidSelectMyStoryCellAtIndexPath:(id)arg1;
- (void)handleDidSelectMySharedStoriesCellAtIndexPath:(id)arg1;
- (void)handleDidSelectMyProfileCellAtIndexPath;
- (void)handleDidSelectRowAtIndexPath:(id)arg1;
- (void)sendTextController:(id)arg1 compeletedWithStatus:(int)arg2;
- (id)sponsoredStoryForIndexPath:(id)arg1;
- (void)logVisibleSponsoredStories;
- (unsigned int)sectionForSharedStories:(id)arg1;
- (id)sharedStoriesForSection:(unsigned int)arg1;
- (id)sharedStoriesToDisplay;
- (id)mySharedStoriesCollection;
- (id)myStoriesGroupForStory:(id)arg1;
- (void)myStoryPlayerItemDidReachEnd:(id)arg1;
- (id)myStoriesArray;
- (id)cellForMyStory:(id)arg1;
- (id)myStoryForIndexPath:(id)arg1;
- (int)storyNotesCountForStory:(id)arg1;
- (id)myStoryForPoint:(struct CGPoint)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 forStory:(id)arg3;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 forStory:(id)arg3;
- (void)deletePressedForStory:(id)arg1;
- (void)savePressedForStory:(id)arg1;
- (BOOL)isMyStoriesExpandedForSection:(unsigned int)arg1;
- (void)toggleMyStoriesSection:(int)arg1;
- (void)showMyStoriesForSection:(int)arg1 oldSection:(int)arg2;
- (id)indexPathForFriendInSearch:(id)arg1;
- (BOOL)shouldShowNotificationInCurrentMediaState;
- (id)storiesIndexPathsForUsername:(id)arg1;
- (id)usernameForStoriesAtIndexPath:(id)arg1;
- (BOOL)hasViewableFriendStories;
- (BOOL)hasUnviewedSharedStories;
- (BOOL)hasUnviewedFriendStories;
- (id)friendStoriesCollection;
- (BOOL)gestureRecognizer:(id)arg1 isWithinTopOfCellAtIndexPath:(id)arg2;
- (id)usernameForIndexPath:(id)arg1;
- (BOOL)searchingIndexOutOfBounds:(id)arg1;
- (id)storiesForIndexPath:(id)arg1;
- (id)cellForFriend:(id)arg1;
- (id)friendForCell:(id)arg1;
- (id)friendForIndexPath:(id)arg1;
- (void)setSelectedFriendFromIndexPath:(id)arg1;
- (id)myStoriesCell;
- (id)myStoriesCellIndexPath;
- (id)updatesIndexPathForUsername:(id)arg1;
- (id)indexPathForMyStories:(id)arg1;
- (id)indexPathForMyProfile;
- (id)indexPathForMyStory:(id)arg1;
- (id)indexPathForFriend:(id)arg1;
- (unsigned int)friendsSectionOffset;
- (struct _NSRange)rangeOfSharedStoriesSections;
- (unsigned int)liveSection;
- (unsigned int)recentUpdatesSection;
- (BOOL)isLiveSection:(int)arg1;
- (BOOL)isRecentUpdatesSection:(int)arg1;
- (BOOL)isNonStoryAtIndexPath:(id)arg1;
- (BOOL)isUnviewedStoriesIndex:(id)arg1;
- (BOOL)isFriendsStoriesIndexPath:(id)arg1;
- (BOOL)isMySharedStoryIndexPath:(id)arg1;
- (BOOL)isMySharedStoriesIndexPath:(id)arg1;
- (BOOL)isMyStoriesIndexPath:(id)arg1;
- (BOOL)isMyProfileIndexPath:(id)arg1;
- (float)totalFriendsSectionHeight;
- (void)showOrHideTableIndex;
- (void)doBackgroundAnimation;
- (void)triggerBackgroundAnimation;
- (void)updateTableAlpha;
- (void)scrollToIndex:(BOOL)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)friendCellForIndexPath:(id)arg1;
- (id)myStoryCellForIndexPath:(id)arg1;
- (id)mySharedStoriesCellForIndexPath:(id)arg1;
- (id)myProfileCellForIndexPath:(id)arg1;
- (void)updateFriendStoriesCell:(id)arg1 atIndexPath:(id)arg2;
- (id)friendStoriesCellForIndexPath:(id)arg1;
- (id)searchingSharedStoryCellForIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)preCellForRowAtIndexPath:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)friendSearcherDidUpdateResultsForQuery:(id)arg1;
- (void)handleChangeToExpandedStoriesSection:(id)arg1;
- (void)handleChangeToSelectedFriend:(id)arg1;
- (void)updateBackgroundImageViews;
- (void)updateNoFriendStoriesView;
- (void)updateAddFriendsButton;
- (void)updateNoSearchResultsLabel;
- (void)filterSearch:(id)arg1;
- (void)resetFriendFilter;
- (void)filterResults:(id)arg1;
- (void)searchBarKeyboardWillHide:(id)arg1;
- (void)searchBarDidBeginSearch:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBar:(id)arg1 didSearch:(id)arg2;
- (void)userDidTakeScreenshot;
- (void)didViewAllFriendStories;
- (void)friendsDidChange;
- (void)reloadFriends;
- (void)reloadAllData;
- (void)resetDiscoverButton;
- (void)discoverFullyViewed;
- (void)editionDidUpdate;
- (void)didUpdateSharedStories;
- (void)didFetchStories:(id)arg1;
- (void)storyDidFinish:(id)arg1;
- (void)storyDidExpire:(id)arg1;
- (void)myStoryDidFinish:(id)arg1;
- (void)showStatusBar;
- (void)hideMyStoriesAnimated:(BOOL)arg1 markAsViewed:(BOOL)arg2;
- (void)hideStoriesAnimated:(BOOL)arg1 markAsViewed:(BOOL)arg2;
- (void)clearTapToReplyCells;
- (void)removeStoryObserver:(id)arg1;
- (void)showFriendStoriesForUsername:(id)arg1 friendStoriesViewingType:(int)arg2 initialView:(BOOL)arg3;
- (void)touchesEndedForFriendStories:(id)arg1;
- (void)touchesCancelledForFriendStories:(id)arg1;
- (void)showSharedLocalStoryViewAlertWithSharedStoryId:(id)arg1;
- (void)touchesBeganForFriendStoriesCellWithIndexPath:(id)arg1;
- (void)showMyStoriesInSequence:(id)arg1;
- (void)touchesBeganForMySharedStoriesCellAtIndex:(id)arg1;
- (void)touchesBeganForMyProfileCell;
- (void)doubleTap:(id)arg1;
- (void)tap:(id)arg1;
- (void)tapToSkip:(id)arg1;
- (void)hideMyStory;
- (void)showMyStory:(id)arg1;
- (void)cancelScrollEvents;
- (void)longPress:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewDidFullyAppear;
- (void)viewDidPartiallyAppear;
- (void)viewDidFullyDisappear;
- (void)viewCanAppear;
- (void)handleSelectedStoryChange:(id)arg1;
- (void)handleChangeToStory:(id)arg1 keyPath:(id)arg2 change:(id)arg3;
- (void)handleKeyChange:(id)arg1 toMyStory:(id)arg2;
- (void)handleKeyChange:(id)arg1 toFriendsStories:(id)arg2;
- (void)handleKeyChange:(id)arg1 toFriendStories:(id)arg2 change:(id)arg3;
- (void)handleChangeToStateForSharedStories:(id)arg1;
- (void)handleChangeToMyStoriesState;
- (void)handleChangeToMyStoriesArray:(id)arg1 forStories:(id)arg2;
- (void)handleChangeToMySharedStoriesArray:(id)arg1;
- (void)handleChangeToFriendsStories:(id)arg1;
- (void)handleChangeToMyStories:(id)arg1;
- (void)handleChangeToMySharedStoriesCollection:(id)arg1;
- (void)handleChangeToFriendStoriesCollection:(id)arg1;
- (void)handleChangeToAllStories:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeMySelectedStoryObservers;
- (void)addMySelectedStoryObservers;
- (void)removeIndividualMyStoriesObservers:(id)arg1;
- (void)addIndividualMyStoriesObservers:(id)arg1;
- (void)removeMyStoriesObservers:(id)arg1;
- (void)addMyStoriesObservers:(id)arg1;
- (void)removeIndividualMySharedStoriesObservers:(id)arg1;
- (void)addIndividualMySharedStoriesObservers:(id)arg1;
- (void)removeMySharedStoriesObservers:(id)arg1;
- (void)addMySharedStoriesObservers:(id)arg1;
- (void)removeObserversOfFriendStories:(id)arg1 fromStoriesDictionary:(id)arg2;
- (void)removeIndividualFriendStoriesObservers:(id)arg1;
- (void)addIndividualFriendStoriesObservers:(id)arg1;
- (void)removeFriendStoriesObservers:(id)arg1;
- (void)addFriendStoriesObservers:(id)arg1;
- (void)removeStoriesObservers;
- (void)addStoriesObservers;
- (void)showDiscoverTooltip:(BOOL)arg1 withText:(id)arg2;
- (void)addDiscoverObservers;
- (float)preferredLeftButtonWidth;
- (void)rightButtonPressed;
- (void)leftButtonPressed;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)reloadTable;
- (void)didBecomeActive;
- (void)viewDidEnterBackground;
- (void)viewWillResignActive;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadBackgroundImageViews;
- (void)initHeader;
- (void)loadView;
- (BOOL)logOnViewDidAppear;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

