//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, SCTimedThumbnail, Story, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UITableView;

@interface MyProfileStoryCell : UITableViewCell <UITableViewDataSource, UITableViewDelegate>
{
    BOOL _forSharedStory;
    id <MyProfileStoryCellDelegate> _delegate;
    UIActivityIndicatorView *_thumbnailActivityIndicator;
    UIActivityIndicatorView *_saveAndDeleteActivityIndicator;
    UILabel *_captionLabel;
    UIImageView *_loadingThumbnail;
    UILabel *_screenshotCountLabel;
    UIImageView *_screenshotIcon;
    UIButton *_saveButton;
    UIButton *_deleteButton;
    Story *_story;
    UILabel *_subLabel;
    SCTimedThumbnail *_thumbnail;
    UILabel *_viewedCountLabel;
    UIImageView *_viewedIcon;
    UITableView *_viewersTable;
}

+ (float)expandedHeightForStoryNotesCount:(int)arg1;
+ (float)viewersTableHeightForNumberOfRows:(unsigned int)arg1;
@property(retain, nonatomic) UITableView *viewersTable; // @synthesize viewersTable=_viewersTable;
@property(retain, nonatomic) UIImageView *viewedIcon; // @synthesize viewedIcon=_viewedIcon;
@property(retain, nonatomic) UILabel *viewedCountLabel; // @synthesize viewedCountLabel=_viewedCountLabel;
@property(retain, nonatomic) SCTimedThumbnail *thumbnail; // @synthesize thumbnail=_thumbnail;
@property(retain, nonatomic) UILabel *subLabel; // @synthesize subLabel=_subLabel;
@property(retain, nonatomic) Story *story; // @synthesize story=_story;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) UIImageView *screenshotIcon; // @synthesize screenshotIcon=_screenshotIcon;
@property(retain, nonatomic) UILabel *screenshotCountLabel; // @synthesize screenshotCountLabel=_screenshotCountLabel;
@property(retain, nonatomic) UIImageView *loadingThumbnail; // @synthesize loadingThumbnail=_loadingThumbnail;
@property(nonatomic) BOOL forSharedStory; // @synthesize forSharedStory=_forSharedStory;
@property(retain, nonatomic) UILabel *captionLabel; // @synthesize captionLabel=_captionLabel;
@property(retain, nonatomic) UIActivityIndicatorView *saveAndDeleteActivityIndicator; // @synthesize saveAndDeleteActivityIndicator=_saveAndDeleteActivityIndicator;
@property(retain, nonatomic) UIActivityIndicatorView *thumbnailActivityIndicator; // @synthesize thumbnailActivityIndicator=_thumbnailActivityIndicator;
@property(nonatomic) __weak id <MyProfileStoryCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)deletePressed;
- (void)savePressed;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)setScreenshotCountHidden:(BOOL)arg1 viewCountHidden:(BOOL)arg2;
- (void)setCountsDisplayHidden:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1 isDeleting:(BOOL)arg2 isSaving:(BOOL)arg3;
- (void)setThumbnailFromCacheWithStory:(id)arg1;
- (void)updateWithStory:(id)arg1 expanded:(BOOL)arg2;
- (float)getPercent:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

