//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@protocol NavigationDelegate <NSObject>
- (void)goRightmostWithCompletion:(void (^)(SCDiscoverViewController *))arg1;
- (void)goRight:(UIViewController *)arg1 animated:(BOOL)arg2;
- (void)goLeft:(UIViewController *)arg1 animated:(BOOL)arg2;
@end

