//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (Helpers)
+ (id)dateOneDayFromToday;
+ (int)daysSinceTimestamp:(id)arg1;
+ (int)minutesSinceTimestamp:(id)arg1 forWaitPeriod:(float)arg2;
+ (id)shortStringFromDate:(id)arg1;
+ (id)dateWithoutTime:(id)arg1;
+ (BOOL)isDate:(id)arg1 afterDate:(id)arg2;
+ (BOOL)isDate:(id)arg1 beforeDate:(id)arg2;
+ (BOOL)isDate:(id)arg1 withinHourFromDate:(id)arg2;
+ (BOOL)isDate:(id)arg1 withinSameMinuteAsDate:(id)arg2;
+ (BOOL)isDate:(id)arg1 onSameDayOfTheYearAsDate:(id)arg2;
+ (id)calendar;
+ (BOOL)isDate:(id)arg1 sameDayAsDate:(id)arg2;
+ (id)stringFromDate:(id)arg1;
+ (id)serverTimestampFromDate:(id)arg1;
+ (id)dateFromServerTimestamp:(id)arg1;
+ (id)dateFromJsonString:(id)arg1;
+ (id)jsonStringFromDate:(id)arg1;
- (BOOL)hasThirteenYearsPassedSinceToday;
- (BOOL)isYesterday;
- (BOOL)isToday;
@end

