//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCLeftEdgeSwipableViewController.h"

#import "AddFriendCellDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SWTableViewCellDelegate.h"
#import "Subview.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AddFriendsDelegateObject, NSMutableArray, NSMutableSet, NSNumber, NSString, SCHeader, UILabel, UITableView;

@interface RequestTableViewController : SCLeftEdgeSwipableViewController <UIGestureRecognizerDelegate, UITableViewDataSource, UITableViewDelegate, AddFriendCellDelegate, SCHeaderDataSource, SCHeaderDelegate, SWTableViewCellDelegate, Subview>
{
    AddFriendsDelegateObject *_addFriendsDelegate;
    SCHeader *_header;
    UITableView *_tableView;
    NSNumber *_addedFriendsLastViewedTimestamp;
    NSMutableArray *_friends;
    UILabel *_noFriendsView;
    NSMutableSet *_friendsTouchedAtLeastOnce;
}

+ (id)requestsContext;
+ (id)createSpinner;
@property(retain, nonatomic) NSMutableSet *friendsTouchedAtLeastOnce; // @synthesize friendsTouchedAtLeastOnce=_friendsTouchedAtLeastOnce;
@property(retain, nonatomic) UILabel *noFriendsView; // @synthesize noFriendsView=_noFriendsView;
@property(retain, nonatomic) NSMutableArray *friends; // @synthesize friends=_friends;
@property(retain, nonatomic) NSNumber *addedFriendsLastViewedTimestamp; // @synthesize addedFriendsLastViewedTimestamp=_addedFriendsLastViewedTimestamp;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(retain, nonatomic) AddFriendsDelegateObject *addFriendsDelegate; // @synthesize addFriendsDelegate=_addFriendsDelegate;
- (void).cxx_destruct;
- (BOOL)shouldPopToRootViewControllerLater;
- (BOOL)shouldPopToRootViewController;
- (void)leftEdgeSwiped;
- (void)leftButtonPressed;
- (id)textColorForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)titleForHeader:(id)arg1;
- (void)didPressIgnoreButton:(id)arg1;
- (void)didPressBlockButton:(id)arg1;
- (void)didSelectAddFriendCell:(id)arg1;
- (void)swipeableTableViewCell:(id)arg1 didTriggerRightUtilityButtonWithIndex:(int)arg2;
- (void)removeAddedFriend:(id)arg1 atIndexPath:(id)arg2;
- (id)friendForIndexPath:(id)arg1;
- (id)addedFriendForIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)rightUtilityButtonsForPendingFriend:(BOOL)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)scrollToTop;
- (void)reloadFriends;
- (void)reloadTable;
- (void)reloadData;
- (void)friendsDidChange;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)initAndAddNoFriendRequestsView;
- (void)viewDidLoad;
- (void)loadView;
- (BOOL)logOnViewDidAppear;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

