//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Media;

@interface SCActiveVideoMedia : NSObject
{
    BOOL _cleanWhenLoaded;
    BOOL _counter;
    BOOL _hideWhenLoaded;
    BOOL _playWhenLoaded;
    CDUnknownBlockType _completion;
    Media *_media;
    int _state;
    int _slot;
    float _timeLeft;
    float _yOffset;
    int _counterShape;
    double _videoTimeSoFar;
}

@property(nonatomic) int counterShape; // @synthesize counterShape=_counterShape;
@property(nonatomic) float yOffset; // @synthesize yOffset=_yOffset;
@property(nonatomic) double videoTimeSoFar; // @synthesize videoTimeSoFar=_videoTimeSoFar;
@property(nonatomic) float timeLeft; // @synthesize timeLeft=_timeLeft;
@property(nonatomic) int slot; // @synthesize slot=_slot;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) BOOL playWhenLoaded; // @synthesize playWhenLoaded=_playWhenLoaded;
@property(retain, nonatomic) Media *media; // @synthesize media=_media;
@property(nonatomic) BOOL hideWhenLoaded; // @synthesize hideWhenLoaded=_hideWhenLoaded;
@property(nonatomic) BOOL counter; // @synthesize counter=_counter;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) BOOL cleanWhenLoaded; // @synthesize cleanWhenLoaded=_cleanWhenLoaded;
- (void).cxx_destruct;
- (id)initWithMedia:(id)arg1 withCounter:(BOOL)arg2 timeLeft:(float)arg3 videoTimeSoFar:(double)arg4 playWhenLoaded:(BOOL)arg5 slot:(int)arg6 counterShape:(int)arg7 completion:(CDUnknownBlockType)arg8;

@end

