//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCLeftEdgeSwipableViewController.h"

#import "AddFriendByNameCellDelegate.h"
#import "SCAddFriendCellDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCSearchFriendsSubViewControllerDelegate.h"
#import "SendTextControllerDelegate.h"

@class AddFriendsDelegateObject, Friend, NSMutableSet, NSString, SCHeader, SCSearchFriendsSubViewController, UIView;

@interface SCAddFriendViewController : SCLeftEdgeSwipableViewController <AddFriendByNameCellDelegate, SCAddFriendCellDelegate, SCHeaderDataSource, SCHeaderDelegate, SCSearchFriendsSubViewControllerDelegate, SendTextControllerDelegate>
{
    BOOL _hasInteractedWithTable;
    SCHeader *_header;
    AddFriendsDelegateObject *_addFriendsDelegate;
    SCSearchFriendsSubViewController *_searchFriendsSVC;
    UIView *_container;
    Friend *_friendBeingInvited;
    NSMutableSet *_temporarilyAddedFriends;
}

+ (id)searchContext;
+ (id)addFriendsContext;
@property(retain, nonatomic) NSMutableSet *temporarilyAddedFriends; // @synthesize temporarilyAddedFriends=_temporarilyAddedFriends;
@property(retain) Friend *friendBeingInvited; // @synthesize friendBeingInvited=_friendBeingInvited;
@property(retain, nonatomic) UIView *container; // @synthesize container=_container;
@property(retain, nonatomic) SCSearchFriendsSubViewController *searchFriendsSVC; // @synthesize searchFriendsSVC=_searchFriendsSVC;
@property(nonatomic) BOOL hasInteractedWithTable; // @synthesize hasInteractedWithTable=_hasInteractedWithTable;
@property(retain, nonatomic) AddFriendsDelegateObject *addFriendsDelegate; // @synthesize addFriendsDelegate=_addFriendsDelegate;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (BOOL)shouldPopToRootViewControllerLater;
- (BOOL)shouldPopToRootViewController;
- (void)resetFriendFilter;
- (id)addFriendCellForFriend:(id)arg1 onTableView:(id)arg2;
- (id)cellForModelView:(id)arg1 onTableView:(id)arg2 forRowAtindexPath:(id)arg3;
- (id)getSearchResultsBySection:(id)arg1 withSearchText:(id)arg2;
- (id)pageName;
- (void)sendTextController:(id)arg1 compeletedWithStatus:(int)arg2;
- (void)infoButtonPressed:(id)arg1 forFriend:(id)arg2;
- (void)sendInvitesToFriend:(id)arg1;
- (void)leftButtonPressed;
- (id)textColorForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)titleForHeader:(id)arg1;
- (void)didSelectAddFriendCell:(id)arg1;
- (void)didSelectAddFriendByNameCell:(id)arg1;
- (void)leftEdgeSwiped;
- (void)handleChangeToFindFriendsResults:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeFindFriendsObservers;
- (void)addFindFriendsObservers;
- (void)reloadData;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadView;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

