//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCLeftEdgeSwipableViewController.h"

#import "ContactsLoadingViewControllerDelegate.h"
#import "ContactsVCUserActionDelegate.h"
#import "SCContactsAccessDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCSearchBarDelegate.h"
#import "Subview.h"

@class AddFriendsDelegateObject, ContactsLoadingViewController, ContactsViewController, NSString, SCContactsAccessViewController, SCHeader, UIView;

@interface SCAddContactViewController : SCLeftEdgeSwipableViewController <ContactsLoadingViewControllerDelegate, ContactsVCUserActionDelegate, SCContactsAccessDelegate, SCHeaderDataSource, SCHeaderDelegate, SCSearchBarDelegate, Subview>
{
    SCHeader *_header;
    UIView *_container;
    ContactsLoadingViewController *_contactsLoadingVC;
    ContactsViewController *_contactsVC;
    SCContactsAccessViewController *_contactsAccessVC;
    AddFriendsDelegateObject *_addFriendsDelegate;
}

@property(retain, nonatomic) AddFriendsDelegateObject *addFriendsDelegate; // @synthesize addFriendsDelegate=_addFriendsDelegate;
@property(retain, nonatomic) SCContactsAccessViewController *contactsAccessVC; // @synthesize contactsAccessVC=_contactsAccessVC;
@property(retain, nonatomic) ContactsViewController *contactsVC; // @synthesize contactsVC=_contactsVC;
@property(retain, nonatomic) ContactsLoadingViewController *contactsLoadingVC; // @synthesize contactsLoadingVC=_contactsLoadingVC;
@property(retain, nonatomic) UIView *container; // @synthesize container=_container;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (BOOL)shouldPopToRootViewControllerLater;
- (BOOL)shouldPopToRootViewController;
- (void)leftEdgeSwiped;
- (void)leftButtonPressed;
- (id)textColorForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)titleForHeader:(id)arg1;
- (void)tryFindFriendsAgain;
- (void)accessToContactsGranted;
- (void)didGrantAccessSuccessfully;
- (void)startContactAccessWorkflow;
- (void)showContacts;
- (void)fetchContacts;
- (void)showContactsLoading;
- (void)showContactsAccessWorkflow;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadView;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

