//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCacheDelegate.h"
#import "NSCoding.h"

@class NSCache, NSMutableDictionary, NSString, SCAdManagerConfiguration, UIViewController;

@interface SCAdManager : NSObject <NSCoding, NSCacheDelegate>
{
    SCAdManagerConfiguration *_configuration;
    NSMutableDictionary *_cachedAdSections;
    UIViewController *_bannerViewController;
    NSCache *_controllers;
}

+ (id)path;
+ (BOOL)initialized;
+ (id)shared;
@property(retain, nonatomic) NSCache *controllers; // @synthesize controllers=_controllers;
@property(retain, nonatomic) UIViewController *bannerViewController; // @synthesize bannerViewController=_bannerViewController;
@property(retain, nonatomic) NSMutableDictionary *cachedAdSections; // @synthesize cachedAdSections=_cachedAdSections;
@property(retain, nonatomic) SCAdManagerConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (void)recordImpressionWithKey:(id)arg1 ifDuration:(double)arg2 exceedsLimit:(double)arg3 orFinished:(BOOL)arg4;
- (void)recordAdChunkImpression:(id)arg1 withInterval:(double)arg2 isFinished:(BOOL)arg3;
- (void)recordAdSplashImpressionForEndpoint:(id)arg1 withInterval:(double)arg2 isFinished:(BOOL)arg3;
- (void)cache:(id)arg1 willEvictObject:(id)arg2;
- (void)clearTransformedAds;
- (void)transformAdPlaceholderAsync:(id)arg1 withListener:(id)arg2;
- (id)createBannerView;
- (void)removeExpiredAdsForOwner:(id)arg1;
- (void)cacheSections:(id)arg1 forEndpoint:(id)arg2;
- (id)cachedSectionsForEndpoint:(id)arg1;
- (void)ensureNonNilObjects;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)clear;
- (BOOL)saveState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

