//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SCAdPlaceholder : NSObject
{
    NSString *_channelName;
    NSString *_editionId;
    NSString *_adId;
    unsigned int _adSlot;
    unsigned int _size;
    unsigned int _adType;
}

@property(nonatomic) unsigned int adType; // @synthesize adType=_adType;
@property(nonatomic) unsigned int size; // @synthesize size=_size;
@property(nonatomic) unsigned int adSlot; // @synthesize adSlot=_adSlot;
@property(copy, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(copy, nonatomic) NSString *editionId; // @synthesize editionId=_editionId;
@property(copy, nonatomic) NSString *channelName; // @synthesize channelName=_channelName;
- (void).cxx_destruct;
- (id)description;
- (id)initFromChannel:(id)arg1 edition:(id)arg2 chunk:(id)arg3 adSlot:(unsigned int)arg4 size:(unsigned int)arg5;

@end

