//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertView.h"

@class NSString;

@interface SCAlertView : UIAlertView
{
    BOOL _dismissWhenBackgrounded;
    NSString *_alertViewID;
}

@property(nonatomic) BOOL dismissWhenBackgrounded; // @synthesize dismissWhenBackgrounded=_dismissWhenBackgrounded;
@property(copy, nonatomic) NSString *alertViewID; // @synthesize alertViewID=_alertViewID;
- (void).cxx_destruct;
- (void)didEnterBackground:(id)arg1;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3 dismissWhenBackgrounded:(BOOL)arg4 cancelButtonTitle:(id)arg5 otherButtonTitles:(id)arg6;
- (id)initWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitles:(id)arg5;

@end

