//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface SCAnimatedCameraButtonOverlay : UIImageView
{
}

- (void)setImage:(id)arg1 withPercent:(float)arg2;

@end

