//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class Snap;

@interface SCAnimatingReplaySnapView : UIView
{
    Snap *_animatingSnap;
    int _viewType;
}

+ (BOOL)shouldDisplayAnimatingReplayForSnap:(id)arg1 viewType:(int)arg2;
@property(nonatomic) int viewType; // @synthesize viewType=_viewType;
@property(retain, nonatomic) Snap *animatingSnap; // @synthesize animatingSnap=_animatingSnap;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (id)animationCompletionBlockKey;
- (void)setSnapReplayAnimationState:(int)arg1;
- (void)hide;
- (void)animate;
- (id)initWithFrame:(struct CGRect)arg1 snap:(id)arg2 viewType:(int)arg3;

@end

