//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface SCArchiveDispatchQueuePool : NSObject
{
    unsigned int _numberOfQueuesCreated;
    NSMutableSet *_queues;
}

@property(retain, nonatomic) NSMutableSet *queues; // @synthesize queues=_queues;
@property(nonatomic) unsigned int numberOfQueuesCreated; // @synthesize numberOfQueuesCreated=_numberOfQueuesCreated;
- (void).cxx_destruct;
- (id)newQueue;
- (id)createQueueIfPossible;
- (void)storeQueue:(id)arg1;
- (id)fetchQueue;

@end

