//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCArchiveUtils : NSObject
{
}

+ (BOOL)saveObject:(id)arg1 toPath:(id)arg2;
+ (id)pathWithFileName:(id)arg1;

@end

