//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPClient.h"

@interface SCBaseAPIClient : AFHTTPClient
{
}

- (void)finishedRequestWithPath:(id)arg1 startTime:(double)arg2 success:(BOOL)arg3 requestSize:(double)arg4 responseSize:(double)arg5 hitCache:(BOOL)arg6 statusCode:(int)arg7 reachability:(int)arg8 responseDictionary:(id)arg9;
- (void)finishedRequestWithPath:(id)arg1 startTime:(double)arg2 success:(BOOL)arg3 requestSize:(double)arg4 responseSize:(double)arg5 hitCache:(BOOL)arg6 statusCode:(int)arg7 reachability:(int)arg8;
- (void)deletePath:(id)arg1 parameters:(id)arg2 successQueue:(id)arg3 failureQueue:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)getPath:(id)arg1 parameters:(id)arg2 successQueue:(id)arg3 failureQueue:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)postPath:(id)arg1 parameters:(id)arg2 multipleData:(id)arg3 successQueue:(id)arg4 failureQueue:(id)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (void)postPath:(id)arg1 parameters:(id)arg2 data:(id)arg3 successQueue:(id)arg4 failureQueue:(id)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (void)postPath:(id)arg1 parameters:(id)arg2 successQueue:(id)arg3 failureQueue:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;

@end

