//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCBackgroundFetch : NSObject
{
}

+ (id)filename;
+ (id)dictionaryFromResponse:(id)arg1 key:(id)arg2;
+ (id)dictionaryFromData:(id)arg1 key:(id)arg2;
+ (void)fetchDataWithNotification:(id)arg1;
+ (void)applyResponseData:(id)arg1;
+ (void)processResponseData:(id)arg1;
+ (void)removeResponse;
+ (id)responseWithKey:(id)arg1;
+ (void)saveResponse:(id)arg1;

@end

