//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSDictionary, NSString, UIColor, UIGestureRecognizer, UILongPressGestureRecognizer, UIPanGestureRecognizer, UIPinchGestureRecognizer, UIRotationGestureRecognizer, UITapGestureRecognizer, UIView;

@protocol SCCaption <NSObject>
- (void)viewDidLayoutSubviews:(int)arg1;
- (BOOL)textFrameContainsGesture:(UIGestureRecognizer *)arg1;
- (void)pan:(UIPanGestureRecognizer *)arg1;
- (void)press:(UILongPressGestureRecognizer *)arg1;
- (void)tap:(UITapGestureRecognizer *)arg1;
- (void)setHidden:(BOOL)arg1;
- (void)setText:(NSString *)arg1;
- (void)setUserInteractionEnabled:(BOOL)arg1;
- (void)stopEditingAnimated:(BOOL)arg1;
- (void)startEditingAnimated:(BOOL)arg1;
- (BOOL)isFullscreen;
- (BOOL)isHidden;
- (float)keyboardHeight;
- (float)lastVertical;
- (NSString *)text;
- (BOOL)isEditing;
- (void)tearDownAndRemoveFromSuperview;
- (UIView *)view;
- (id)initWithSuperviewBounds:(struct CGRect)arg1 delegate:(id)arg2 mode:(int)arg3;

@optional
- (NSDictionary *)shareLoggingParameters;
- (NSAttributedString *)attributedText;
- (void)colorChanged:(UIColor *)arg1;
- (void)rotation:(UIRotationGestureRecognizer *)arg1;
- (void)pinch:(UIPinchGestureRecognizer *)arg1;
@end

