//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface SCCameraAction : NSObject
{
    NSString *_type;
    NSArray *_parameters;
}

+ (id)actionWithType:(id)arg1 parameters:(id)arg2;
@property(retain, nonatomic) NSArray *parameters; // @synthesize parameters=_parameters;
@property(nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)parameterAtIndex:(int)arg1;
- (void)executeActionWithCaptureManager:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)actionTypesActionCancels;
- (id)actionTypesActionSupercedes;

@end

