//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAEmitterLayer, NSString;

@interface SCCameraTimer : UIView
{
    float _currentTime;
    NSString *_themeAnimationKey;
    float _maxRecordingLength;
    float _initialCircleWidth;
    float _deltaCircleWidth;
    float _redCircleWidth;
    CAEmitterLayer *_emitterLayer;
    struct CGPoint _circleCenter;
}

+ (Class)layerClass;
@property(retain, nonatomic) CAEmitterLayer *emitterLayer; // @synthesize emitterLayer=_emitterLayer;
@property(nonatomic) struct CGPoint circleCenter; // @synthesize circleCenter=_circleCenter;
@property(nonatomic) float redCircleWidth; // @synthesize redCircleWidth=_redCircleWidth;
@property(nonatomic) float deltaCircleWidth; // @synthesize deltaCircleWidth=_deltaCircleWidth;
@property(nonatomic) float initialCircleWidth; // @synthesize initialCircleWidth=_initialCircleWidth;
@property(nonatomic) float maxRecordingLength; // @synthesize maxRecordingLength=_maxRecordingLength;
@property(retain, nonatomic) NSString *themeAnimationKey; // @synthesize themeAnimationKey=_themeAnimationKey;
@property(nonatomic) float currentTime; // @synthesize currentTime=_currentTime;
- (void).cxx_destruct;
- (void)initializeEmitterCells;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 maxRecordingLength:(float)arg2;

@end

