//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCCaptionConfigDelegate.h"
#import "SCCaptionDelegate.h"
#import "SCColorPickerDelegate.h"

@class NSArray, NSAttributedString, NSString;

@interface SCCaptionManager : NSObject <SCCaptionDelegate, SCCaptionConfigDelegate, SCColorPickerDelegate>
{
    BOOL _tempEditing;
    BOOL _tempHidden;
    id <SCCaptionManagerDelegate> _delegate;
    float _tempLastVertical;
    id <SCCaption> _caption;
    int _currentModeIndex;
    NSArray *_captionModes;
    float _tempKeyboardHeight;
    NSString *_tempText;
    NSAttributedString *_tempAttributedText;
}

+ (id)captionModeForLogging:(int)arg1;
@property(copy, nonatomic) NSAttributedString *tempAttributedText; // @synthesize tempAttributedText=_tempAttributedText;
@property(copy, nonatomic) NSString *tempText; // @synthesize tempText=_tempText;
@property(nonatomic) float tempKeyboardHeight; // @synthesize tempKeyboardHeight=_tempKeyboardHeight;
@property(nonatomic) BOOL tempHidden; // @synthesize tempHidden=_tempHidden;
@property(nonatomic) BOOL tempEditing; // @synthesize tempEditing=_tempEditing;
@property(retain, nonatomic) NSArray *captionModes; // @synthesize captionModes=_captionModes;
@property(nonatomic) int currentModeIndex; // @synthesize currentModeIndex=_currentModeIndex;
@property(retain, nonatomic) id <SCCaption> caption; // @synthesize caption=_caption;
@property(nonatomic) float tempLastVertical; // @synthesize tempLastVertical=_tempLastVertical;
@property(nonatomic) __weak id <SCCaptionManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)shareLoggingParameters;
- (void)colorChanged:(id)arg1;
- (void)updateTempText;
- (void)textChanged;
- (void)startedEditing;
- (void)stoppedEditing;
- (BOOL)canStartEditingCaption;
- (void)viewDidLayoutSubviews:(int)arg1;
- (struct CGRect)frame;
- (id)imageFromView;
- (BOOL)textFrameContainsGesture:(id)arg1;
- (void)rotation:(id)arg1;
- (void)pinch:(id)arg1;
- (void)pan:(id)arg1;
- (void)press:(id)arg1;
- (void)tap:(id)arg1;
- (void)startEditing;
- (void)stopEditing;
- (void)setHidden:(BOOL)arg1;
- (void)setText:(id)arg1;
- (void)setUserInteractionEnabled:(BOOL)arg1;
- (BOOL)captionPresent;
- (float)keyboardHeight;
- (float)lastVertical;
- (id)attributedText;
- (id)text;
- (BOOL)isFullscreen;
- (BOOL)isEditing;
- (BOOL)isHidden;
- (void)cleanUpLastMode;
- (id)newViewForCurrentCaptionModeWithSuperviewBounds:(struct CGRect)arg1;
- (BOOL)isBigTextPlusMode;
- (int)currentMode;
- (void)nextMode;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 captionModes:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

