//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "TTTAttributedLabelDelegate.h"

@class NSString, SCButton, SCHeader;

@interface SCCashTOSViewController : UIViewController <SCHeaderDataSource, SCHeaderDelegate, TTTAttributedLabelDelegate>
{
    id <SCCashTOSDelegate> _delegate;
    SCButton *_agreeButton;
    SCHeader *_header;
}

@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(retain, nonatomic) SCButton *agreeButton; // @synthesize agreeButton=_agreeButton;
@property(nonatomic) __weak id <SCCashTOSDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)shouldPopToRootViewControllerLater;
- (BOOL)shouldPopToRootViewController;
- (void)expandLineHeight:(id)arg1 multiple:(float)arg2 includeURL:(BOOL)arg3;
- (void)agreeButtonPressed;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)leftButtonPressed;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)initAgreeButton;
- (void)initPolicyLabel;
- (void)initSquareGhost;
- (void)initInfoLabel;
- (void)initBackground;
- (void)initHeader;
- (void)loadView;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

