//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCCaption.h"
#import "UITextViewDelegate.h"

@class NSString, UITextView, UIView;

@interface SCCaptionDefaultTextView : NSObject <UITextViewDelegate, SCCaption>
{
    BOOL _editing;
    id <SCCaptionDelegate> _delegate;
    id <SCCaptionConfigDelegate> _configDelegate;
    int _characterLimit;
    UIView *_containerView;
    float _lastVertical;
    int _mode;
    UITextView *_textView;
    float _keyboardHeight;
    struct CGRect _panningBounds;
    struct CGRect _superviewBounds;
}

@property(nonatomic) struct CGRect superviewBounds; // @synthesize superviewBounds=_superviewBounds;
@property(nonatomic) float keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(nonatomic) struct CGRect panningBounds; // @synthesize panningBounds=_panningBounds;
@property(nonatomic) int mode; // @synthesize mode=_mode;
@property(nonatomic) float lastVertical; // @synthesize lastVertical=_lastVertical;
@property(nonatomic, getter=isEditing) BOOL editing; // @synthesize editing=_editing;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) int characterLimit; // @synthesize characterLimit=_characterLimit;
@property(nonatomic) __weak id <SCCaptionConfigDelegate> configDelegate; // @synthesize configDelegate=_configDelegate;
@property(nonatomic) __weak id <SCCaptionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews:(int)arg1;
- (void)trimTextViewTextIfNecessary;
- (void)resizeForViewing;
- (void)resizeForEditing;
- (struct CGRect)textViewFrame;
- (struct CGRect)containerViewFrame;
- (float)adjustedYOffsetForContentBounds:(float)arg1;
- (BOOL)textFrameContainsGesture:(id)arg1;
- (void)pan:(id)arg1;
- (void)tapOrPress:(id)arg1;
- (void)press:(id)arg1;
- (void)tap:(id)arg1;
- (void)didStopEditingAnimated:(BOOL)arg1;
- (void)prepareToStopEditing;
- (void)didStartEditingAnimated:(BOOL)arg1;
- (void)prepareToStartEditing;
- (void)stopEditingAnimated:(BOOL)arg1;
- (void)startEditingAnimated:(BOOL)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (float)superviewHeight;
- (float)superviewWidth;
- (int)contentMargin;
- (int)contentHeight;
- (int)contentWidth;
- (int)maxTextWidth;
- (void)setText:(id)arg1;
- (void)setHidden:(BOOL)arg1;
- (void)setUserInteractionEnabled:(BOOL)arg1;
- (BOOL)isFullscreen;
- (id)text;
- (BOOL)isHidden;
- (void)inputKeyboardWillChangeFrame:(id)arg1;
- (void)removeObservers;
- (void)addObservers;
- (void)configureTextViewBasedOnEditMode;
- (id)view;
- (void)tearDownAndRemoveFromSuperview;
- (void)dealloc;
- (void)initializeViews;
- (id)initWithSuperviewBounds:(struct CGRect)arg1 delegate:(id)arg2 mode:(int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

