//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCTouchControlUIView.h"

@interface SCCaptionTouchControlUIView : SCTouchControlUIView
{
    BOOL _lockVertical;
    BOOL _evaluated;
    float _lockVerticalRatio;
}

@property(nonatomic) BOOL evaluated; // @synthesize evaluated=_evaluated;
@property(nonatomic) float lockVerticalRatio; // @synthesize lockVerticalRatio=_lockVerticalRatio;
@property(nonatomic) BOOL lockVertical; // @synthesize lockVertical=_lockVertical;
- (void)rotation:(id)arg1;
- (void)pinch:(id)arg1;
- (void)pan:(id)arg1;
@property(nonatomic) float lockVerticalAngle;
- (id)initWithFrame:(struct CGRect)arg1;

@end

