//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCCaptureManagerSessionDelegate.h"

@class AVCaptureVideoPreviewLayer, NSString;

@interface SCCaptureVideoPreviewView : UIView <SCCaptureManagerSessionDelegate>
{
    AVCaptureVideoPreviewLayer *_captureVideoPreviewLayer;
    UIView *_overlayView;
}

@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *captureVideoPreviewLayer; // @synthesize captureVideoPreviewLayer=_captureVideoPreviewLayer;
- (void).cxx_destruct;
- (struct CGPoint)convertViewCoordinates:(struct CGPoint)arg1 withCaptureInputPorts:(id)arg2;
- (void)captureManagerWillStopSession;
- (void)captureManagerSessionRunningChanged:(BOOL)arg1;
- (void)setSession:(id)arg1;
- (void)setOverlayViewHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithCaptureManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

