//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVCamCaptureManager, NSDate, NSMutableArray, NSMutableDictionary, NSTimer, SCCameraAction, SCCaptureVideoPreviewView;

@interface SCCamera : NSObject
{
    BOOL _powerSaveModeEnabled;
    BOOL _asyncContinuousFocused;
    AVCamCaptureManager *_captureManager;
    NSMutableArray *_actionsQueue;
    NSMutableDictionary *_cachedQueueCounts;
    SCCaptureVideoPreviewView *_captureVideoPreviewView;
    SCCameraAction *_delayedStopAction;
    NSTimer *_delayedStopActionTimer;
    SCCameraAction *_inProgressAction;
    int _cameraStartSeqNo;
    NSDate *_modeStartTime;
}

+ (id)sharedInstance;
@property(nonatomic) BOOL asyncContinuousFocused; // @synthesize asyncContinuousFocused=_asyncContinuousFocused;
@property(retain, nonatomic) NSDate *modeStartTime; // @synthesize modeStartTime=_modeStartTime;
@property(nonatomic) int cameraStartSeqNo; // @synthesize cameraStartSeqNo=_cameraStartSeqNo;
@property(nonatomic) BOOL powerSaveModeEnabled; // @synthesize powerSaveModeEnabled=_powerSaveModeEnabled;
@property(retain, nonatomic) SCCameraAction *inProgressAction; // @synthesize inProgressAction=_inProgressAction;
@property(retain, nonatomic) NSTimer *delayedStopActionTimer; // @synthesize delayedStopActionTimer=_delayedStopActionTimer;
@property(retain, nonatomic) SCCameraAction *delayedStopAction; // @synthesize delayedStopAction=_delayedStopAction;
@property(retain, nonatomic) SCCaptureVideoPreviewView *captureVideoPreviewView; // @synthesize captureVideoPreviewView=_captureVideoPreviewView;
@property(retain, nonatomic) NSMutableDictionary *cachedQueueCounts; // @synthesize cachedQueueCounts=_cachedQueueCounts;
@property(retain, nonatomic) NSMutableArray *actionsQueue; // @synthesize actionsQueue=_actionsQueue;
@property(retain, nonatomic) AVCamCaptureManager *captureManager; // @synthesize captureManager=_captureManager;
- (void).cxx_destruct;
- (struct CGPoint)convertToPointOfInterestFromViewCoordinates:(struct CGPoint)arg1;
- (BOOL)inProgressActionIsMemberOfClass:(Class)arg1;
- (id)arrayWithFirstParameter:(id)arg1 secondParameter:(id)arg2 thirdParameter:(id)arg3;
- (void)syncCaptureStillImage;
- (void)asyncSwitchToRegularSessionWithCompletion:(CDUnknownBlockType)arg1;
- (void)asyncStartCaptureVideoDataOutputWithSampleBufferDelegate:(id)arg1 queue:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)asyncToggleCameraWithConfiguration:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)asyncToggleCameraWithCompletion:(CDUnknownBlockType)arg1;
- (void)asyncContinuousFocus;
- (void)asyncFocusAtPoint:(struct CGPoint)arg1;
- (void)asyncContinuousExposureAtPoint:(struct CGPoint)arg1;
- (void)asyncCaptureStillImage;
- (void)asyncStopRecording;
- (void)asyncStartRecordingWithCompletion:(CDUnknownBlockType)arg1;
- (void)asyncResetCameraWithCompletion:(CDUnknownBlockType)arg1;
- (void)asyncStopCameraSessionRequired:(BOOL)arg1 withDelay:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)asyncStopCameraSessionRequired:(BOOL)arg1;
- (void)asyncStartCameraSessionForOwner:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setCameraObjectsForOwner:(id)arg1;
- (void)subjectAreaDidChange:(id)arg1;
- (void)featureSettingsUpdated:(id)arg1;
- (void)didLogout:(id)arg1;
- (void)captureSessionRuntimeErrorDidOccur:(id)arg1;
- (void)willResignActive;
- (void)didBecomeActive;
- (void)removeObservers;
- (void)addObservers;
- (void)cancelDelayedStopAction;
- (void)delayedStopActionTimerFired:(id)arg1;
- (void)addDelayedStopAction:(id)arg1;
- (int)numberOfItemsInQueueOfType:(id)arg1;
- (void)executeNextAction;
- (void)addNewActionToQueue:(id)arg1;
- (BOOL)cameraSessionRunning;
- (BOOL)resettingCamera;
- (BOOL)togglingCamera;
- (void)initializeCameraWithPowerSaveModeEnabled:(BOOL)arg1;
- (void)dealloc;
- (id)init;

@end

