//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCCertificateTrust : NSObject
{
    struct __CFArray *_trustedCerts;
}

+ (id)sharedSQAPITrust;
+ (id)sharedSCAPITrust;
@property(nonatomic) struct __CFArray *trustedCerts; // @synthesize trustedCerts=_trustedCerts;
- (CDUnknownBlockType)authChallengeBlock;
- (void)dealloc;
- (id)initWithTrustedCerts:(struct __CFArray *)arg1;

@end

