//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIPanGestureRecognizer, UIView;

@interface SCChatKeyboardControl : NSObject <UIGestureRecognizerDelegate>
{
    BOOL _becomingFirstResponder;
    BOOL _draggingChatScrollView;
    BOOL _hidingKeyboardNotAnimated;
    BOOL _keyboardDraggingEnabled;
    BOOL _keyboardUpWhenEnteringChat;
    BOOL _pullingUpKeyboard;
    BOOL _resigningAfterDrag;
    BOOL _showingKeyboardNotAnimated;
    UIView *_chatView;
    float _chatViewOffset;
    int _chatVisbilityState;
    CDUnknownBlockType _hideKeyboardCompletion;
    CDUnknownBlockType _keyboardDidMoveBlock;
    UIView *_keyboardView;
    UIPanGestureRecognizer *_keyboardPanRecognizer;
    int _keyboardState;
    float _initialKeyboardY;
    float _lastContentOffset;
    UIView *_textInputView;
    struct CGPoint _initialPanningTouchLocation;
    struct CGRect _previousKeyboardRect;
}

@property(nonatomic) __weak UIView *textInputView; // @synthesize textInputView=_textInputView;
@property(nonatomic) BOOL showingKeyboardNotAnimated; // @synthesize showingKeyboardNotAnimated=_showingKeyboardNotAnimated;
@property(nonatomic) BOOL resigningAfterDrag; // @synthesize resigningAfterDrag=_resigningAfterDrag;
@property(nonatomic) BOOL pullingUpKeyboard; // @synthesize pullingUpKeyboard=_pullingUpKeyboard;
@property(nonatomic) struct CGRect previousKeyboardRect; // @synthesize previousKeyboardRect=_previousKeyboardRect;
@property(nonatomic) float lastContentOffset; // @synthesize lastContentOffset=_lastContentOffset;
@property(nonatomic) struct CGPoint initialPanningTouchLocation; // @synthesize initialPanningTouchLocation=_initialPanningTouchLocation;
@property(nonatomic) float initialKeyboardY; // @synthesize initialKeyboardY=_initialKeyboardY;
@property(nonatomic) int keyboardState; // @synthesize keyboardState=_keyboardState;
@property(nonatomic) BOOL keyboardUpWhenEnteringChat; // @synthesize keyboardUpWhenEnteringChat=_keyboardUpWhenEnteringChat;
@property(retain, nonatomic) UIPanGestureRecognizer *keyboardPanRecognizer; // @synthesize keyboardPanRecognizer=_keyboardPanRecognizer;
@property(nonatomic) __weak UIView *keyboardView; // @synthesize keyboardView=_keyboardView;
@property(nonatomic) BOOL keyboardDraggingEnabled; // @synthesize keyboardDraggingEnabled=_keyboardDraggingEnabled;
@property(copy, nonatomic) CDUnknownBlockType keyboardDidMoveBlock; // @synthesize keyboardDidMoveBlock=_keyboardDidMoveBlock;
@property(nonatomic) BOOL hidingKeyboardNotAnimated; // @synthesize hidingKeyboardNotAnimated=_hidingKeyboardNotAnimated;
@property(copy, nonatomic) CDUnknownBlockType hideKeyboardCompletion; // @synthesize hideKeyboardCompletion=_hideKeyboardCompletion;
@property(nonatomic) BOOL draggingChatScrollView; // @synthesize draggingChatScrollView=_draggingChatScrollView;
@property(nonatomic) int chatVisbilityState; // @synthesize chatVisbilityState=_chatVisbilityState;
@property(nonatomic) float chatViewOffset; // @synthesize chatViewOffset=_chatViewOffset;
@property(nonatomic) __weak UIView *chatView; // @synthesize chatView=_chatView;
@property(nonatomic) BOOL becomingFirstResponder; // @synthesize becomingFirstResponder=_becomingFirstResponder;
- (void).cxx_destruct;
- (BOOL)canBeginEditing;
- (void)removeObservers;
- (void)addObservers;
- (void)callKeyboardDidMoveBlock:(struct CGRect)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)panGestureDidChange:(id)arg1;
- (void)updateKeyboardFrameForOffset;
- (void)chatBecameNotVisible;
- (void)chatBecamePartiallyVisible;
- (void)chatBecameFullyVisible;
- (void)chatViewDidFullyDisappear;
- (void)chatViewDidFullyAppear;
- (void)chatVCDidAppearAtOffset:(float)arg1;
- (BOOL)pullingUpEnded;
- (void)chatScrollViewWillBeginDragging:(id)arg1;
- (void)chatScrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)chatScrollViewDidScroll:(id)arg1 withFullScreenItem:(BOOL)arg2;
- (void)setKeyboardPanningActionHandler:(CDUnknownBlockType)arg1;
- (void)animateBasedOnNotification:(id)arg1;
- (void)hideKeyboard:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)hideKeyboard:(BOOL)arg1;
- (void)showKeyboard:(BOOL)arg1;
- (void)setKeyboardAnimationsEnabled:(BOOL)arg1;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)responderDidResignActive:(id)arg1;
- (void)responderDidBecomeActive:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

