//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber, NSString, SCChatTextInputCashTagFormatter;

@interface SCChatTextInputCashTagManager : NSObject
{
    BOOL _swipeToSendMarkerEntered;
    BOOL _shouldDelayAndCoalesceDidChangeInsertionPointContext;
    CDStruct_193cfb47 _delegateFlags;
    id <SCChatTextInputCashTagManagerDelegate> _delegate;
    unsigned int _insertionPointContext;
    NSArray *_validCashTagRanges;
    NSArray *_highlightedCashTagRanges;
    NSString *_lastKnownTextOfTextInputViewForHighlightedCashTagRanges;
    NSArray *_memorizedHighlightedCashTagRanges;
    NSString *_memorizedTextOfTextInputView;
    NSNumber *_insertionPointContextBeforeDelayingAndCoalescing;
    SCChatTextInputCashTagFormatter *_cashTagFormatter;
}

@property(retain, nonatomic) SCChatTextInputCashTagFormatter *cashTagFormatter; // @synthesize cashTagFormatter=_cashTagFormatter;
@property(nonatomic) CDStruct_193cfb47 delegateFlags; // @synthesize delegateFlags=_delegateFlags;
@property(copy, nonatomic) NSNumber *insertionPointContextBeforeDelayingAndCoalescing; // @synthesize insertionPointContextBeforeDelayingAndCoalescing=_insertionPointContextBeforeDelayingAndCoalescing;
@property(copy, nonatomic) NSString *memorizedTextOfTextInputView; // @synthesize memorizedTextOfTextInputView=_memorizedTextOfTextInputView;
@property(copy, nonatomic) NSArray *memorizedHighlightedCashTagRanges; // @synthesize memorizedHighlightedCashTagRanges=_memorizedHighlightedCashTagRanges;
@property(copy, nonatomic) NSString *lastKnownTextOfTextInputViewForHighlightedCashTagRanges; // @synthesize lastKnownTextOfTextInputViewForHighlightedCashTagRanges=_lastKnownTextOfTextInputViewForHighlightedCashTagRanges;
@property(nonatomic) BOOL shouldDelayAndCoalesceDidChangeInsertionPointContext; // @synthesize shouldDelayAndCoalesceDidChangeInsertionPointContext=_shouldDelayAndCoalesceDidChangeInsertionPointContext;
@property(nonatomic) BOOL swipeToSendMarkerEntered; // @synthesize swipeToSendMarkerEntered=_swipeToSendMarkerEntered;
@property(copy, nonatomic) NSArray *highlightedCashTagRanges; // @synthesize highlightedCashTagRanges=_highlightedCashTagRanges;
@property(copy, nonatomic) NSArray *validCashTagRanges; // @synthesize validCashTagRanges=_validCashTagRanges;
@property(nonatomic) unsigned int insertionPointContext; // @synthesize insertionPointContext=_insertionPointContext;
@property(nonatomic) __weak id <SCChatTextInputCashTagManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct _NSRange)changeRangeFromString:(id)arg1 toString:(id)arg2;
- (void)shiftRangesInCashTagRanges:(id)arg1 rightToRange:(struct _NSRange)arg2 byOffset:(int)arg3;
- (void)removeInvalidRangesInCashTagRanges:(id)arg1 withText:(id)arg2;
- (void)removeRangesInCashTagRanges:(id)arg1 intersectedWithRange:(struct _NSRange)arg2;
- (void)insertRange:(struct _NSRange)arg1 intoCashTagRanges:(id)arg2;
- (unsigned int)indexOfRangeInCashTagRanges:(id)arg1 coveringInsertionPoint:(unsigned int)arg2;
- (BOOL)isRange:(struct _NSRange)arg1 intersectedWithRange:(struct _NSRange)arg2;
- (BOOL)isInsertionPoint:(unsigned int)arg1 inCashTagRange:(struct _NSRange)arg2;
- (BOOL)inMultistageTextInput;
- (unsigned int)insertionPoint;
- (void)notifyDelegateDidChangeInsertionPointContext;
- (void)cancelScheduledNotifyDelegateDidChangeInsertionPointContext;
- (void)scheduleNotifyDelegateDidChangeInsertionPointContext:(unsigned int)arg1;
- (void)updateSwipeToSendMarkerEnteredAndNofityDelegate:(BOOL)arg1;
- (void)updateInsertionPointContextAndNotifyDelegate:(BOOL)arg1;
- (void)updateHighlightedCashTagRangesWithCashTagRanges:(id)arg1 notifyDelegate:(BOOL)arg2;
- (void)updateHighlightedCashTagRangesAndNotifyDelegate:(BOOL)arg1;
- (void)updateValidCashTagRangesAndNotifyDelegate:(BOOL)arg1;
- (void)textInputViewDidChangeSelection;
- (void)textInputViewDidChangeText;
- (void)textInputViewWillChangeTextInRange:(struct _NSRange)arg1 replacementText:(id)arg2;
- (unsigned int)totalCashAmountInHighlightedCashTagRanges;
- (void)resetHighlightedCashTagRangesWithCashTagRanges:(id)arg1;
- (void)highlightCashTagAtInsertionPoint;
- (void)resetAllStates;
- (id)init;

@end

