//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCTCPSessionDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, NSTimer, SCTCPSession;

@interface SCChatGateway : NSObject <SCTCPSessionDelegate>
{
    BOOL _active;
    BOOL _sendingChatBatch;
    int _endSessionCount;
    NSTimer *_batchHTTPRequestTimer;
    NSMutableDictionary *_batchedCompletionHandlers;
    NSMutableArray *_batchedMessages;
    NSMutableDictionary *_batchedForTCPMessages;
    NSTimer *_batchedForTCPTimer;
    int _maxBatchedForTCPMessagesPerSecond;
    SCTCPSession *_tcpSession;
    double _tcpDisconnectTime;
    double _timeBecameActive;
}

+ (id)stringFromProtocol:(int)arg1;
+ (id)shared;
@property(nonatomic) BOOL sendingChatBatch; // @synthesize sendingChatBatch=_sendingChatBatch;
@property(nonatomic) double timeBecameActive; // @synthesize timeBecameActive=_timeBecameActive;
@property(nonatomic) double tcpDisconnectTime; // @synthesize tcpDisconnectTime=_tcpDisconnectTime;
@property(retain, nonatomic) SCTCPSession *tcpSession; // @synthesize tcpSession=_tcpSession;
@property(nonatomic) int maxBatchedForTCPMessagesPerSecond; // @synthesize maxBatchedForTCPMessagesPerSecond=_maxBatchedForTCPMessagesPerSecond;
@property(retain, nonatomic) NSTimer *batchedForTCPTimer; // @synthesize batchedForTCPTimer=_batchedForTCPTimer;
@property(retain, nonatomic) NSMutableDictionary *batchedForTCPMessages; // @synthesize batchedForTCPMessages=_batchedForTCPMessages;
@property(retain, nonatomic) NSMutableArray *batchedMessages; // @synthesize batchedMessages=_batchedMessages;
@property(retain, nonatomic) NSMutableDictionary *batchedCompletionHandlers; // @synthesize batchedCompletionHandlers=_batchedCompletionHandlers;
@property(retain, nonatomic) NSTimer *batchHTTPRequestTimer; // @synthesize batchHTTPRequestTimer=_batchHTTPRequestTimer;
@property(nonatomic) int endSessionCount; // @synthesize endSessionCount=_endSessionCount;
@property(nonatomic) BOOL active; // @synthesize active=_active;
- (void).cxx_destruct;
- (void)didDisconnectWithError:(id)arg1;
- (void)didEndSession;
- (void)didStartSession;
- (void)didFailToStartSessionWithError:(id)arg1;
- (void)didReceiveJSONDictionary:(id)arg1;
- (void)updateChatsWithJSONDictionary:(id)arg1;
- (BOOL)recentlyStartedSession;
- (BOOL)shouldUseTcp;
- (void)sendCompletionHandlerMessagesForMessages:(id)arg1 success:(BOOL)arg2 error:(id)arg3 protocol:(int)arg4;
- (void)handleConversationResponse:(id)arg1;
- (void)handleConversationsResponse:(id)arg1;
- (BOOL)shouldBeBatchedForTCP:(id)arg1;
- (void)batchedForTCPTimerFired;
- (void)sendPreviouslySentHTTPMessagesThroughTCP;
- (BOOL)batchedMessagesContainsChat:(id)arg1;
- (void)removeSupersededBatchedMessagesForMessage:(id)arg1;
- (void)batchTimerFired;
- (void)fetchAuthenticationInfoForChatId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)fetchChatWithChatId:(id)arg1 iterOffest:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)fetchChatWithChatId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)addMessageToBatch:(id)arg1 forChat:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)makeChatRequestWithDictionary:(id)arg1 forChat:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)userDidLogout;
- (BOOL)tcpConnected;
- (void)didEnterBackground;
- (void)willEnterForeground;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

