//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCChunkItem.h"

@class NSMutableSet, NSString;

@interface SCChunkLocalWebpageItem : SCChunkItem
{
    NSString *_htmlString;
    NSMutableSet *_assetFilenames;
}

@property(retain, nonatomic) NSMutableSet *assetFilenames; // @synthesize assetFilenames=_assetFilenames;
@property(copy, nonatomic) NSString *htmlString; // @synthesize htmlString=_htmlString;
- (void).cxx_destruct;
- (id)mediaFileNames;
- (BOOL)mediaExistsInCache;
- (id)cacheMediaIds;
- (void)saveDataWithName:(id)arg1 chunkDictionary:(id)arg2;
- (BOOL)isValidResourceURL:(id)arg1;
- (id)localAssetsURL;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1 chunkDictionary:(id)arg2;

@end

