//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString;

@interface SCColorPicker : UIImageView <UIGestureRecognizerDelegate>
{
    id <SCColorPickerDelegate> _delegate;
    float _savedHue;
}

@property(nonatomic) float savedHue; // @synthesize savedHue=_savedHue;
@property(nonatomic) __weak id <SCColorPickerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)determineColor:(struct CGPoint)arg1 withTotalHeight:(float)arg2 withAbsoluteLocation:(float)arg3;
- (id)determineColor:(struct CGPoint)arg1 withTotalHeight:(float)arg2;
- (void)colorPress:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

