//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class CADisplayLink;

@interface SCCounterLabel : UILabel
{
    CADisplayLink *_borderDisplayLink;
    int _counterShape;
    float _snapTime;
    float _snapTimeLeft;
    double _lastDrawTime;
}

@property(nonatomic) float snapTimeLeft; // @synthesize snapTimeLeft=_snapTimeLeft;
@property(nonatomic) float snapTime; // @synthesize snapTime=_snapTime;
@property(nonatomic) double lastDrawTime; // @synthesize lastDrawTime=_lastDrawTime;
@property(nonatomic) int counterShape; // @synthesize counterShape=_counterShape;
@property(retain, nonatomic) CADisplayLink *borderDisplayLink; // @synthesize borderDisplayLink=_borderDisplayLink;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)borderDisplayLinkFired:(id)arg1;
- (void)stopBorderDisplayLink;
- (void)startBorderDisplayLink;
- (void)setBorderWithSnapTime:(float)arg1 snapTimeLeft:(float)arg2 counterShape:(int)arg3;
- (void)setFrameWithTimeLeft:(float)arg1 containerWidth:(float)arg2 yOffset:(float)arg3 counterShape:(int)arg4;
- (void)dealloc;
- (id)init;

@end

