//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCDeviceName : NSObject
{
}

+ (id)deviceVersionStringForDeviceName:(id)arg1;
+ (BOOL)isDeviceNewerThanDeviceWithSameType:(id)arg1;
+ (BOOL)currentDeviceMeetsMinimumDeviceRequirement:(id)arg1;
+ (BOOL)isIpad:(id)arg1;
+ (BOOL)isIphone:(id)arg1;
+ (BOOL)isIpod:(id)arg1;
+ (BOOL)isIpad;
+ (BOOL)isIphone;
+ (BOOL)isIpod;
+ (id)platformString;
+ (int)maxTCPMessagesPerSecondForDevice;

@end

