//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MediaDataSource.h"
#import "MediaDelegate.h"
#import "NSCoding.h"
#import "SCAdOwnerProtocol.h"
#import "SCMediaOwnerProtocol.h"

@class Media, NSDate, NSString, NSURL, SCDiscoverEdition, UIColor;

@interface SCDiscoverChannel : NSObject <MediaDataSource, MediaDelegate, NSCoding, SCAdOwnerProtocol, SCMediaOwnerProtocol>
{
    BOOL _userManuallyTriggeredIntroMediaLoading;
    NSString *_name;
    UIColor *_primaryPublisherColor;
    UIColor *_secondaryPublisherColor;
    unsigned int _position;
    Media *_filledIconMedia;
    unsigned int _filledIconMediaState;
    NSURL *_filledIconURL;
    Media *_invertedIconMedia;
    unsigned int _invertedIconMediaState;
    NSURL *_invertedIconURL;
    Media *_loadingIconMedia;
    unsigned int _loadingIconMediaState;
    NSURL *_loadingIconURL;
    unsigned int _introMovieMediaState;
    NSString *_introMovieEndpoint;
    SCDiscoverEdition *_currentEdition;
    NSDate *_lastViewedDate;
    NSString *_introMovieFileName;
    SCDiscoverEdition *_displayedOutdatedEdition;
}

+ (void)recoverMissingIconForChannel:(id)arg1;
+ (void)iconForChannel:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (float)borderWidthForChannel:(id)arg1;
+ (id)borderColorForChannel:(id)arg1;
+ (id)backgroundColorForChannel:(id)arg1;
@property(nonatomic) BOOL userManuallyTriggeredIntroMediaLoading; // @synthesize userManuallyTriggeredIntroMediaLoading=_userManuallyTriggeredIntroMediaLoading;
@property(retain, nonatomic) SCDiscoverEdition *displayedOutdatedEdition; // @synthesize displayedOutdatedEdition=_displayedOutdatedEdition;
@property(copy, nonatomic) NSString *introMovieFileName; // @synthesize introMovieFileName=_introMovieFileName;
@property(retain, nonatomic) NSDate *lastViewedDate; // @synthesize lastViewedDate=_lastViewedDate;
@property(retain, nonatomic) SCDiscoverEdition *currentEdition; // @synthesize currentEdition=_currentEdition;
@property(copy, nonatomic) NSString *introMovieEndpoint; // @synthesize introMovieEndpoint=_introMovieEndpoint;
@property(nonatomic) unsigned int introMovieMediaState; // @synthesize introMovieMediaState=_introMovieMediaState;
@property(retain, nonatomic) NSURL *loadingIconURL; // @synthesize loadingIconURL=_loadingIconURL;
@property(nonatomic) unsigned int loadingIconMediaState; // @synthesize loadingIconMediaState=_loadingIconMediaState;
@property(retain, nonatomic) Media *loadingIconMedia; // @synthesize loadingIconMedia=_loadingIconMedia;
@property(retain, nonatomic) NSURL *invertedIconURL; // @synthesize invertedIconURL=_invertedIconURL;
@property(nonatomic) unsigned int invertedIconMediaState; // @synthesize invertedIconMediaState=_invertedIconMediaState;
@property(retain, nonatomic) Media *invertedIconMedia; // @synthesize invertedIconMedia=_invertedIconMedia;
@property(retain, nonatomic) NSURL *filledIconURL; // @synthesize filledIconURL=_filledIconURL;
@property(nonatomic) unsigned int filledIconMediaState; // @synthesize filledIconMediaState=_filledIconMediaState;
@property(retain, nonatomic) Media *filledIconMedia; // @synthesize filledIconMedia=_filledIconMedia;
@property(nonatomic) unsigned int position; // @synthesize position=_position;
@property(retain, nonatomic) UIColor *secondaryPublisherColor; // @synthesize secondaryPublisherColor=_secondaryPublisherColor;
@property(retain, nonatomic) UIColor *primaryPublisherColor; // @synthesize primaryPublisherColor=_primaryPublisherColor;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)mediaFileNames;
- (BOOL)mediaExistsInCache;
- (id)cacheMediaIds;
- (id)cacheAdIds;
- (BOOL)encrypt;
- (BOOL)persist;
- (id)encryptionDictionaryForMedia:(id)arg1;
- (id)decryptData:(id)arg1 forMedia:(id)arg2;
- (id)mediaIdForMedia:(id)arg1;
- (id)introMovieLocalURL;
- (BOOL)mediaIsLoaded;
- (BOOL)mediaIsLoading;
- (BOOL)isHomepageIconMediaLoaded;
- (void)handleFetchedIntroMovieWithSuccess:(BOOL)arg1;
- (void)fetchIntroMovieIfNecessaryUserInitiated:(BOOL)arg1 errorHandler:(CDUnknownBlockType)arg2;
- (void)fetchIntroMovieIfNecessaryUserInitiated:(BOOL)arg1;
- (void)fetchMediaIfNecessaryForIconType:(unsigned int)arg1 userInitiated:(BOOL)arg2;
- (void)fetchIconMediaIfNecessaryUserInitiated:(BOOL)arg1;
- (void)setIconMediaState:(unsigned int)arg1 iconType:(unsigned int)arg2;
- (BOOL)hasViewedChannelInLastHours:(unsigned int)arg1;
- (void)didFinishViewing;
- (void)prepareToStartViewing;
- (BOOL)updateWithJSONDictionary:(id)arg1;
- (void)ensureNonNilMediaObjects;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

