//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "SCAdOwnerProtocol.h"
#import "SCMediaOwnerProtocol.h"

@class NSArray, NSDate, NSString;

@interface SCDiscoverChannels : NSObject <NSCoding, SCAdOwnerProtocol, SCMediaOwnerProtocol>
{
    BOOL _hasNewContent;
    NSArray *_channels;
    NSDate *_lastViewedChannelIcons;
}

@property(retain, nonatomic) NSDate *lastViewedChannelIcons; // @synthesize lastViewedChannelIcons=_lastViewedChannelIcons;
@property(nonatomic) BOOL hasNewContent; // @synthesize hasNewContent=_hasNewContent;
@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
- (void).cxx_destruct;
- (BOOL)hasViewedChannelIconsInLastHours:(unsigned int)arg1;
- (void)viewedChannelIcons;
- (void)fetchMediaIfNecessary;
- (id)mediaFileNames;
- (BOOL)mediaExistsInCache;
- (id)cacheMediaIds;
- (id)cacheAdIds;
- (void)updateWithJSONDictionary:(id)arg1;
- (void)ensureNonNilObjects;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

