//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

@class NSArray, SCDiscoverChannelCell;

@interface SCDiscoverChannelsCollectionViewController : UICollectionViewController
{
    SCDiscoverChannelCell *_currentSelectedCell;
    id <SCDiscoverChannelsCollectionViewControllerDelegate> _delegate;
    NSArray *_channels;
}

@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
@property(nonatomic) __weak id <SCDiscoverChannelsCollectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SCDiscoverChannelCell *currentSelectedCell; // @synthesize currentSelectedCell=_currentSelectedCell;
- (void).cxx_destruct;
- (float)channelCellWidthForCollectionView;
- (void)showAlertForIntroMovieError:(id)arg1 channel:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forChannel:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (void)viewDidLoad;
- (id)initWithCollectionViewLayout:(id)arg1 discoverChannels:(id)arg2;

@end

