//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCDiscoverChannel, SCDiscoverChunk, SCDiscoverEdition;

@interface SCDiscoverUserState : NSObject
{
    SCDiscoverChannel *_currentChannel;
    SCDiscoverEdition *_currentEdition;
    SCDiscoverChunk *_currentChunk;
}

+ (id)stateWithChannel:(id)arg1 edition:(id)arg2 chunk:(id)arg3;
+ (id)stateWithChannel:(id)arg1;
@property(nonatomic) __weak SCDiscoverChunk *currentChunk; // @synthesize currentChunk=_currentChunk;
@property(nonatomic) __weak SCDiscoverEdition *currentEdition; // @synthesize currentEdition=_currentEdition;
@property(nonatomic) __weak SCDiscoverChannel *currentChannel; // @synthesize currentChannel=_currentChannel;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithChannel:(id)arg1 edition:(id)arg2 chunk:(id)arg3;

@end

