//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCInlineChatContentMessage.h"

#import "MediaUploadDelegate.h"

@class NSArray, NSMutableArray, NSString;

@interface SCDiscoverSharedMessage : SCInlineChatContentMessage <MediaUploadDelegate>
{
    NSString *_clientId;
    NSArray *_recipients;
    NSMutableArray *_recipientsNeedingRetry;
}

@property(retain, nonatomic) NSMutableArray *recipientsNeedingRetry; // @synthesize recipientsNeedingRetry=_recipientsNeedingRetry;
@property(retain, nonatomic) NSArray *recipients; // @synthesize recipients=_recipients;
@property(copy, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
- (void).cxx_destruct;
- (id)cacheId;
- (void)imageProcessingDidSucceedForMedia:(id)arg1;
- (void)mediaUploadDidFailForMedia:(id)arg1;
- (void)mediaUploadDidSucceedForMedia:(id)arg1;
- (int)uploadMediaTypeForMedia:(id)arg1;
- (id)uploadMediaIdForMedia:(id)arg1;
- (CDUnknownBlockType)sendFailureBlock;
- (CDUnknownBlockType)sendSuccessBlock;
- (id)pendingOrFailedRecipientUsernames;
- (id)recipientUsernames;
- (id)stringForUsernames:(id)arg1;
- (id)pendingOrFailedRecipientString;
- (id)recipientString;
- (id)seqNumbers;
- (id)sendRequestParameters;
- (void)send;
- (void)upload;
- (void)fillConversationId;
- (id)initWithClientId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

