//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class NSDictionary;

@interface SCDiscoverCollectionViewLayout : UICollectionViewLayout
{
    NSDictionary *_layoutInformation;
    unsigned int _numberOfRows;
    float _itemMargin;
    struct CGSize _itemSize;
    struct UIEdgeInsets _insets;
}

+ (float)topInsetForNumberOfRows:(unsigned int)arg1;
+ (id)rowDescriptionArrayForItems:(unsigned int)arg1;
+ (float)scaledDimension:(float)arg1 forWidth:(float)arg2;
@property(nonatomic) float itemMargin; // @synthesize itemMargin=_itemMargin;
@property(nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
@property(nonatomic) unsigned int numberOfRows; // @synthesize numberOfRows=_numberOfRows;
@property(retain, nonatomic) NSDictionary *layoutInformation; // @synthesize layoutInformation=_layoutInformation;
- (void).cxx_destruct;
- (void)updateDimensionConstantsForNumberOfRows:(unsigned int)arg1;
- (float)heightForNumberOfRows:(int)arg1 withInsets:(BOOL)arg2;
- (float)widthForNumberOfColumns:(int)arg1 withInsets:(BOOL)arg2;
- (struct CGRect)frameForRow:(unsigned int)arg1 column:(unsigned int)arg2 numberOfColumns:(unsigned int)arg3;
- (float)yOriginForRow:(unsigned int)arg1;
- (float)xOriginForColumn:(unsigned int)arg1 numberOfColumns:(unsigned int)arg2;
- (struct CGSize)collectionViewContentSize;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayout;

@end

