//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BCOVPlaybackControllerDelegate.h"
#import "SCDiscoverLongformVideoControlsDelegate.h"
#import "SCDiscoverLongformVideoStateDelegate.h"

@class AVPlayerItem, AVPlayerLayer, FBKVOController, NSArray, NSObject<BCOVPlaybackController>, NSString, NSTimer, SCChunkRemoteVideoItem, SCDiscoverLongformVideoControlsViewController, SCDiscoverLongformVideoState, UIColor;

@interface SCDiscoverLongformVideoViewController : UIViewController <BCOVPlaybackControllerDelegate, SCDiscoverLongformVideoControlsDelegate, SCDiscoverLongformVideoStateDelegate>
{
    BOOL _shouldAutoPlayWhenReady;
    AVPlayerLayer *_playerLayer;
    SCChunkRemoteVideoItem *_remoteVideoItem;
    NSObject<BCOVPlaybackController> *_bcovController;
    NSArray *_bcovVideos;
    NSTimer *_controlsFadeTimer;
    SCDiscoverLongformVideoControlsViewController *_controlsViewController;
    NSString *_editionID;
    UIColor *_primaryColor;
    NSString *_publisherName;
    UIColor *_secondaryColor;
    NSString *_sectionID;
    SCDiscoverLongformVideoState *_state;
    FBKVOController *_observeController;
    AVPlayerItem *_playerItem;
}

@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) FBKVOController *observeController; // @synthesize observeController=_observeController;
@property(nonatomic) BOOL shouldAutoPlayWhenReady; // @synthesize shouldAutoPlayWhenReady=_shouldAutoPlayWhenReady;
@property(retain, nonatomic) SCDiscoverLongformVideoState *state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *sectionID; // @synthesize sectionID=_sectionID;
@property(retain, nonatomic) UIColor *secondaryColor; // @synthesize secondaryColor=_secondaryColor;
@property(copy, nonatomic) NSString *publisherName; // @synthesize publisherName=_publisherName;
@property(retain, nonatomic) UIColor *primaryColor; // @synthesize primaryColor=_primaryColor;
@property(copy, nonatomic) NSString *editionID; // @synthesize editionID=_editionID;
@property(retain, nonatomic) SCDiscoverLongformVideoControlsViewController *controlsViewController; // @synthesize controlsViewController=_controlsViewController;
@property(retain, nonatomic) NSTimer *controlsFadeTimer; // @synthesize controlsFadeTimer=_controlsFadeTimer;
@property(retain, nonatomic) NSArray *bcovVideos; // @synthesize bcovVideos=_bcovVideos;
@property(retain, nonatomic) NSObject<BCOVPlaybackController> *bcovController; // @synthesize bcovController=_bcovController;
@property(retain, nonatomic) SCChunkRemoteVideoItem *remoteVideoItem; // @synthesize remoteVideoItem=_remoteVideoItem;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
- (void).cxx_destruct;
- (long long)numberOfBytesTransferredToBCOVPlaybackController;
- (void)logDidFinishBufferingVideoWithSuccess:(BOOL)arg1 abandoned:(BOOL)arg2;
- (void)logDidStartBufferingVideo;
- (void)logDidFinishWaitingToPlayWithSuccess:(BOOL)arg1 abandoned:(BOOL)arg2;
- (void)logDidStartWaitingToPlay;
- (void)longformVideoControlsDidPressPause;
- (void)longformVideoControlsDidPressPlay;
- (void)longformVideoControlsDidPressFullscreen:(BOOL)arg1;
- (void)longformVideoControlsDidToggleVolume:(BOOL)arg1;
- (void)playerItemLikelyToKeepUp:(id)arg1;
- (void)playerItemBufferBecameEmpty:(id)arg1;
- (void)playbackController:(id)arg1 didAdvanceToPlaybackSession:(id)arg2;
- (void)playbackController:(id)arg1 playbackSession:(id)arg2 didReceiveLifecycleEvent:(id)arg3;
- (void)terminateVideo;
- (void)startBufferingVideo;
- (void)state:(id)arg1 didChangeTag:(int)arg2;
- (void)setBcovVideosFromVideoURLs:(id)arg1;
- (void)fetchVideoPlaylist;
- (void)configureVideoPlaylist;
- (void)invalidateControlsFadeTimerAndShowControls;
- (void)setupControlsFadeTimer;
- (void)fadeOutControls;
- (void)fadeInControls;
- (void)didTap;
- (void)setFullscreen:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)setupTapGesture;
- (void)setupControlsView;
- (void)loadView;
- (void)playerDidFullyDisappear;
- (void)playerDidFullyAppear;
- (void)fullstackDidFullyDisappear;
- (void)fullstackDidFullyAppear;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithRemoteVideoItem:(id)arg1 channelProperties:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

