//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCDiscoverChunkLoadingStrategy.h"

@class NSString;

@interface SCDiscoverWwanChunkLoadingStrategy : NSObject <SCDiscoverChunkLoadingStrategy>
{
}

+ (BOOL)recentChannelRuleApplies:(id)arg1 chunk:(id)arg2;
+ (BOOL)currentEditionRuleApplies:(id)arg1 chunk:(id)arg2;
+ (BOOL)setupDownloadRequestWithUserState:(id)arg1 chunk:(id)arg2 downloadRequest:(id)arg3 lastViewedDiscoverTime:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

