//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "SCAdOwnerProtocol.h"
#import "SCDiscoverEditionMediaLoaderDataSource.h"
#import "SCDiscoverEditionMediaLoaderDelegate.h"
#import "SCDiscoverEditionUserStateBuilderDataSource.h"
#import "SCMediaOwnerProtocol.h"

@class NSArray, NSMutableDictionary, NSString, SCChunkSection, SCDiscoverChannel, SCDiscoverEditionMediaLoader, SCDiscoverEditionUserStateBuilder;

@interface SCDiscoverEdition : NSObject <NSCoding, SCDiscoverEditionMediaLoaderDataSource, SCDiscoverEditionMediaLoaderDelegate, SCDiscoverEditionUserStateBuilderDataSource, SCAdOwnerProtocol, SCMediaOwnerProtocol>
{
    BOOL _hasBeenFullyViewed;
    BOOL _isBeingDisplayed;
    SCDiscoverChannel *_channel;
    NSString *__id;
    SCChunkSection *_lastViewedSection;
    SCDiscoverEditionMediaLoader *_mediaLoader;
    SCDiscoverEditionUserStateBuilder *_userStateBuilder;
    NSArray *_chunks;
    NSArray *_chunksToDisplay;
    NSMutableDictionary *_sectionIDToChunkIndexMap;
    NSMutableDictionary *_sectionIDToChunkToDisplayIndexMap;
}

@property(retain, nonatomic) NSMutableDictionary *sectionIDToChunkToDisplayIndexMap; // @synthesize sectionIDToChunkToDisplayIndexMap=_sectionIDToChunkToDisplayIndexMap;
@property(retain, nonatomic) NSMutableDictionary *sectionIDToChunkIndexMap; // @synthesize sectionIDToChunkIndexMap=_sectionIDToChunkIndexMap;
@property(retain, nonatomic) NSArray *chunksToDisplay; // @synthesize chunksToDisplay=_chunksToDisplay;
@property(retain, nonatomic) NSArray *chunks; // @synthesize chunks=_chunks;
@property(retain, nonatomic) SCDiscoverEditionUserStateBuilder *userStateBuilder; // @synthesize userStateBuilder=_userStateBuilder;
@property(retain, nonatomic) SCDiscoverEditionMediaLoader *mediaLoader; // @synthesize mediaLoader=_mediaLoader;
@property(retain, nonatomic) SCChunkSection *lastViewedSection; // @synthesize lastViewedSection=_lastViewedSection;
@property(nonatomic) BOOL isBeingDisplayed; // @synthesize isBeingDisplayed=_isBeingDisplayed;
@property(copy, nonatomic) NSString *_id; // @synthesize _id=__id;
@property(nonatomic) BOOL hasBeenFullyViewed; // @synthesize hasBeenFullyViewed=_hasBeenFullyViewed;
@property(nonatomic) __weak SCDiscoverChannel *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;
- (void)logSections;
- (id)chunkAtSection:(id)arg1 forEditionUserStateBuilder:(id)arg2;
- (id)editionForEditionUserStateBuilder:(id)arg1;
- (void)editionMediaLoader:(id)arg1 didSkipLoadingChunk:(id)arg2;
- (void)editionMediaLoader:(id)arg1 didFinishLoadingChunk:(id)arg2 success:(BOOL)arg3 error:(id)arg4;
- (void)editionMediaLoader:(id)arg1 didStartLoadingChunk:(id)arg2;
- (id)chunksForEditionMediaLoader:(id)arg1;
- (id)mediaFileNames;
- (BOOL)mediaExistsInCache;
- (id)cacheMediaIds;
- (void)updateChunksToDisplayIndexes;
- (BOOL)displayedChunksFullyLoadedAndViewed;
- (id)nextAdChunkForChunk:(id)arg1;
- (id)chunkForSection:(id)arg1;
- (BOOL)shouldBeViewedFromBeginning;
- (void)didFailToFindMediaInSection:(id)arg1;
- (void)validateSectionMedia:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (void)sectionsAtChunkIndex:(unsigned int)arg1 successBlock:(CDUnknownBlockType)arg2 loadingBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (void)sectionWithDirection:(int)arg1 fromSection:(id)arg2 successBlock:(CDUnknownBlockType)arg3 loadingBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (void)firstSectionWithSuccessBlock:(CDUnknownBlockType)arg1 loadingBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (void)didFinishViewing;
- (void)prepareToStartViewing;
- (void)clearAllAdChunkTransforms;
- (void)processAdPlaceholders;
- (id)adPlaceholderFromChunk:(id)arg1 channel:(id)arg2 adSlot:(unsigned int)arg3 size:(unsigned int)arg4;
- (id)cacheAdIds;
- (BOOL)hasContent;
- (void)rebuildSectionIdToChunkToDisplayIndexMap;
- (void)rebuildSectionIdToChunkIndexMap;
- (void)ensureNonNilObjects;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)updateWithChunkDicts:(id)arg1;
- (id)initWithEditionId:(id)arg1 chunkDicts:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

