//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SCDownloadRequest : NSObject
{
    BOOL _authenticated;
    NSString *_key;
    int _priority;
    int _connectivity;
    int _method;
    double _requestTimestamp;
}

+ (id)createRequestWithURL:(id)arg1 key:(id)arg2 priority:(int)arg3 connectivity:(int)arg4 method:(int)arg5 authenticated:(BOOL)arg6;
+ (id)createRequestWithEndpoint:(id)arg1 parameters:(id)arg2 key:(id)arg3 priority:(int)arg4 connectivity:(int)arg5 method:(int)arg6 authenticated:(BOOL)arg7;
+ (id)createRequestWithURL:(id)arg1 key:(id)arg2 priority:(int)arg3 connectivity:(int)arg4;
+ (id)createRequestWithEndpoint:(id)arg1 parameters:(id)arg2 key:(id)arg3 priority:(int)arg4 connectivity:(int)arg5;
+ (id)createImmediateRequestWithURL:(id)arg1 key:(id)arg2;
+ (id)createImmediateRequestWithEndpoint:(id)arg1 parameters:(id)arg2 key:(id)arg3;
+ (id)createImmediateRequestWithEndpoint:(id)arg1 parameters:(id)arg2 key:(id)arg3 authenticated:(BOOL)arg4;
@property(nonatomic) double requestTimestamp; // @synthesize requestTimestamp=_requestTimestamp;
@property(nonatomic) BOOL authenticated; // @synthesize authenticated=_authenticated;
@property(nonatomic) int method; // @synthesize method=_method;
@property(nonatomic) int connectivity; // @synthesize connectivity=_connectivity;
@property(nonatomic) int priority; // @synthesize priority=_priority;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (BOOL)isBackgroundRequest;
- (void)executeWithSuccessQueue:(id)arg1 failureQueue:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (id)initWithKey:(id)arg1 priority:(int)arg2 connectivity:(int)arg3 method:(int)arg4 authenticated:(BOOL)arg5 requestTimestamp:(double)arg6;

@end

