//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary;

@interface SCDownloadTaskPool : NSObject
{
    NSMutableDictionary *_tasks;
    NSMutableDictionary *_queues;
    NSArray *_priorities;
}

@property(retain, nonatomic) NSArray *priorities; // @synthesize priorities=_priorities;
@property(retain, nonatomic) NSMutableDictionary *queues; // @synthesize queues=_queues;
@property(retain, nonatomic) NSMutableDictionary *tasks; // @synthesize tasks=_tasks;
- (void).cxx_destruct;
- (void)refreshPriorities;
- (id)queueForPriority:(id)arg1;
- (id)poll;
- (id)taskForKey:(id)arg1;
- (id)removeTaskForKey:(id)arg1;
- (void)addTask:(id)arg1;
- (id)init;

@end

