//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCDownloadRequest.h"

@class NSDictionary, NSString;

@interface SCEndpointDownloadRequest : SCDownloadRequest
{
    NSString *_endpoint;
    NSDictionary *_parameters;
}

@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) NSString *endpoint; // @synthesize endpoint=_endpoint;
- (void).cxx_destruct;
- (void)executeWithSuccessQueue:(id)arg1 failureQueue:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (id)initWithEndpoint:(id)arg1 parameters:(id)arg2 key:(id)arg3 priority:(int)arg4 connectivity:(int)arg5 method:(int)arg6 authenticated:(BOOL)arg7 requestTimestamp:(double)arg8;

@end

