//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@interface SCFeatureSettings : NSObject <NSCoding>
{
    BOOL _smartFiltersEnabled;
    BOOL _visualFiltersEnabled;
    BOOL _frontFacingFlashEnabled;
    BOOL _powerSaveModeEnabled;
    BOOL _replaySnapsEnabled;
    BOOL _scrambleBestFriendsEnabled;
    BOOL _pendingUpdateToServer;
}

@property(nonatomic) BOOL pendingUpdateToServer; // @synthesize pendingUpdateToServer=_pendingUpdateToServer;
@property(nonatomic) BOOL scrambleBestFriendsEnabled; // @synthesize scrambleBestFriendsEnabled=_scrambleBestFriendsEnabled;
@property(nonatomic) BOOL replaySnapsEnabled; // @synthesize replaySnapsEnabled=_replaySnapsEnabled;
@property(nonatomic) BOOL powerSaveModeEnabled; // @synthesize powerSaveModeEnabled=_powerSaveModeEnabled;
@property(nonatomic) BOOL frontFacingFlashEnabled; // @synthesize frontFacingFlashEnabled=_frontFacingFlashEnabled;
@property(nonatomic) BOOL visualFiltersEnabled; // @synthesize visualFiltersEnabled=_visualFiltersEnabled;
@property(nonatomic) BOOL smartFiltersEnabled; // @synthesize smartFiltersEnabled=_smartFiltersEnabled;
- (BOOL)isEqual:(id)arg1;
- (id)json;
- (id)duplicate;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJsonDictionary:(id)arg1;
- (id)init;

@end

