//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface SCFilterView : UIView
{
    BOOL _invalid;
    BOOL _displayed;
}

+ (int)type;
@property(nonatomic, getter=isDisplayed) BOOL displayed; // @synthesize displayed=_displayed;
@property(nonatomic, getter=isInvalid) BOOL invalid; // @synthesize invalid=_invalid;
- (void)setOrientation:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1 config:(id)arg2;

@end

