//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSSet;

@interface SCFriendSearcher : NSObject
{
    id <SCFriendSearcherDelegate> _delegate;
    NSSet *_friendNamesToIgnore;
    NSMutableArray *_fetchedResultsCache;
    NSArray *_resultsToDisplay;
}

@property(retain, nonatomic) NSArray *resultsToDisplay; // @synthesize resultsToDisplay=_resultsToDisplay;
@property(retain, nonatomic) NSMutableArray *fetchedResultsCache; // @synthesize fetchedResultsCache=_fetchedResultsCache;
@property(retain, nonatomic) NSSet *friendNamesToIgnore; // @synthesize friendNamesToIgnore=_friendNamesToIgnore;
@property(nonatomic) __weak id <SCFriendSearcherDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (unsigned int)resultsCount;
- (unsigned int)indexOfFriend:(id)arg1;
- (id)friendAtIndex:(unsigned int)arg1;
- (id)friendsFromSearchResults:(id)arg1;
- (void)updateCacheWithNewResults:(id)arg1;
- (void)clearCache;
- (void)fetchFriendsWithQuery:(id)arg1;
- (id)init;

@end

