//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSString;

@interface SCGeofencedObject : NSObject <NSCoding>
{
    NSArray *_geoFenceLocationPoints;
    NSString *_locationId;
}

@property(retain, nonatomic) NSString *locationId; // @synthesize locationId=_locationId;
@property(retain, nonatomic) NSArray *geoFenceLocationPoints; // @synthesize geoFenceLocationPoints=_geoFenceLocationPoints;
- (void).cxx_destruct;
- (BOOL)geoFenceContainsLocation:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)initGeoFenceWithDictionary:(id)arg1;

@end

