//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCGeofencedObject.h"

@class NSDate, NSString, UIImage;

@interface SCGeoFilter : SCGeofencedObject
{
    NSDate *_expirationDate;
    NSString *_filterId;
    UIImage *_image;
    int _scaleSetting;
    unsigned int _positionSetting;
    unsigned int _index;
}

@property(nonatomic) unsigned int index; // @synthesize index=_index;
@property(nonatomic) unsigned int positionSetting; // @synthesize positionSetting=_positionSetting;
@property(nonatomic) int scaleSetting; // @synthesize scaleSetting=_scaleSetting;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *filterId; // @synthesize filterId=_filterId;
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
- (void).cxx_destruct;
- (BOOL)hasInvalidValues;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)updateWithDictionary:(id)arg1 index:(unsigned int)arg2;
- (void)initScaleAndPosition:(id)arg1;
- (void)configureMetaDataWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1 index:(unsigned int)arg2;

@end

