//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIImage, UIImageView, UILongPressGestureRecognizer;

@interface SCGrowingButton : UIView <UIGestureRecognizerDelegate>
{
    BOOL _recognizesGesturesSimultaneously;
    BOOL _enabled;
    BOOL _pressed;
    UIImage *_image;
    float _maximumScale;
    float _minimumScale;
    UIView *_extraAnimationView;
    SEL _action;
    UIImageView *_imageView;
    UILongPressGestureRecognizer *_longPressGesture;
    id _target;
    struct CGSize _imageInset;
}

@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) BOOL pressed; // @synthesize pressed=_pressed;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGesture; // @synthesize longPressGesture=_longPressGesture;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) UIView *extraAnimationView; // @synthesize extraAnimationView=_extraAnimationView;
@property(nonatomic) BOOL recognizesGesturesSimultaneously; // @synthesize recognizesGesturesSimultaneously=_recognizesGesturesSimultaneously;
@property(nonatomic) float minimumScale; // @synthesize minimumScale=_minimumScale;
@property(nonatomic) float maximumScale; // @synthesize maximumScale=_maximumScale;
@property(nonatomic) struct CGSize imageInset; // @synthesize imageInset=_imageInset;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)cancelExistingTransformAnimationsIfNeeded;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)addTarget:(id)arg1 action:(SEL)arg2;
- (void)animate;
- (void)shrink;
- (void)grow;
- (void)press:(id)arg1;
- (void)layoutSubviews;
- (struct CGPoint)imageCenter;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

