//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface SCHeadset : UIButton
{
    double _headsetRemovalTime;
}

+ (BOOL)isHeadsetPluggedIn;
+ (id)shared;
@property(nonatomic) double headsetRemovalTime; // @synthesize headsetRemovalTime=_headsetRemovalTime;
- (BOOL)headsetRecentlyRemoved;
- (void)headsetRemoved;
- (void)dealloc;
- (id)init;

@end

