//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCHereLogger : NSObject
{
    BOOL _firstRequestReported;
    double _startTime;
    double _startTimeWhenAvailable;
    double _prevEventTimestamp;
}

+ (id)sharedInstance;
@property(nonatomic) BOOL firstRequestReported; // @synthesize firstRequestReported=_firstRequestReported;
@property(nonatomic) double prevEventTimestamp; // @synthesize prevEventTimestamp=_prevEventTimestamp;
@property(nonatomic) double startTimeWhenAvailable; // @synthesize startTimeWhenAvailable=_startTimeWhenAvailable;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
- (void)logRenderError:(id)arg1;
- (void)logSetupPhaseChanged:(id)arg1;
- (void)logBroadcastHereLockTop:(BOOL)arg1;
- (void)logExitWithReason:(id)arg1;
- (void)logOutgoingHereStoppedWithReason:(id)arg1 beforeVideoDisplayed:(BOOL)arg2 aloneInScope:(BOOL)arg3;
- (void)logOutgoingHereStarted;

@end

