//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, NSData, NSObject<OS_dispatch_queue>, NSURL;

@interface SCImageToVideoWriter : NSObject
{
    BOOL _processing;
    BOOL _pauseProcessing;
    BOOL _exportOnResume;
    NSData *_imageData;
    NSObject<OS_dispatch_queue> *_processQueue;
    float _duration;
    NSURL *_outputURL;
    AVAssetWriter *_videoWriter;
    AVAssetWriterInput *_videoWriterInput;
    AVAssetWriterInputPixelBufferAdaptor *_adaptor;
    struct __CVBuffer *_pixelBuffer;
    CDUnknownBlockType _completion;
    struct CGSize _size;
}

@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) struct __CVBuffer *pixelBuffer; // @synthesize pixelBuffer=_pixelBuffer;
@property(retain, nonatomic) AVAssetWriterInputPixelBufferAdaptor *adaptor; // @synthesize adaptor=_adaptor;
@property(retain, nonatomic) AVAssetWriterInput *videoWriterInput; // @synthesize videoWriterInput=_videoWriterInput;
@property(retain, nonatomic) AVAssetWriter *videoWriter; // @synthesize videoWriter=_videoWriter;
@property(retain, nonatomic) NSURL *outputURL; // @synthesize outputURL=_outputURL;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(nonatomic) float duration; // @synthesize duration=_duration;
@property BOOL exportOnResume; // @synthesize exportOnResume=_exportOnResume;
@property BOOL pauseProcessing; // @synthesize pauseProcessing=_pauseProcessing;
@property(nonatomic) BOOL processing; // @synthesize processing=_processing;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *processQueue; // @synthesize processQueue=_processQueue;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
- (void).cxx_destruct;
- (struct __CVBuffer *)createCVPixelBufferFromCGImage:(struct CGImage *)arg1 andSize:(struct CGSize)arg2;
- (struct CGImage *)createCGImage;
- (void)cleanup;
- (void)completeWithURL:(id)arg1 error:(id)arg2;
- (void)didFailWithError:(id)arg1;
- (void)didFinish;
- (void)writeFrame:(int)arg1;
- (void)writeToVideoURLWithSize:(struct CGSize)arg1 duration:(float)arg2 completion:(CDUnknownBlockType)arg3;
- (id)generateOutputMovieURL;
- (void)applicationDidBecomeActive;
- (void)applicationWillResignActive;
- (void)dealloc;
- (id)initWithImageData:(id)arg1;

@end

