//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCLocationDataController.h"

@class NSMutableArray;

@interface SCLocationGeoFilterController : SCLocationDataController
{
    NSMutableArray *_geoFilters;
}

@property(retain, nonatomic) NSMutableArray *geoFilters; // @synthesize geoFilters=_geoFilters;
- (void).cxx_destruct;
- (id)logGeoFenceCorrectnessOfFilter:(id)arg1 forlocation:(id)arg2;
- (void)clearCache;
- (BOOL)cacheValidForLocation:(id)arg1;
- (BOOL)shouldUpdateForLocation:(id)arg1;
- (void)processResponse:(id)arg1 location:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)encodeWithCoder:(id)arg1;
- (void)ensureNonNilObjects;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

