//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCLoadingMoreItemsDelegate : NSObject
{
    id <SCFetchableList> _fetchableList;
}

@property(retain, nonatomic) id <SCFetchableList> fetchableList; // @synthesize fetchableList=_fetchableList;
- (void).cxx_destruct;
- (BOOL)isLoadingCellIndexPath:(id)arg1;
- (void)loadMoreItems;
- (BOOL)moreItemsToLoad;
- (BOOL)failedToLoadMoreItems;
- (BOOL)canLoadMoreItems;
- (void)didSelectRowAtIndexPath:(id)arg1;
- (void)willDisplayIndexPath:(id)arg1;

@end

