//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, SCShareUser;

@interface SCLogger : NSObject
{
    NSMutableArray *_events;
    NSMutableSet *_uniqueEvents;
    NSMutableDictionary *_timers;
    NSMutableDictionary *_timedEvents;
    NSMutableDictionary *_counters;
    SCShareUser *_shareUser;
    NSArray *_performanceEvents;
    NSMutableArray *_savedEvents;
}

+ (id)sharedInstance;
+ (id)reachabilityString:(int)arg1;
+ (double)memoryFreeMB;
+ (double)memoryUsedMB;
@property(retain, nonatomic) NSMutableArray *savedEvents; // @synthesize savedEvents=_savedEvents;
@property(retain, nonatomic) NSArray *performanceEvents; // @synthesize performanceEvents=_performanceEvents;
@property(retain, nonatomic) SCShareUser *shareUser; // @synthesize shareUser=_shareUser;
@property(retain, nonatomic) NSMutableDictionary *counters; // @synthesize counters=_counters;
@property(retain, nonatomic) NSMutableDictionary *timedEvents; // @synthesize timedEvents=_timedEvents;
@property(retain, nonatomic) NSMutableDictionary *timers; // @synthesize timers=_timers;
@property(retain, nonatomic) NSMutableSet *uniqueEvents; // @synthesize uniqueEvents=_uniqueEvents;
@property(retain, nonatomic) NSMutableArray *events; // @synthesize events=_events;
- (void).cxx_destruct;
- (void)logProfileEvent:(id)arg1 context:(id)arg2 success:(BOOL)arg3 additionalParameters:(id)arg4 secretParameters:(id)arg5;
- (id)getProfilePageNameForContext:(id)arg1;
- (void)logWithAmplitude:(id)arg1 parameters:(id)arg2;
- (void)logHandledException:(id)arg1;
- (unsigned int)numEvents;
- (void)setLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(float)arg3 verticalAccuracy:(float)arg4;
- (id)getAndClearEvents;
- (void)addEvent:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4;
- (id)flurryHistogramBucketFor:(double)arg1 and:(double)arg2 and:(int)arg3;
- (id)markEndSessionForType:(id)arg1;
- (void)logEndSessionForType:(id)arg1;
- (BOOL)markStartSessionForType:(id)arg1;
- (void)logStartSessionForType:(id)arg1;
- (void)logPageView:(id)arg1;
- (void)logJSONSerializationError:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3;
- (void)flushEvents;
- (void)logEventsToEventLogger:(id)arg1;
- (void)logEventToEventLogger:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4;
- (void)logEventToEventLogger:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3;
- (void)logEvent:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3;
- (void)logEvent:(id)arg1 parameters:(id)arg2;
- (void)logEvent:(id)arg1;
- (void)restartServices;
- (void)stopServices;
- (void)initServicesWithShareUser:(id)arg1;
- (void)initServicesWithCrashDelegate:(id)arg1;
- (id)commonProperties;
- (id)init;
- (void)logSavedEvents;
- (void)updateContentReadyAndFirstItemReadyEventswithParameters:(id)arg1;
- (void)cancelPerfEventsWhenChatViewAppear;
- (void)cancelPerfEventsWhenPreviewViewAppear;
- (void)cancelPerfEventsWhenSettingViewAppear;
- (void)cancelPerfEventsWhenMyFriendsViewFullyDisappear;
- (void)cancelPerfEventsWhenFeedViewFullyDisappear;
- (void)cancelPerfEventsWhenAddFriendsViewAppear;
- (void)startPerfEventsWhenAppStartupFromBackgroundWithNotification;
- (void)startPerfEventsWhenAppStartupFromBackground;
- (void)startPerfEventsWhenAppStartupFromKilledStateWithNotification;
- (void)startPerfEventsWhenAppStartupFromKilledState;
- (unsigned int)numCounters;
- (void)removeCounterForKey:(id)arg1;
- (int)counterForKey:(id)arg1;
- (void)incrementCounterForKey:(id)arg1;
- (void)startCounterForKey:(id)arg1;
- (void)removeUniqueEvents;
- (void)cancelAllLogTimedEvents;
- (void)cancelLogTimedEvents:(id)arg1;
- (void)cancelLogTimedEvent:(id)arg1;
- (void)cancelLogTimedEvent:(id)arg1 withUniqueId:(id)arg2;
- (void)setStartParameters:(id)arg1 withReachability:(id)arg2 withParameters:(id)arg3;
- (void)updateLogTimedEvent:(id)arg1 withUniqueId:(id)arg2 withParameters:(id)arg3;
- (void)updateLogTimedEventStart:(id)arg1 withUniqueId:(id)arg2 withParameters:(id)arg3;
- (void)updateLogTimedEventStart:(id)arg1 withUniqueId:(id)arg2;
- (void)logTimedEventEnd:(id)arg1 withUniqueId:(id)arg2 withParameters:(id)arg3;
- (void)logStepToEvent:(id)arg1 withUniqueId:(id)arg2 withStepName:(id)arg3;
- (void)disableResetForEvent:(id)arg1 withUniqueId:(id)arg2;
- (void)logTimedEventStart:(id)arg1 withUniqueId:(id)arg2 isUniqueEvent:(BOOL)arg3 withReachability:(id)arg4 withParameters:(id)arg5 shouldLogStartTime:(BOOL)arg6;
- (void)logTimedEventStart:(id)arg1 withUniqueId:(id)arg2 isUniqueEvent:(BOOL)arg3 withReachability:(id)arg4 withParameters:(id)arg5;
- (void)logTimedEventStart:(id)arg1 withUniqueId:(id)arg2 isUniqueEvent:(BOOL)arg3 withReachability:(id)arg4;
- (void)logTimedEventStart:(id)arg1 withUniqueId:(id)arg2 isUniqueEvent:(BOOL)arg3;
- (void)logTimedEvent:(id)arg1 withInterval:(double)arg2;
- (void)logPerformanceEvent:(id)arg1 parameters:(id)arg2;

@end

