//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCLocalNotificationsController : NSObject
{
    BOOL _sentChatOrSnapNotification;
    BOOL _sentStoryNotification;
}

@property(nonatomic) BOOL sentStoryNotification; // @synthesize sentStoryNotification=_sentStoryNotification;
@property(nonatomic) BOOL sentChatOrSnapNotification; // @synthesize sentChatOrSnapNotification=_sentChatOrSnapNotification;
- (BOOL)shouldSendNotificationOfType:(id)arg1;
- (void)sentNotificationOfType:(id)arg1;
- (void)displayLocalNotificationForFailedSendWithUserInfo:(id)arg1;
- (void)handleFailedChatSend:(id)arg1;
- (void)handleFailedStorySend:(id)arg1;
- (void)handleFailedSnapSend:(id)arg1;
- (void)didEnterBackground;
- (void)dealloc;
- (id)init;

@end

