//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSString;

@interface SCLocationController : NSObject <CLLocationManagerDelegate>
{
    BOOL _requestingLocationPermission;
    CLLocationManager *_locationManager;
    CDUnknownBlockType _permissionCompletionBlock;
    CDUnknownBlockType _locationCompletionBlock;
    CDUnknownBlockType _locationFailureBlock;
}

+ (BOOL)isRecentAccurateLocation:(id)arg1;
+ (BOOL)locationAuthorizedWhenInUseWithAuthorizationStatus:(int)arg1;
+ (void)updateLocationAuthorizationStatus;
+ (void)setLocationAuthorizationStatus:(int)arg1;
+ (void)clearLocationAuthorizationStatus;
+ (BOOL)locationAuthorizationDenied;
+ (BOOL)locationAuthorizationNotDetermined;
+ (BOOL)locationAuthorized;
@property(nonatomic) BOOL requestingLocationPermission; // @synthesize requestingLocationPermission=_requestingLocationPermission;
@property(copy, nonatomic) CDUnknownBlockType locationFailureBlock; // @synthesize locationFailureBlock=_locationFailureBlock;
@property(copy, nonatomic) CDUnknownBlockType locationCompletionBlock; // @synthesize locationCompletionBlock=_locationCompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType permissionCompletionBlock; // @synthesize permissionCompletionBlock=_permissionCompletionBlock;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void).cxx_destruct;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)findLocationWithSuccessBlock:(CDUnknownBlockType)arg1 failureBlock:(CDUnknownBlockType)arg2;
- (void)requestLocationPermissionWithCompletionHandler:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

