//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCLocationDataController.h"

@class CLLocation, NSDate, SCWeather;

@interface SCLocationWeatherController : SCLocationDataController
{
    SCWeather *_cachedWeather;
    CLLocation *_lastUpdatedLocation;
    NSDate *_lastUpdatedTimestamp;
}

@property(retain, nonatomic) NSDate *lastUpdatedTimestamp; // @synthesize lastUpdatedTimestamp=_lastUpdatedTimestamp;
@property(retain, nonatomic) CLLocation *lastUpdatedLocation; // @synthesize lastUpdatedLocation=_lastUpdatedLocation;
@property(retain, nonatomic) SCWeather *cachedWeather; // @synthesize cachedWeather=_cachedWeather;
- (void).cxx_destruct;
- (void)clearCache;
- (BOOL)cacheValidForLocation:(id)arg1;
- (BOOL)shouldUpdateForLocation:(id)arg1;
- (void)processResponse:(id)arg1 location:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

