//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCLayoutAccessoryTableViewCellDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, SCFeatureSettings, SCHeader, SCLocationController, UITableView;

@interface SCManageAdditionalServicesViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, SCHeaderDataSource, SCHeaderDelegate, UIAlertViewDelegate, SCLayoutAccessoryTableViewCellDelegate>
{
    id <SCManageAdditionalServicesDelegate> _delegate;
    SCFeatureSettings *_featureSettings;
    SCLocationController *_locationController;
    SCHeader *_header;
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(retain, nonatomic) SCLocationController *locationController; // @synthesize locationController=_locationController;
@property(retain, nonatomic) SCFeatureSettings *featureSettings; // @synthesize featureSettings=_featureSettings;
@property(nonatomic) __weak id <SCManageAdditionalServicesDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)shouldPopToRootViewControllerLater;
- (BOOL)shouldPopToRootViewController;
- (void)handleClickedButtonAtIndexForLocationPermissions:(int)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)promptForLocationServicesRequired;
- (void)requestToUseLocation;
- (void)userPostponedLocationPermissions;
- (void)prepareToRequestToUseLocation;
- (void)didAttemptToTurnOnFilters;
- (void)switchChanged:(id)arg1;
- (BOOL)isSwitchOnForIndexPath:(id)arg1;
- (void)presentBestFriendsCountVC;
- (id)newFiltersAttributionLabel;
- (id)newFiltersTextLabel;
- (id)newSwitchViewForIndexPath:(id)arg1;
- (struct CGRect)layoutAccessoryTableViewCell:(id)arg1 frameForAccessoryView:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)toggleCellForIndexPath:(id)arg1;
- (id)filtersToggleCell;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)updateFeatureSettingsIfNecessary;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)leftButtonPressed;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (unsigned int)supportedInterfaceOrientations;
- (void)dealloc;
- (void)resetView;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillResignActive;
- (void)viewDidLoad;
- (void)initHeader;
- (void)loadView;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

