//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary;

@protocol SCMessageState <NSObject>
- (BOOL)shouldBeAddedAgainGivenClearedDictionary:(NSDictionary *)arg1;
- (unsigned int)friendSaveVersion;
- (unsigned int)userSaveVersion;
- (BOOL)isSaved;
- (BOOL)savedByFriend;
- (BOOL)savedByUser;
- (void)markAsReleasedByFriendWithTimestamp:(NSDate *)arg1;
- (void)markAsReleasedByUser:(BOOL)arg1;
- (BOOL)isReleased;
- (BOOL)releasedByFriend;
- (BOOL)releasedByUser;
@end

