//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCFilterView.h"

@class GPUImageView, UIImageView;

@interface SCMediaFilterView : SCFilterView
{
    UIImageView *_imageView;
    GPUImageView *_videoView;
}

+ (int)type;
@property(retain, nonatomic) GPUImageView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)setVideoViewCenter:(struct CGPoint)arg1;
- (void)setImageViewCenter:(struct CGPoint)arg1;
- (void)endedProcessing;
- (void)startedProcessing;
- (void)cancelImageProcessing;
- (void)processImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setImage:(id)arg1;
- (BOOL)requiresGPU;
- (id)image;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 config:(id)arg2;

@end

