//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary, NSString;

@protocol SCMessage <NSObject>
- (BOOL)shouldDisplayBelowFoldInChat;
- (NSDictionary *)clearedDictionary;
- (BOOL)isInvalidAfterUnarchiving;
- (BOOL)timeToSendHasExpired;
- (NSDate *)sentTimestamp;
- (NSDate *)feedDisplayTimestamp;
- (NSDate *)messageTimestamp;
- (BOOL)isSent;
- (BOOL)isUnread;
- (BOOL)sending;
- (BOOL)failedToSend;
- (BOOL)sentByUser;
- (BOOL)isSendingOrHasFailed;
- (NSString *)messageRecipient;
- (NSString *)messageSender;
- (NSString *)consistentId;
@end

