//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCFilterView.h"

@interface SCOverlayFilterView : SCFilterView
{
}

- (BOOL)shouldRespondToTap:(id)arg1;
- (void)tap:(id)arg1;
- (id)image;
- (id)filterId;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 config:(id)arg2;

@end

