//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UIImage, UIImageView;

@interface SCPaymentSwipeSenderBillView : UIView
{
    BOOL _isIdle;
    id <SCPaymentSwipeSenderBillViewDelegate> _delegate;
    UIImageView *_movingBillView;
    UIImageView *_stillBillView;
    UIImage *_billImage;
    NSMutableArray *_billList;
    int _maxYellowLevel;
    int _yellowLevel;
    float _billStartY;
    struct CGPoint _origin;
}

@property(nonatomic) float billStartY; // @synthesize billStartY=_billStartY;
@property(nonatomic) struct CGPoint origin; // @synthesize origin=_origin;
@property(nonatomic) int yellowLevel; // @synthesize yellowLevel=_yellowLevel;
@property(nonatomic) int maxYellowLevel; // @synthesize maxYellowLevel=_maxYellowLevel;
@property(retain, nonatomic) NSMutableArray *billList; // @synthesize billList=_billList;
@property(retain, nonatomic) UIImage *billImage; // @synthesize billImage=_billImage;
@property(retain, nonatomic) UIImageView *stillBillView; // @synthesize stillBillView=_stillBillView;
@property(retain, nonatomic) UIImageView *movingBillView; // @synthesize movingBillView=_movingBillView;
@property(nonatomic) BOOL isIdle; // @synthesize isIdle=_isIdle;
@property(nonatomic) __weak id <SCPaymentSwipeSenderBillViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)isEarlierThan2011Model;
- (void)handleSwipeCompletionFailure;
- (void)handleSwipeDownCompletionSuccess;
- (void)handleSwipeUpCompletionSuccess;
- (void)handleSwipeChangedWithDeltaY:(float)arg1;
- (void)handleSwipeBegan;
- (void)showStillBill;
- (void)animateIdleBills;
- (int)yellowLevelForSwipeInterval:(float)arg1;
- (void)updateBillColor;
- (void)updateBillColorForYellowLevel:(int)arg1;
- (void)animateBillFlyIn;
- (void)loadBillViews;
- (id)initWithFrame:(struct CGRect)arg1 billStartY:(float)arg2;

@end

