//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@interface SCPaymentBlocker : NSObject
{
    BOOL _requiresPasscode;
    int _type;
    NSURL *_url;
}

+ (BOOL)blockerTypeIsPreInitiateBlocker:(int)arg1;
@property(nonatomic) BOOL requiresPasscode; // @synthesize requiresPasscode=_requiresPasscode;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (int)comparePriority:(id)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isPreInitiateBlocker;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)configureURLForDefaultTypeWithInfo:(id)arg1;
- (void)configureForConfirmTypeWithInfo:(id)arg1;
- (void)configureForURLTypeWithInfo:(id)arg1;
- (id)initWithType:(int)arg1 info:(id)arg2;

@end

