//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SCPaymentMessageSendState : NSObject
{
    int _stateTag;
    id <SCSendStateDelegate> _delegate;
    NSString *_signature;
    NSString *_passcode;
    int _currentAction;
}

+ (BOOL)paymentMessageIsSuccessfullySent:(id)arg1;
@property(nonatomic) int currentAction; // @synthesize currentAction=_currentAction;
@property(readonly, copy) NSString *passcode; // @synthesize passcode=_passcode;
@property(copy) NSString *signature; // @synthesize signature=_signature;
@property(nonatomic) __weak id <SCSendStateDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly) int stateTag; // @synthesize stateTag=_stateTag;
- (void).cxx_destruct;
- (BOOL)isSent;
- (BOOL)failedToSend;
- (BOOL)isSending;
- (void)setStateTag:(int)arg1;
- (void)actionFailed:(int)arg1 withPayment:(id)arg2;
- (void)actionSucceeded:(int)arg1 withPayment:(id)arg2;
- (void)beginAction:(int)arg1;
- (int)nextAction;
- (int)getAndBeginNextAction;
- (void)updateWithPaymentMessage:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDelegate:(id)arg1;
- (id)initWithDelegate:(id)arg1 paymentMessage:(id)arg2;

@end

