//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SCPieAnimationHelpers : NSObject
{
    NSMutableDictionary *_maskImages;
    NSMutableDictionary *_reverseMaskImages;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *reverseMaskImages; // @synthesize reverseMaskImages=_reverseMaskImages;
@property(retain, nonatomic) NSMutableDictionary *maskImages; // @synthesize maskImages=_maskImages;
- (void).cxx_destruct;
- (id)reversePieMaskForImage:(struct CGRect)arg1 startPercent:(float)arg2 endPercent:(float)arg3;
- (id)pieMaskForImage:(struct CGRect)arg1 startPercent:(float)arg2 endPercent:(float)arg3;
- (id)maskImage:(id)arg1 withMask:(id)arg2;
- (id)combineImages:(struct CGRect)arg1 forBackgroundImage:(id)arg2 forForeGroundImage:(id)arg3;
- (id)centerCropImage:(id)arg1;
- (id)init;

@end

