//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol SCProfileViewDelegate
- (BOOL)shouldAutomaticallyHide;
- (void)displayNamePressed;
- (void)setProfileScrollViewOffsetToBottom:(BOOL)arg1 animated:(BOOL)arg2;
- (void)settingsButtonPressed;
- (void)myFriendsButtonPressed;
- (void)addFriendsButtonPressed;
- (void)recentFriendsButtonPressed;
@end

