//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCSnaptagHelpVideoViewDelegate.h"

@class NSString, SCHeader, SCSnaptagHelpVideoView, UIButton, UIImage, UIImageView, UILabel;

@interface SCProfileView : UIView <SCHeaderDataSource, SCHeaderDelegate, SCSnaptagHelpVideoViewDelegate>
{
    UIImage *_qrCodeImage;
    id <SCProfileViewDelegate> _delegate;
    SCHeader *_header;
    UIButton *_backToCameraButton;
    UIButton *_settingsButton;
    UIImageView *_qrCodeView;
    UIButton *_displayNameButton;
    UILabel *_username;
    UIView *_optionalSpacerBetweenButtonsAndNames;
    UIButton *_recentFriendsButton;
    UIButton *_addFriendsButton;
    UIButton *_myContactsButton;
    UIButton *_downButton;
    SCSnaptagHelpVideoView *_snaptagHelpVideoView;
}

+ (id)getTitleColorForNewFriends:(float)arg1 andButtonState:(unsigned int)arg2;
+ (id)getImageForNewFriends:(float)arg1 andButtonState:(unsigned int)arg2;
@property(retain, nonatomic) SCSnaptagHelpVideoView *snaptagHelpVideoView; // @synthesize snaptagHelpVideoView=_snaptagHelpVideoView;
@property(retain, nonatomic) UIButton *downButton; // @synthesize downButton=_downButton;
@property(retain, nonatomic) UIButton *myContactsButton; // @synthesize myContactsButton=_myContactsButton;
@property(retain, nonatomic) UIButton *addFriendsButton; // @synthesize addFriendsButton=_addFriendsButton;
@property(retain, nonatomic) UIButton *recentFriendsButton; // @synthesize recentFriendsButton=_recentFriendsButton;
@property(retain, nonatomic) UIView *optionalSpacerBetweenButtonsAndNames; // @synthesize optionalSpacerBetweenButtonsAndNames=_optionalSpacerBetweenButtonsAndNames;
@property(retain, nonatomic) UILabel *username; // @synthesize username=_username;
@property(retain, nonatomic) UIButton *displayNameButton; // @synthesize displayNameButton=_displayNameButton;
@property(retain, nonatomic) UIImageView *qrCodeView; // @synthesize qrCodeView=_qrCodeView;
@property(retain, nonatomic) UIButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) UIButton *backToCameraButton; // @synthesize backToCameraButton=_backToCameraButton;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(nonatomic) __weak id <SCProfileViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImage *qrCodeImage; // @synthesize qrCodeImage=_qrCodeImage;
- (void).cxx_destruct;
- (void)rightButtonPressed;
- (void)leftButtonPressed;
- (void)downButtonPressed;
- (void)appWillEnterForeground;
- (id)backgroundColorForHeader;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (void)hideProfile;
- (void)setNewFriendsCount:(unsigned int)arg1;
- (void)snaptagHelpViewShouldClose;
- (void)snaptagHelpButtonPressed;
- (void)setUserName:(id)arg1 andDisplayName:(id)arg2 andScore:(unsigned int)arg3;
- (id)displayImageForSnaptag:(id)arg1;
- (void)setImageForSnaptag:(id)arg1;
- (void)dealloc;
- (void)initDownButtonBelow:(id)arg1;
- (void)initFriendButtonsInside:(id)arg1;
- (void)initHeaderNav;
- (void)initPersonalIdentifierInside:(id)arg1;
- (void)initNotifications;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

