//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface SCProgressSaveButtonLayer : CALayer
{
    float _saveProgress;
    float _postSaveProgress;
}

+ (id)checkmarkPathWithRect:(struct CGRect)arg1 andProgress:(float)arg2;
+ (id)arrowPathWithRect:(struct CGRect)arg1 andProgress:(float)arg2;
+ (id)clippingPathWithRect:(struct CGRect)arg1;
+ (id)staticPathWithRect:(struct CGRect)arg1;
+ (id)progressBarWithRect:(struct CGRect)arg1 andProgress:(float)arg2;
+ (BOOL)needsDisplayForKey:(id)arg1;
@property(nonatomic) float postSaveProgress; // @synthesize postSaveProgress=_postSaveProgress;
@property(nonatomic) float saveProgress; // @synthesize saveProgress=_saveProgress;
- (void)drawInContext:(struct CGContext *)arg1;

@end

