//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UITextView;

@interface SCPurpleTooltipBalloon : UIView
{
    UITextView *_textView;
    UIView *_triangle;
    UIView *_backgroundRectangle;
}

@property(retain, nonatomic) UIView *backgroundRectangle; // @synthesize backgroundRectangle=_backgroundRectangle;
@property(retain, nonatomic) UIView *triangle; // @synthesize triangle=_triangle;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)setText:(id)arg1;
- (id)createTriangle;
- (id)initWithFrame:(struct CGRect)arg1 discover:(BOOL)arg2;

@end

