//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCTextViewDelegate.h"
#import "TTTAttributedLabelDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSDate, NSDateFormatter, NSString, SCButton, SCHeader, SCTextView, UIDatePicker, UIScrollView;

@interface SCRegisterView : UIView <SCHeaderDelegate, SCHeaderDataSource, SCTextViewDelegate, TTTAttributedLabelDelegate, UIScrollViewDelegate>
{
    BOOL _fieldIsFirstResponder;
    NSDate *_birthday;
    id <SCRegisterViewDelegate> _delegate;
    NSDate *_date;
    SCHeader *_header;
    UIScrollView *_scrollView;
    SCTextView *_emailTextView;
    SCTextView *_passwordTextView;
    UIDatePicker *_agePickerView;
    SCTextView *_birthDateTextView;
    SCButton *_enterButton;
    NSDateFormatter *_dateFormatter;
    float _scrollOffset;
}

@property(nonatomic) float scrollOffset; // @synthesize scrollOffset=_scrollOffset;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(nonatomic) BOOL fieldIsFirstResponder; // @synthesize fieldIsFirstResponder=_fieldIsFirstResponder;
@property(retain, nonatomic) SCButton *enterButton; // @synthesize enterButton=_enterButton;
@property(retain, nonatomic) SCTextView *birthDateTextView; // @synthesize birthDateTextView=_birthDateTextView;
@property(retain, nonatomic) UIDatePicker *agePickerView; // @synthesize agePickerView=_agePickerView;
@property(retain, nonatomic) SCTextView *passwordTextView; // @synthesize passwordTextView=_passwordTextView;
@property(retain, nonatomic) SCTextView *emailTextView; // @synthesize emailTextView=_emailTextView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(nonatomic) __weak id <SCRegisterViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDate *birthday; // @synthesize birthday=_birthday;
- (void).cxx_destruct;
- (BOOL)isDisplayingError;
- (void)makeFirstResponderForInputType:(unsigned int)arg1;
- (void)setInputEnabled:(BOOL)arg1;
- (void)hideAgePicker;
- (void)showAgePicker;
- (void)hideEnterButtonWithInputsVisible:(BOOL)arg1;
- (void)showEnterButtonWithInputsVisible:(BOOL)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)textViewDidMakeFirstEdit:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textViewShouldReturn:(id)arg1;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)leftButtonPressed;
- (void)birthdayDidChange:(id)arg1;
- (void)setError:(id)arg1 forInputType:(unsigned int)arg2;
@property(readonly, copy, nonatomic) NSString *password;
@property(readonly, copy, nonatomic) NSString *email;
- (void)updateBirthday;
- (void)viewDidAppear:(BOOL)arg1;
- (void)initAgePickerView;
- (void)initEnterButton;
- (void)initUserAgreementLabel;
- (void)initAgeTextView;
- (void)initPasswordTextField;
- (void)initEmailTextField;
- (void)initHeader;
- (void)dealloc;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

