//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIActivityIndicatorView, UIImage, UITextView;

@interface SCReportLogsViewController : UIViewController
{
    UIImage *_screenshot;
    UIActivityIndicatorView *_spinner;
    UITextView *_textView;
}

+ (id)lastFiveTracesFromPreviousSession;
+ (BOOL)memoryCrashOccurredOnLastLoad;
+ (id)deviceUserInfoAndLogsForShake:(BOOL)arg1;
+ (id)deviceAndUserInfoForShake:(BOOL)arg1;
+ (id)consoleLogs;
+ (void)endLogSession;
+ (void)beginNewLogSession;
+ (id)logPath:(int)arg1;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UIImage *screenshot; // @synthesize screenshot=_screenshot;
- (void).cxx_destruct;
- (void)tap:(id)arg1;
- (void)send;
- (void)cancel;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)initWithScreenshot:(id)arg1;

@end

