//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCLayout.h"

@class NSString, UIView;

@interface SCSelectRecipientsViewLayout : NSObject <SCLayout>
{
    UIView *_tableView;
    UIView *_tableIndex;
}

@property(retain, nonatomic) UIView *tableIndex; // @synthesize tableIndex=_tableIndex;
@property(retain, nonatomic) UIView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)layoutSubviewsInFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

