//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSString, SCSendArrow, SCSharedStorySponsor, UILabel, UIScrollView;

@interface SCSendConfirmationViewController : UIViewController <UIGestureRecognizerDelegate>
{
    BOOL _addToMyStory;
    BOOL _addToSharedStory;
    BOOL _quickSend;
    BOOL _hasTapHintAnimation;
    id <SCSendConfirmationViewControllerDelegate> _delegate;
    NSArray *_recipients;
    SCSharedStorySponsor *_sharedStorySponsor;
    UILabel *_recipientsLabel;
    UILabel *_hintLabel;
    UIScrollView *_recipientsScrollView;
    SCSendArrow *_sendArrow;
}

@property(retain, nonatomic) SCSendArrow *sendArrow; // @synthesize sendArrow=_sendArrow;
@property(retain, nonatomic) UIScrollView *recipientsScrollView; // @synthesize recipientsScrollView=_recipientsScrollView;
@property(retain, nonatomic) UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(retain, nonatomic) UILabel *recipientsLabel; // @synthesize recipientsLabel=_recipientsLabel;
@property(retain, nonatomic) SCSharedStorySponsor *sharedStorySponsor; // @synthesize sharedStorySponsor=_sharedStorySponsor;
@property(retain, nonatomic) NSArray *recipients; // @synthesize recipients=_recipients;
@property(nonatomic) BOOL hasTapHintAnimation; // @synthesize hasTapHintAnimation=_hasTapHintAnimation;
@property(nonatomic) BOOL quickSend; // @synthesize quickSend=_quickSend;
@property(nonatomic) BOOL addToSharedStory; // @synthesize addToSharedStory=_addToSharedStory;
@property(nonatomic) BOOL addToMyStory; // @synthesize addToMyStory=_addToMyStory;
@property(nonatomic) __weak id <SCSendConfirmationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateRecipients;
- (void)setSendButtonEnabled:(BOOL)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)recipientsScrollViewTapped:(id)arg1;
- (void)sendPressed;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)showHintLabelBriefly;
- (void)showTapToAddLabelBrieflyIfNecessary;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

