//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Friend, NSArray, NSDictionary, NSIndexPath, NSString, UITableView, UITableViewCell;

@protocol SCSearchFriendsSubViewControllerDelegate <NSObject>
- (UITableViewCell *)cellForModelView:(Friend *)arg1 onTableView:(UITableView *)arg2 forRowAtindexPath:(NSIndexPath *)arg3;
- (NSDictionary *)getSearchResultsBySection:(NSArray *)arg1 withSearchText:(NSString *)arg2;
- (NSString *)pageName;

@optional
- (void)didSelectCell:(UITableViewCell *)arg1;
- (void)didBeginEditingSearchBox;
- (void)didDismissSearch;
@end

