//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCGeofencedObject.h"

@class NSString;

@interface SCSharedStorySponsor : SCGeofencedObject
{
    BOOL _localStory;
    NSString *_friendName;
    NSString *_myStoriesDisplayName;
    NSString *_sendScreenDisplayName;
    NSString *_storyGroupId;
    NSString *_username;
    NSString *_venue;
}

@property(nonatomic, getter=isLocalStory) BOOL localStory; // @synthesize localStory=_localStory;
@property(copy, nonatomic) NSString *venue; // @synthesize venue=_venue;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *storyGroupId; // @synthesize storyGroupId=_storyGroupId;
@property(copy, nonatomic) NSString *sendScreenDisplayName; // @synthesize sendScreenDisplayName=_sendScreenDisplayName;
@property(copy, nonatomic) NSString *myStoriesDisplayName; // @synthesize myStoriesDisplayName=_myStoriesDisplayName;
@property(copy, nonatomic) NSString *friendName; // @synthesize friendName=_friendName;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

