//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SCSharedStoriesDescriptionStore : NSObject
{
    NSMutableDictionary *_sharedStoryDescriptions;
}

+ (BOOL)initialized;
+ (id)shared;
+ (id)path;
@property(retain, nonatomic) NSMutableDictionary *sharedStoryDescriptions; // @synthesize sharedStoryDescriptions=_sharedStoryDescriptions;
- (void).cxx_destruct;
- (void)fetchDescriptionForSharedStoryId:(id)arg1;
- (id)setForId:(id)arg1;
- (void)clear;
- (BOOL)saveState;
- (void)encodeWithCoder:(id)arg1;
- (void)ensureNonNilObjects;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

