//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCSnapScanner : NSObject
{
    id <SCSnapScannerDelegate> _delegate;
    int _expectedFrameWidth;
    int _frameCounter;
    double _lastTime;
}

@property(nonatomic) double lastTime; // @synthesize lastTime=_lastTime;
@property(nonatomic) int frameCounter; // @synthesize frameCounter=_frameCounter;
@property(nonatomic) int expectedFrameWidth; // @synthesize expectedFrameWidth=_expectedFrameWidth;
@property(nonatomic) __weak id <SCSnapScannerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)scanBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (id)init;

@end

