//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, SCSnapScanner, UIImage;

@protocol SCSnapScannerDelegate <NSObject>
- (void)snapScanner:(SCSnapScanner *)arg1 didDetectSnapcode:(NSData *)arg2 withVersion:(int)arg3;

@optional
- (void)snapScanner:(SCSnapScanner *)arg1 didUpdateFrameRate:(int)arg2;
- (void)snapScanner:(SCSnapScanner *)arg1 didRenderDataImage:(UIImage *)arg2;
@end

