//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface SCStoryLogger : NSObject
{
    NSMutableSet *_flurryLoggedVisibleSponsoredStories;
    NSMutableSet *_viewedStoriesUsernames;
    unsigned int _numSnapsViewed;
    float _timeOfViewingStories;
}

+ (id)sharedInstance;
@property(nonatomic) float timeOfViewingStories; // @synthesize timeOfViewingStories=_timeOfViewingStories;
@property(nonatomic) unsigned int numSnapsViewed; // @synthesize numSnapsViewed=_numSnapsViewed;
@property(retain, nonatomic) NSMutableSet *viewedStoriesUsernames; // @synthesize viewedStoriesUsernames=_viewedStoriesUsernames;
@property(retain, nonatomic) NSMutableSet *flurryLoggedVisibleSponsoredStories; // @synthesize flurryLoggedVisibleSponsoredStories=_flurryLoggedVisibleSponsoredStories;
- (void).cxx_destruct;
- (void)logDownloadStoryEnd:(id)arg1 success:(BOOL)arg2;
- (void)logDownloadStoryStart:(id)arg1;
- (void)logViewStoryEnd:(id)arg1;
- (void)logViewStoryStart:(id)arg1 initialView:(BOOL)arg2;
- (void)logViewSponsoredStoryCell:(id)arg1;
- (void)logSkipStory:(id)arg1 viewingType:(int)arg2;
- (void)logViewMyStories;
- (void)logScreenshotStory:(id)arg1 viewingType:(int)arg2 isAtRecentUpdate:(BOOL)arg3;
- (id)brandSnapStoryViewEventNameWithStoryID:(id)arg1;
- (void)logViewStory:(id)arg1 viewingType:(int)arg2 context:(id)arg3;
- (void)logFinishViewingStories:(id)arg1 isUnviewedStories:(BOOL)arg2 isFullViewed:(BOOL)arg3;
- (void)logStartViewingStoriesOfUser:(id)arg1 type:(int)arg2;
- (void)logPostStoryFailed:(id)arg1;
- (void)logPostStory:(id)arg1 postingType:(unsigned int)arg2;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)dealloc;
- (id)init;

@end

