//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCSelectSingleRecipientDelegate.h"

@class NSString, SCHeader, SCSelectRecipientsViewController, UIView;

@interface SCStartChatViewController : UIViewController <SCHeaderDataSource, SCHeaderDelegate, SCSelectSingleRecipientDelegate>
{
    id <SCStartChatDelegate> _delegate;
    UIView *_containerView;
    SCHeader *_header;
    SCSelectRecipientsViewController *_selectRecipientVC;
}

@property(retain, nonatomic) SCSelectRecipientsViewController *selectRecipientVC; // @synthesize selectRecipientVC=_selectRecipientVC;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <SCStartChatDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didSelectCellForRecipient:(id)arg1;
- (id)chatForRecipient:(id)arg1;
- (void)rightButtonPressed;
- (id)imageForRightButtonInState:(unsigned int)arg1;
- (id)imageForLeftButtonInState:(unsigned int)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)initHeader;
- (void)loadView;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

