//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCSwipeFilterView;

@protocol SCSwipeFilterViewDelegate <NSObject>
- (BOOL)swipeFilterViewCanScroll:(SCSwipeFilterView *)arg1;

@optional
- (void)swipeViewDidEndDoubleSwiping:(SCSwipeFilterView *)arg1;
- (void)swipeViewDidStartDoubleSwiping:(SCSwipeFilterView *)arg1;
- (void)swipeViewDidEndDecelerating:(SCSwipeFilterView *)arg1;
- (void)swipeFilterViewDidScroll:(SCSwipeFilterView *)arg1;
@end

