//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SwipeViewDataSource.h"
#import "SwipeViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, SCDrawingView, SwipeView, UIImageView, UILongPressGestureRecognizer, UIPanGestureRecognizer;

@interface SCSwipeFilterView : UIView <SwipeViewDataSource, SwipeViewDelegate, UIGestureRecognizerDelegate>
{
    BOOL _doubleSwipingEnabled;
    BOOL _indexChangedOnDidEndDragging;
    BOOL _swipeLogged;
    BOOL _exitingDoubleSwiping;
    BOOL _reloading;
    NSString *_swipeFilterType;
    id <SCSwipeFilterViewDelegate> _delegate;
    NSMutableDictionary *_filteredMediaViewsDictionary;
    NSMutableDictionary *_filteredOverlayViewsDictionary;
    int _orientation;
    NSMutableArray *_overlaySwipeViews;
    SwipeView *_mediaSwipeView;
    SwipeView *_controlSwipeView;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UIImageView *_drawingImageView;
    SCDrawingView *_drawingView;
    NSMutableDictionary *_filterConfigs;
    NSMutableArray *_filterNames;
    unsigned int _numberOfFilterChanges;
    unsigned int _numberOfGeoFilterImpressions;
    int _state;
    int _firstSelectedType;
    int _firstSelectedIndex;
    int _secondSelectedType;
    int _secondSelectedIndex;
}

+ (id)logNameForFilterName:(id)arg1;
@property(nonatomic) BOOL reloading; // @synthesize reloading=_reloading;
@property(nonatomic) int secondSelectedIndex; // @synthesize secondSelectedIndex=_secondSelectedIndex;
@property(nonatomic) int secondSelectedType; // @synthesize secondSelectedType=_secondSelectedType;
@property(nonatomic) int firstSelectedIndex; // @synthesize firstSelectedIndex=_firstSelectedIndex;
@property(nonatomic) int firstSelectedType; // @synthesize firstSelectedType=_firstSelectedType;
@property(nonatomic) BOOL exitingDoubleSwiping; // @synthesize exitingDoubleSwiping=_exitingDoubleSwiping;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) BOOL swipeLogged; // @synthesize swipeLogged=_swipeLogged;
@property(nonatomic) unsigned int numberOfGeoFilterImpressions; // @synthesize numberOfGeoFilterImpressions=_numberOfGeoFilterImpressions;
@property(nonatomic) unsigned int numberOfFilterChanges; // @synthesize numberOfFilterChanges=_numberOfFilterChanges;
@property(nonatomic) BOOL indexChangedOnDidEndDragging; // @synthesize indexChangedOnDidEndDragging=_indexChangedOnDidEndDragging;
@property(retain, nonatomic) NSMutableArray *filterNames; // @synthesize filterNames=_filterNames;
@property(retain, nonatomic) NSMutableDictionary *filterConfigs; // @synthesize filterConfigs=_filterConfigs;
@property(retain, nonatomic) SCDrawingView *drawingView; // @synthesize drawingView=_drawingView;
@property(retain, nonatomic) UIImageView *drawingImageView; // @synthesize drawingImageView=_drawingImageView;
@property(nonatomic, getter=isDoubleSwipingEnabled) BOOL doubleSwipingEnabled; // @synthesize doubleSwipingEnabled=_doubleSwipingEnabled;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) SwipeView *controlSwipeView; // @synthesize controlSwipeView=_controlSwipeView;
@property(retain, nonatomic) SwipeView *mediaSwipeView; // @synthesize mediaSwipeView=_mediaSwipeView;
@property(retain, nonatomic) NSMutableArray *overlaySwipeViews; // @synthesize overlaySwipeViews=_overlaySwipeViews;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) NSMutableDictionary *filteredOverlayViewsDictionary; // @synthesize filteredOverlayViewsDictionary=_filteredOverlayViewsDictionary;
@property(retain, nonatomic) NSMutableDictionary *filteredMediaViewsDictionary; // @synthesize filteredMediaViewsDictionary=_filteredMediaViewsDictionary;
@property(nonatomic) __weak id <SCSwipeFilterViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *swipeFilterType; // @synthesize swipeFilterType=_swipeFilterType;
- (void).cxx_destruct;
- (void)resetSwipeViewBoundsAndCenter;
- (void)resetSwipeFilterViewCenter;
- (void)reloadData;
- (void)swipeView:(id)arg1 reloadDataAndScrollToOffset:(float)arg2;
- (BOOL)shouldRespondToTap:(id)arg1;
- (void)press:(id)arg1;
- (void)tap:(id)arg1;
- (void)swipeViewDidEndDecelerating:(id)arg1;
- (void)swipeViewCurrentItemIndexDidChange:(id)arg1 previousIndex:(int)arg2;
- (void)swipeViewDidScroll:(id)arg1;
- (void)swipeViewWillBeginDragging:(id)arg1;
- (struct CGSize)swipeViewItemSize:(id)arg1;
- (id)swipeView:(id)arg1 viewForItemAtIndex:(int)arg2 reusingView:(id)arg3;
- (int)numberOfItemsInSwipeView:(id)arg1;
- (void)exitDoubleSwipingState;
- (void)toDoubleSwipingRecoverState;
- (void)toDoubleSwipingState;
- (void)toSingleSwipingStateFromDoubleSwiping;
- (void)toSingleSwipingStateFromDoubleSwipingRecover;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)currentOverlayFilterViewForType:(int)arg1;
- (id)currentMediaFilterView;
- (id)currentFilterNameForType:(int)arg1;
- (int)currentFilterIndexForType:(int)arg1;
- (BOOL)containsFilterName:(id)arg1 forType:(int)arg2;
- (void)cleanupFilterViewWithName:(id)arg1;
- (void)scrollToFilterAtIndex:(unsigned int)arg1;
- (void)removeFilterName:(id)arg1 forType:(int)arg2;
- (void)insertFilterName:(id)arg1 afterFilterName:(id)arg2 config:(id)arg3 forType:(int)arg4;
- (void)insertFilterName:(id)arg1 beforeFilterName:(id)arg2 config:(id)arg3 forType:(int)arg4;
- (void)insertFilterName:(id)arg1 atIndex:(int)arg2 config:(id)arg3 forType:(int)arg4;
- (void)insertFilterName:(id)arg1 afterFilterName:(id)arg2 forType:(int)arg3;
- (void)insertFilterName:(id)arg1 beforeFilterName:(id)arg2 forType:(int)arg3;
- (void)insertFilterName:(id)arg1 atIndex:(int)arg2 forType:(int)arg3;
- (void)addFilterNames:(id)arg1 forType:(int)arg2;
- (void)addFilterName:(id)arg1 config:(id)arg2 forType:(int)arg3;
- (void)addFilterName:(id)arg1 forType:(int)arg2;
- (BOOL)containsFilterName:(id)arg1;
- (void)removeFilterName:(id)arg1;
- (void)insertFilterName:(id)arg1 afterFilterName:(id)arg2 config:(id)arg3;
- (void)insertFilterName:(id)arg1 beforeFilterName:(id)arg2 config:(id)arg3;
- (void)insertFilterName:(id)arg1 atIndex:(int)arg2 config:(id)arg3;
- (void)insertFilterName:(id)arg1 afterFilterName:(id)arg2;
- (void)insertFilterName:(id)arg1 beforeFilterName:(id)arg2;
- (void)insertFilterName:(id)arg1 atIndex:(int)arg2;
- (void)addFilterNames:(id)arg1;
- (void)addFilterName:(id)arg1 config:(id)arg2;
- (void)addFilterName:(id)arg1;
- (int)typeFromFilterName:(id)arg1 config:(id)arg2;
- (void)removeInvalidFilters;
- (unsigned int)filterCountForType:(int)arg1;
- (id)filterViewForName:(id)arg1 forType:(int)arg2;
- (id)overlayFilterViewForName:(id)arg1;
- (id)mediaFilterViewForName:(id)arg1;
- (id)newMediaFilterViewForName:(id)arg1;
- (BOOL)isScrolling;
- (BOOL)isDoubleSwiping;
@property(readonly, nonatomic) UIPanGestureRecognizer *scrollViewPanGestureRecognizer;
- (id)swipeViewForType:(int)arg1;
- (void)setSwipeViewUserInteractionEnabled:(BOOL)arg1;
- (void)setScrollEnabled:(BOOL)arg1;
- (id)overlayImage;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

