//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCTCPSessionDataSource.h"

@class NSDate, NSString;

@interface SCTCPSessionDataStore : NSObject <SCTCPSessionDataSource>
{
    unsigned short _port;
    NSDate *_lastUpdated;
    NSString *_host;
    NSString *_mac;
    NSString *_payload;
}

@property(copy, nonatomic) NSString *payload; // @synthesize payload=_payload;
@property(copy, nonatomic) NSString *mac; // @synthesize mac=_mac;
@property(nonatomic) unsigned short port; // @synthesize port=_port;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
@property(retain, nonatomic) NSDate *lastUpdated; // @synthesize lastUpdated=_lastUpdated;
- (void).cxx_destruct;
- (void)updateWithAlternateTCPServer:(id)arg1;
- (unsigned short)tcpPort;
- (id)tcpHost;
- (id)tcpAuthDictionary;
- (BOOL)isValid;
- (void)updateWithJSONDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

