//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSError;

@protocol SCTCPSessionDelegate <NSObject>
- (void)didDisconnectWithError:(NSError *)arg1;
- (void)didEndSession;
- (void)didStartSession;
- (void)didFailToStartSessionWithError:(NSError *)arg1;
- (void)didReceiveJSONDictionary:(NSDictionary *)arg1;
@end

