//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "TTTAttributedLabelDelegate.h"

@class NSString, SCAnimatingReplaySnapView, SCChatCellImageView, SCLinkAttribute, TTTAttributedLabel, UIActivityIndicatorView, UIImageView, UILabel, UIView;

@interface SCTextTableViewCell : UITableViewCell <TTTAttributedLabelDelegate>
{
    BOOL _isPaymentMessage;
    BOOL _activeCashTouch;
    id <SCTextTableViewCellDelegate> _delegate;
    UIActivityIndicatorView *_activity;
    SCAnimatingReplaySnapView *_animatingReplaySnapView;
    UIView *_animatingSnapView;
    UIView *_containerView;
    NSString *_chatId;
    SCChatCellImageView *_chatImageView;
    TTTAttributedLabel *_chatLabel;
    UIView *_chatLine;
    UILabel *_dateHeaderLabel;
    UIImageView *_failedIconImageView;
    UILabel *_headerLabel;
    SCLinkAttribute *_productToDisplayLinkAttribute;
    UIView *_savedBackground;
    UIImageView *_snapIconImageView;
    TTTAttributedLabel *_snapLabel;
    TTTAttributedLabel *_snapSublabel;
    UILabel *_timeLabel;
    UILabel *_timerLabel;
    UIView *_cashBackground;
    UIImageView *_sparkleImageView;
}

+ (id)cashTagColor;
+ (id)unknownMessageBackgroundColor;
+ (id)unknownMessageColor;
+ (id)snapLabelColor;
+ (id)textColor;
+ (id)sendingTextColor;
+ (id)grayChatColor;
+ (id)blueTextColor;
+ (id)redTextColor;
+ (BOOL)hasAtLeastOneEmoji:(id)arg1;
+ (BOOL)hasOnlyEmoji:(id)arg1;
+ (BOOL)isNumberEmoji:(id)arg1;
+ (float)bigEmojiHeightForCellTextWidth:(float)arg1;
+ (id)attributedStringForText:(id)arg1 saved:(BOOL)arg2;
+ (id)timerFont;
+ (id)savedCashLabelFont;
+ (id)snapSublabelFont;
+ (id)snapLabelFont;
+ (id)savedTimeLabelFont;
+ (float)timeLabelWidth;
+ (id)timeLabelFont;
+ (id)headerLabelFont;
+ (id)dateHeaderLabelFont;
+ (id)savedTextLabelFont;
+ (id)italicTextLabelFont;
+ (id)emojiOnlyLabelFont;
+ (id)textLabelFont;
+ (float)heightForMessage:(id)arg1 withDateHeader:(BOOL)arg2 withHeader:(BOOL)arg3 withBottomPadding:(BOOL)arg4 isLastMessage:(BOOL)arg5;
@property(nonatomic) BOOL activeCashTouch; // @synthesize activeCashTouch=_activeCashTouch;
@property(nonatomic) BOOL isPaymentMessage; // @synthesize isPaymentMessage=_isPaymentMessage;
@property(retain, nonatomic) UIImageView *sparkleImageView; // @synthesize sparkleImageView=_sparkleImageView;
@property(retain, nonatomic) UIView *cashBackground; // @synthesize cashBackground=_cashBackground;
@property(retain, nonatomic) UILabel *timerLabel; // @synthesize timerLabel=_timerLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) TTTAttributedLabel *snapSublabel; // @synthesize snapSublabel=_snapSublabel;
@property(retain, nonatomic) TTTAttributedLabel *snapLabel; // @synthesize snapLabel=_snapLabel;
@property(retain, nonatomic) UIImageView *snapIconImageView; // @synthesize snapIconImageView=_snapIconImageView;
@property(retain, nonatomic) UIView *savedBackground; // @synthesize savedBackground=_savedBackground;
@property(retain, nonatomic) SCLinkAttribute *productToDisplayLinkAttribute; // @synthesize productToDisplayLinkAttribute=_productToDisplayLinkAttribute;
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(retain, nonatomic) UIImageView *failedIconImageView; // @synthesize failedIconImageView=_failedIconImageView;
@property(retain, nonatomic) UILabel *dateHeaderLabel; // @synthesize dateHeaderLabel=_dateHeaderLabel;
@property(retain, nonatomic) UIView *chatLine; // @synthesize chatLine=_chatLine;
@property(retain, nonatomic) TTTAttributedLabel *chatLabel; // @synthesize chatLabel=_chatLabel;
@property(retain, nonatomic) SCChatCellImageView *chatImageView; // @synthesize chatImageView=_chatImageView;
@property(copy, nonatomic) NSString *chatId; // @synthesize chatId=_chatId;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *animatingSnapView; // @synthesize animatingSnapView=_animatingSnapView;
@property(retain, nonatomic) SCAnimatingReplaySnapView *animatingReplaySnapView; // @synthesize animatingReplaySnapView=_animatingReplaySnapView;
@property(retain, nonatomic) UIActivityIndicatorView *activity; // @synthesize activity=_activity;
@property(nonatomic) __weak id <SCTextTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)touchHitsCashBackground:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithPhoneNumber:(id)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithAddress:(id)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)setURLsVisible:(BOOL)arg1;
- (void)animatePaymentReceiverSparkles:(id)arg1;
- (void)animateReplayWithSnapIfNecessary:(id)arg1;
- (void)snapFieldsSetBigIcon;
- (void)snapFieldsSetSmallIcon;
- (void)snapFieldsSetY:(float)arg1;
- (void)setCashFieldsHidden:(BOOL)arg1;
- (void)setSnapReplayFieldsHiddenForSnap:(id)arg1;
- (void)setImageFieldsHidden:(BOOL)arg1;
- (void)setTextFieldsHidden:(BOOL)arg1;
- (void)setSnapSublabelHidden:(BOOL)arg1;
- (void)setSnapFieldsHidden:(BOOL)arg1;
- (void)adjustDateHeaderForOffset:(float)arg1;
- (struct CGRect)chatImageViewFrame;
- (void)setMessageFailedToSend:(BOOL)arg1;
- (void)setHeaderLabelForSender:(id)arg1;
- (void)setDateHeaderLabelForDate:(id)arg1;
- (void)setHeaderVisible:(BOOL)arg1 dateHeaderVisible:(BOOL)arg2;
- (void)setSaved:(BOOL)arg1 message:(id)arg2;
- (void)setTime:(id)arg1;
- (void)setText:(id)arg1 saved:(BOOL)arg2;
- (void)setPaymentMessage:(id)arg1;
- (void)setTextAttributesForSuccessfulPaymentMessage:(id)arg1;
- (void)setTodayPlaceHolder;
- (void)setTextAttributesWithText:(id)arg1;
- (void)setTextWithMessage:(id)arg1;
- (void)setTextWithMedia:(id)arg1;
- (void)setSnap:(id)arg1;
- (void)setTextWithScreenshot:(id)arg1 sender:(id)arg2;
- (void)setUnknownChat:(id)arg1 sender:(id)arg2;
- (void)setMessage:(id)arg1 forUser:(id)arg2 withDateHeader:(BOOL)arg3 withHeader:(BOOL)arg4 withTimestamp:(BOOL)arg5;
- (void)setFrame:(struct CGRect)arg1;
- (void)prepareForReuse;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

