//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIAlertViewDelegate.h"

@class NSString, UIActivityIndicatorView, UIImageView, UILabel, UIView;

@interface SCUnlinkCardTableViewCell : UITableViewCell <UIAlertViewDelegate>
{
    id <SCUnlinkCardTableViewCellDelegate> _delegate;
    UIActivityIndicatorView *_activityView;
    UIImageView *_cardBrandImage;
    UILabel *_cardSuffixLabel;
    UIView *_unlinkCardXButtonView;
}

@property(retain, nonatomic) UIView *unlinkCardXButtonView; // @synthesize unlinkCardXButtonView=_unlinkCardXButtonView;
@property(retain, nonatomic) UILabel *cardSuffixLabel; // @synthesize cardSuffixLabel=_cardSuffixLabel;
@property(retain, nonatomic) UIImageView *cardBrandImage; // @synthesize cardBrandImage=_cardBrandImage;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
@property(nonatomic) __weak id <SCUnlinkCardTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)resetCardInfo;
- (void)resetUnlinkState;
- (void)unlinkCardButtonPressed:(id)arg1;
- (void)layoutSubviews;
- (void)initCardSuffixLabel;
- (void)initCardBrandImage;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

