//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@class UIButton, UILabel;

@interface SCVerificationCodeTextField : UITextField
{
    BOOL _inErrorState;
    id <SCVerificationCodeTextFieldDelegate> _verificationCodeTextFieldDelegate;
    UILabel *_invalidLabel;
    UIButton *_xButton;
}

@property(retain, nonatomic) UIButton *xButton; // @synthesize xButton=_xButton;
@property(retain, nonatomic) UILabel *invalidLabel; // @synthesize invalidLabel=_invalidLabel;
@property(nonatomic) BOOL inErrorState; // @synthesize inErrorState=_inErrorState;
@property(nonatomic) __weak id <SCVerificationCodeTextFieldDelegate> verificationCodeTextFieldDelegate; // @synthesize verificationCodeTextFieldDelegate=_verificationCodeTextFieldDelegate;
- (void).cxx_destruct;
- (void)drawPlaceholderInRect:(struct CGRect)arg1;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;
- (BOOL)isInErrorState;
- (void)setError:(BOOL)arg1;
- (void)clearInput;
- (struct CGSize)intrinsicContentSize;
- (id)initWithFrame:(struct CGRect)arg1;

@end

