//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCSwipeFilterView.h"

#import "GPUImageMovieDelegate.h"

@class AVPlayer, GPUImageMovie, NSMutableArray, NSString, NSURL, SCVideoSwipeFilterAdaptor, UIImage;

@interface SCVideoSwipeFilterView : SCSwipeFilterView <GPUImageMovieDelegate>
{
    BOOL _backgroundVideoSuccessfullyPlayed;
    BOOL _processing;
    BOOL _processingStopped;
    BOOL _didProcessFirstFrame;
    NSString *_snapSource;
    SCVideoSwipeFilterAdaptor *_adaptor;
    NSMutableArray *_filterNames;
    GPUImageMovie *_movie;
    NSURL *_videoURL;
    UIImage *_videoOverlayImage;
    AVPlayer *_player;
    int _viewCount;
}

@property(nonatomic) BOOL didProcessFirstFrame; // @synthesize didProcessFirstFrame=_didProcessFirstFrame;
@property(nonatomic) int viewCount; // @synthesize viewCount=_viewCount;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) UIImage *videoOverlayImage; // @synthesize videoOverlayImage=_videoOverlayImage;
@property(retain, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(retain, nonatomic) GPUImageMovie *movie; // @synthesize movie=_movie;
@property(nonatomic) BOOL processingStopped; // @synthesize processingStopped=_processingStopped;
@property(nonatomic) BOOL processing; // @synthesize processing=_processing;
@property(retain, nonatomic) NSMutableArray *filterNames; // @synthesize filterNames=_filterNames;
@property(nonatomic) BOOL backgroundVideoSuccessfullyPlayed; // @synthesize backgroundVideoSuccessfullyPlayed=_backgroundVideoSuccessfullyPlayed;
@property(retain, nonatomic) SCVideoSwipeFilterAdaptor *adaptor; // @synthesize adaptor=_adaptor;
@property(nonatomic) NSString *snapSource; // @synthesize snapSource=_snapSource;
- (void).cxx_destruct;
- (void)didProcessMovieFrame;
- (void)didPlayTime:(CDStruct_1b6d18a9)arg1;
- (void)didCompletePlayingMovie;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setVolume:(float)arg1;
- (id)newMediaFilterViewForName:(id)arg1;
- (void)setVideoURL:(id)arg1 videoOverlayImage:(id)arg2;
- (float)duration;
- (void)resetFilteredViews;
- (void)stopVideo;
- (void)reshowVideo;
- (void)showVideo;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

