//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ALServiceListener.h"

@class ALVideoView, NSString;

@interface SCVideoChatServiceListener : NSObject <ALServiceListener>
{
    BOOL _playingVideoStream;
    id <SCVideoChatServiceListenerDelegate> _delegate;
    NSString *_localSinkId;
    NSString *_sinkId;
    ALVideoView *_videoView;
}

@property(retain, nonatomic) ALVideoView *videoView; // @synthesize videoView=_videoView;
@property(copy, nonatomic) NSString *sinkId; // @synthesize sinkId=_sinkId;
@property(nonatomic) BOOL playingVideoStream; // @synthesize playingVideoStream=_playingVideoStream;
@property(nonatomic) NSString *localSinkId; // @synthesize localSinkId=_localSinkId;
@property(nonatomic) __weak id <SCVideoChatServiceListenerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)receivingStream;
- (BOOL)playingRemoteVideoStream;
- (void)playRemoteVideoStream;
- (void)stopRemoteVideoStream;
- (void)onMessage:(id)arg1;
- (void)onSessionReconnected:(id)arg1;
- (void)onConnectionLost:(id)arg1;
- (void)onVideoFrameSizeChanged:(id)arg1;
- (void)onMediaIssue:(id)arg1;
- (void)onMediaStreamEvent:(id)arg1;
- (void)onUserEvent:(id)arg1;
- (id)initWithRemoteVideoView:(id)arg1;

@end

