//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureAudioDataOutputSampleBufferDelegate.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"
#import "SCVideoRecordCaptureChannelDelegate.h"
#import "SCVideoScanCaptureChannelDelegate.h"

@class AVCaptureAudioDataOutput, AVCaptureSession, AVCaptureVideoDataOutput, FBKVOController, NSObject<OS_dispatch_queue>, NSString, SCVideoRecordCaptureChannel, SCVideoScanCaptureChannel;

@interface SCVideoCapturePipeline : NSObject <SCVideoRecordCaptureChannelDelegate, SCVideoScanCaptureChannelDelegate, AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate>
{
    BOOL _adjustingExposure;
    BOOL _active;
    BOOL _shouldCurrentlyDiscardFrames;
    BOOL _internalAdjustingExposure;
    BOOL _stabilizationLogged;
    id <SCVideoCapturePipelineDelegate> _delegate;
    AVCaptureSession *_captureSession;
    AVCaptureVideoDataOutput *_videoOutput;
    AVCaptureAudioDataOutput *_audioOutput;
    id <SCVideoCaptureChannel> _activeCaptureChannel;
    SCVideoScanCaptureChannel *_scanCaptureChannel;
    SCVideoRecordCaptureChannel *_recordCaptureChannel;
    NSObject<OS_dispatch_queue> *_sampleBufferCallbackQueue;
    float _lastExposureTime;
    int _lastISOSpeedRating;
    int _exposureUnchangedCount;
    FBKVOController *_observeController;
    double _lastAdjustingExposureStartTime;
}

@property(nonatomic) BOOL stabilizationLogged; // @synthesize stabilizationLogged=_stabilizationLogged;
@property(retain, nonatomic) FBKVOController *observeController; // @synthesize observeController=_observeController;
@property(nonatomic) double lastAdjustingExposureStartTime; // @synthesize lastAdjustingExposureStartTime=_lastAdjustingExposureStartTime;
@property(nonatomic) int exposureUnchangedCount; // @synthesize exposureUnchangedCount=_exposureUnchangedCount;
@property(nonatomic) BOOL internalAdjustingExposure; // @synthesize internalAdjustingExposure=_internalAdjustingExposure;
@property(nonatomic) int lastISOSpeedRating; // @synthesize lastISOSpeedRating=_lastISOSpeedRating;
@property(nonatomic) float lastExposureTime; // @synthesize lastExposureTime=_lastExposureTime;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *sampleBufferCallbackQueue; // @synthesize sampleBufferCallbackQueue=_sampleBufferCallbackQueue;
@property(retain, nonatomic) SCVideoRecordCaptureChannel *recordCaptureChannel; // @synthesize recordCaptureChannel=_recordCaptureChannel;
@property(retain, nonatomic) SCVideoScanCaptureChannel *scanCaptureChannel; // @synthesize scanCaptureChannel=_scanCaptureChannel;
@property(retain, nonatomic) id <SCVideoCaptureChannel> activeCaptureChannel; // @synthesize activeCaptureChannel=_activeCaptureChannel;
@property(retain, nonatomic) AVCaptureAudioDataOutput *audioOutput; // @synthesize audioOutput=_audioOutput;
@property(retain, nonatomic) AVCaptureVideoDataOutput *videoOutput; // @synthesize videoOutput=_videoOutput;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property(nonatomic) BOOL shouldCurrentlyDiscardFrames; // @synthesize shouldCurrentlyDiscardFrames=_shouldCurrentlyDiscardFrames;
@property(nonatomic) BOOL active; // @synthesize active=_active;
@property(nonatomic) BOOL adjustingExposure; // @synthesize adjustingExposure=_adjustingExposure;
@property(nonatomic) __weak id <SCVideoCapturePipelineDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)captureOutput:(id)arg1 didDropSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)parseExposureTime:(float *)arg1 ISOSpeedRating:(int *)arg2 fromSampleBuffer:(struct opaqueCMSampleBuffer *)arg3;
- (void)videoRecordCaptureChannel:(id)arg1 didFailWithError:(id)arg2;
- (void)videoRecordCaptureChannel:(id)arg1 didFinishRecordingToURL:(id)arg2;
- (void)videoRecordCaptureChannelDidBeginRecording:(id)arg1;
- (void)videoScanCaptureChannel:(id)arg1 didUpdateFrameRate:(int)arg2;
- (void)videoScanCaptureChannel:(id)arg1 didRenderDataImage:(id)arg2;
- (void)videoScanCaptureChannel:(id)arg1 didDetectSnapcode:(id)arg2 withVersion:(int)arg3;
- (void)switchToChannel:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)stopScan;
- (void)startScan;
- (void)finishRecording;
- (void)beginRecordingToURL:(id)arg1 withOrientation:(int)arg2;
- (void)videoStablizationEnabledChanged:(id)arg1;
- (void)enableVideoStablizationIfSupported;
- (void)removeOutputsFromSession;
- (void)addOutputsToSession;
- (void)sleep;
- (void)wakeup;
- (void)setupNewVideoDevice:(id)arg1;
@property(readonly, nonatomic) BOOL isSlowDevice;
- (void)dealloc;
- (id)initWithSession:(id)arg1 videoDevice:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

