//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSURL, SCVideoRecordCaptureChannel;

@protocol SCVideoRecordCaptureChannelDelegate <NSObject>
- (void)videoRecordCaptureChannel:(SCVideoRecordCaptureChannel *)arg1 didFailWithError:(NSError *)arg2;
- (void)videoRecordCaptureChannel:(SCVideoRecordCaptureChannel *)arg1 didFinishRecordingToURL:(NSURL *)arg2;
- (void)videoRecordCaptureChannelDidBeginRecording:(SCVideoRecordCaptureChannel *)arg1;
@end

