//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCVideoChatProviderDelegate.h"

@class NSString, NSTimer, SCHereAuth;

@interface SCVideoChatSession : NSObject <SCVideoChatProviderDelegate>
{
    id <SCVideoChatSessionDelegate> _delegate;
    SCHereAuth *_hereAuth;
    id <SCVideoChatProvider> _provider;
    NSTimer *_videoChatConnectionTimer;
}

@property(retain, nonatomic) NSTimer *videoChatConnectionTimer; // @synthesize videoChatConnectionTimer=_videoChatConnectionTimer;
@property(retain, nonatomic) id <SCVideoChatProvider> provider; // @synthesize provider=_provider;
@property(retain, nonatomic) SCHereAuth *hereAuth; // @synthesize hereAuth=_hereAuth;
@property(nonatomic) __weak id <SCVideoChatSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)providerDidFinishToggling:(id)arg1;
- (void)providerLocalVideoStreamFrameDidChange:(id)arg1;
- (void)providerLocalVideoStreamDidEnd:(id)arg1;
- (void)providerDidBeginLocalVideoStream:(id)arg1;
- (void)providerRemoteVideoStreamDidEnd:(id)arg1;
- (void)providerDidReceiveRemoteVideoStream:(id)arg1;
- (void)mediaIssue;
- (void)recipientConnectedWithProvider:(id)arg1;
- (void)recipientDisconnectedWithProvider:(id)arg1;
- (void)userDisconnectedWithProvider:(id)arg1;
- (void)userConnectedWithProvider:(id)arg1;
- (BOOL)shouldSwitchToBackFacingCamera;
- (BOOL)shouldSwitchToFrontFacingCamera;
- (void)switchToBackFacingCamera;
- (void)switchToFrontFacingCamera;
- (BOOL)hasMultipleCameras;
- (void)nextLocalFrameWithCallback:(CDUnknownBlockType)arg1;
- (id)remoteVideoView;
- (id)localVideoView;
- (BOOL)recipientHasConnected;
- (BOOL)mediaIssueActive;
- (BOOL)sessionConnected;
- (BOOL)anyStreamRendered;
- (BOOL)sendingStreamRendered;
- (BOOL)sendingStream;
- (BOOL)receivingStream;
- (void)enableIncomingStream;
- (void)disableIncomingStream;
- (void)endSessionWithCallback:(CDUnknownBlockType)arg1;
- (void)endStreaming;
- (void)connectionTimedOut:(id)arg1;
- (void)invalidateVideoChatTimeout;
- (void)startVideoChatConnectionTimer;
- (void)startStreaming;
- (void)startSessionWithCaptureManager:(id)arg1;
- (id)initWithAuth:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

