//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCSnapScannerDelegate.h"
#import "SCVideoCaptureChannel.h"

@class NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString, SCSnapScanner;

@interface SCVideoScanCaptureChannel : NSObject <SCSnapScannerDelegate, SCVideoCaptureChannel>
{
    BOOL _active;
    id <SCVideoScanCaptureChannelDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_frameScanningQueue;
    float _restCycleOfBusyCycle;
    NSObject<OS_dispatch_semaphore> *_activeSemaphore;
    SCSnapScanner *_snapScanner;
    double _maxFrameDuration;
    double _scanTimeout;
    double _scanStartTime;
}

@property(readonly, nonatomic) SCSnapScanner *snapScanner; // @synthesize snapScanner=_snapScanner;
@property(nonatomic) BOOL active; // @synthesize active=_active;
@property(nonatomic) double scanStartTime; // @synthesize scanStartTime=_scanStartTime;
@property(nonatomic) double scanTimeout; // @synthesize scanTimeout=_scanTimeout;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *activeSemaphore; // @synthesize activeSemaphore=_activeSemaphore;
@property(nonatomic) float restCycleOfBusyCycle; // @synthesize restCycleOfBusyCycle=_restCycleOfBusyCycle;
@property(nonatomic) double maxFrameDuration; // @synthesize maxFrameDuration=_maxFrameDuration;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *frameScanningQueue; // @synthesize frameScanningQueue=_frameScanningQueue;
@property(nonatomic) __weak id <SCVideoScanCaptureChannelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)processVideoSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)processAudioSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (BOOL)desiresAnAudioStream;
- (void)snapScanner:(id)arg1 didUpdateFrameRate:(int)arg2;
- (void)snapScanner:(id)arg1 didRenderDataImage:(id)arg2;
- (void)snapScanner:(id)arg1 didDetectSnapcode:(id)arg2 withVersion:(int)arg3;
- (void)stopScan;
- (void)startScan;
- (id)initWithMaxFrameDuration:(CDStruct_1b6d18a9)arg1 restCycle:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

