//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError, NSURL, SCVideoCapturePipeline, UIImage;

@protocol SCVideoCapturePipelineDelegate <NSObject>
- (void)videoCapturePipeline:(SCVideoCapturePipeline *)arg1 didUpdateFrameRate:(int)arg2;
- (void)videoCapturePipeline:(SCVideoCapturePipeline *)arg1 didRenderDataImage:(UIImage *)arg2;
- (void)videoCapturePipeline:(SCVideoCapturePipeline *)arg1 didDetectSnapcode:(NSData *)arg2 withVersion:(int)arg3;
- (void)videoCapturePipeline:(SCVideoCapturePipeline *)arg1 didFailRecordingWithError:(NSError *)arg2;
- (void)videoCapturePipeline:(SCVideoCapturePipeline *)arg1 didFinishRecordingToURL:(NSURL *)arg2;
- (void)videoCapturePipelineDidBeginRecording:(SCVideoCapturePipeline *)arg1;
@end

