//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface SCVideoChatPulseView : UIView
{
    BOOL _pulsing;
    BOOL _shouldPulse;
    UIView *_outerRing;
    UIView *_innerRing;
    float _initialOuterRadius;
    float _initialInnerRadius;
}

@property(nonatomic) float initialInnerRadius; // @synthesize initialInnerRadius=_initialInnerRadius;
@property(nonatomic) float initialOuterRadius; // @synthesize initialOuterRadius=_initialOuterRadius;
@property(retain, nonatomic) UIView *innerRing; // @synthesize innerRing=_innerRing;
@property(retain, nonatomic) UIView *outerRing; // @synthesize outerRing=_outerRing;
@property(nonatomic) BOOL shouldPulse; // @synthesize shouldPulse=_shouldPulse;
@property(nonatomic, getter=isPulsing) BOOL pulsing; // @synthesize pulsing=_pulsing;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)startPulsing;
- (void)setCenter:(struct CGPoint)arg1;
- (id)initWithFrame:(struct CGRect)arg1 initialRadius:(float)arg2;

@end

