//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCOverlayFilterView.h"

@class UILabel, UIView;

@interface SCWeatherFilterView : SCOverlayFilterView
{
    UILabel *_degreeLabel;
    int _orientation;
    int _roundedTempDegCelsius;
    int _roundedTempDegFahrenheit;
    UILabel *_temperatureLabel;
    UILabel *_temperatureScaleLabel;
    UIView *_temperatureView;
}

+ (int)type;
@property(retain, nonatomic) UIView *temperatureView; // @synthesize temperatureView=_temperatureView;
@property(retain, nonatomic) UILabel *temperatureScaleLabel; // @synthesize temperatureScaleLabel=_temperatureScaleLabel;
@property(retain, nonatomic) UILabel *temperatureLabel; // @synthesize temperatureLabel=_temperatureLabel;
@property(nonatomic) int roundedTempDegFahrenheit; // @synthesize roundedTempDegFahrenheit=_roundedTempDegFahrenheit;
@property(nonatomic) int roundedTempDegCelsius; // @synthesize roundedTempDegCelsius=_roundedTempDegCelsius;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) UILabel *degreeLabel; // @synthesize degreeLabel=_degreeLabel;
- (void).cxx_destruct;
- (void)smartFilterDataStoreUpdated:(id)arg1;
- (id)stringForTemperature:(unsigned int)arg1;
- (id)stringForTemperatureScale:(unsigned int)arg1;
- (BOOL)shouldRespondToTap:(id)arg1;
- (void)tap:(id)arg1;
- (void)setTemperatureToDisplay;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

