//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MASConstraint, NSString, UIImageView;

@interface SelectContactCell : UITableViewCell
{
    BOOL _isForSponsor;
    NSString *_page;
    UIImageView *_circle;
    MASConstraint *_circleRightConstraint;
    unsigned int _circleType;
}

@property(nonatomic) unsigned int circleType; // @synthesize circleType=_circleType;
@property(retain, nonatomic) MASConstraint *circleRightConstraint; // @synthesize circleRightConstraint=_circleRightConstraint;
@property(retain, nonatomic) UIImageView *circle; // @synthesize circle=_circle;
@property(retain, nonatomic) NSString *page; // @synthesize page=_page;
@property(nonatomic, setter=setIsForSponsor:) BOOL isForSponsor; // @synthesize isForSponsor=_isForSponsor;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)setUnselectedHighlightedBackground;
- (void)setUnselectedBackground;
- (void)setSelectedBackground;
- (void)toggleRightOffset:(BOOL)arg1;
- (void)setFontSelected:(BOOL)arg1;
- (void)setCircleSelected:(BOOL)arg1;
- (void)setBackgroundSelected:(BOOL)arg1;
- (void)setCellSelected:(BOOL)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 page:(id)arg3;

@end

