//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EphemeralMedia.h"

#import "MediaDataSource.h"
#import "MediaDelegate.h"
#import "MediaImageProcessingDelegate.h"
#import "MediaUploadDelegate.h"
#import "NSCoding.h"
#import "SCMessage.h"
#import "SnapVideoFilterDelegate.h"

@class AVPlayerItem, NSArray, NSDate, NSNumber, NSString, NSURL;

@interface Snap : EphemeralMedia <SnapVideoFilterDelegate, MediaDataSource, MediaDelegate, MediaUploadDelegate, MediaImageProcessingDelegate, NSCoding, SCMessage>
{
    BOOL _being_viewed;
    BOOL _canBeReplayed;
    BOOL _clearedBySender;
    BOOL _clearedByRecipient;
    BOOL _displayedActionTextInFeed;
    BOOL _doubleTap;
    BOOL _pending;
    BOOL _recentlyViewedAndHasNotLeftView;
    BOOL _replayed;
    BOOL _expiredWhileStackNotEmpty;
    BOOL _broadcastHideTimer;
    BOOL _broadcastSnap;
    BOOL _hasBeenTriedToRemove;
    NSString *_display;
    NSString *_sender;
    NSString *_recipient;
    NSArray *_recipients;
    int _replayAnimationStateFeed;
    int _replayAnimationStateChat;
    int _screenshots;
    NSDate *_sentTimestamp;
    int _status;
    int _state;
    NSDate *_timestamp;
    AVPlayerItem *_playerItem;
    NSNumber *_time_left;
    NSString *_broadcastActionText;
    NSURL *_broadcastUrlToOpen;
    NSNumber *_broadcastItunesProductId;
    NSString *_broadcastAffiliateToken;
    NSString *_broadcastCampaignTracker;
    unsigned int _numTimesReloaded;
    double _closedAt;
    double _secondsViewed;
    double _timeStartedOnScreen;
    double _video_time_so_far;
}

+ (id)targetSnapFromEphemeralMedia:(id)arg1;
+ (id)snapFromEphemeralMedia:(id)arg1;
+ (id)snapsFromJsonArray:(id)arg1;
+ (id)videoDirectory;
+ (BOOL)isStateViewing:(int)arg1;
+ (BOOL)isStateReceivedAndOpened:(int)arg1;
+ (BOOL)isStateSendingOrHasFailed:(int)arg1;
+ (BOOL)showActivityIndicatorForSnap:(id)arg1;
+ (BOOL)hideActionTextAfterDelayForSnap:(id)arg1;
+ (BOOL)hideActionTextForSnap:(id)arg1;
+ (id)actionTextForSnap:(id)arg1 context:(int)arg2;
+ (id)chatIconImageForSnap:(id)arg1;
+ (id)chatScreenshotImage;
+ (id)viewedIconImageForSnap:(id)arg1;
+ (id)replayIconImageForSnap:(id)arg1;
+ (id)iconImageForSnap:(id)arg1;
@property(nonatomic) unsigned int numTimesReloaded; // @synthesize numTimesReloaded=_numTimesReloaded;
@property(nonatomic) BOOL hasBeenTriedToRemove; // @synthesize hasBeenTriedToRemove=_hasBeenTriedToRemove;
@property(copy, nonatomic) NSString *broadcastCampaignTracker; // @synthesize broadcastCampaignTracker=_broadcastCampaignTracker;
@property(copy, nonatomic) NSString *broadcastAffiliateToken; // @synthesize broadcastAffiliateToken=_broadcastAffiliateToken;
@property(retain, nonatomic) NSNumber *broadcastItunesProductId; // @synthesize broadcastItunesProductId=_broadcastItunesProductId;
@property(retain, nonatomic) NSURL *broadcastUrlToOpen; // @synthesize broadcastUrlToOpen=_broadcastUrlToOpen;
@property(nonatomic) BOOL broadcastSnap; // @synthesize broadcastSnap=_broadcastSnap;
@property(nonatomic) BOOL broadcastHideTimer; // @synthesize broadcastHideTimer=_broadcastHideTimer;
@property(retain, nonatomic) NSString *broadcastActionText; // @synthesize broadcastActionText=_broadcastActionText;
@property(nonatomic) double video_time_so_far; // @synthesize video_time_so_far=_video_time_so_far;
@property(retain, nonatomic) NSNumber *time_left; // @synthesize time_left=_time_left;
@property(nonatomic) double timeStartedOnScreen; // @synthesize timeStartedOnScreen=_timeStartedOnScreen;
@property(nonatomic) double secondsViewed; // @synthesize secondsViewed=_secondsViewed;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(nonatomic) BOOL expiredWhileStackNotEmpty; // @synthesize expiredWhileStackNotEmpty=_expiredWhileStackNotEmpty;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) int status; // @synthesize status=_status;
@property(retain, nonatomic) NSDate *sentTimestamp; // @synthesize sentTimestamp=_sentTimestamp;
@property(nonatomic) int screenshots; // @synthesize screenshots=_screenshots;
@property(nonatomic) BOOL replayed; // @synthesize replayed=_replayed;
@property(nonatomic) int replayAnimationStateChat; // @synthesize replayAnimationStateChat=_replayAnimationStateChat;
@property(nonatomic) int replayAnimationStateFeed; // @synthesize replayAnimationStateFeed=_replayAnimationStateFeed;
@property(retain, nonatomic) NSArray *recipients; // @synthesize recipients=_recipients;
@property(retain, nonatomic) NSString *recipient; // @synthesize recipient=_recipient;
@property(nonatomic) BOOL recentlyViewedAndHasNotLeftView; // @synthesize recentlyViewedAndHasNotLeftView=_recentlyViewedAndHasNotLeftView;
@property(retain, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(nonatomic) BOOL pending; // @synthesize pending=_pending;
@property(nonatomic) BOOL doubleTap; // @synthesize doubleTap=_doubleTap;
@property(nonatomic) BOOL displayedActionTextInFeed; // @synthesize displayedActionTextInFeed=_displayedActionTextInFeed;
@property(retain, nonatomic) NSString *display; // @synthesize display=_display;
@property(nonatomic) double closedAt; // @synthesize closedAt=_closedAt;
@property(nonatomic) BOOL clearedByRecipient; // @synthesize clearedByRecipient=_clearedByRecipient;
@property(nonatomic) BOOL clearedBySender; // @synthesize clearedBySender=_clearedBySender;
@property(nonatomic) BOOL canBeReplayed; // @synthesize canBeReplayed=_canBeReplayed;
@property(nonatomic) BOOL being_viewed; // @synthesize being_viewed=_being_viewed;
- (void).cxx_destruct;
- (id)clearedDictionary;
- (BOOL)sending;
- (BOOL)failedToSend;
- (BOOL)sentByUser;
- (BOOL)isInvalidAfterUnarchiving;
- (BOOL)isUnread;
- (BOOL)shouldDisplayBelowFoldInChat;
- (id)messageRecipient;
- (id)messageSender;
- (id)feedDisplayTimestamp;
- (id)messageTimestamp;
- (void)imageProcessingDidSucceedForMedia:(id)arg1;
- (void)mediaUploadDidFailForMedia:(id)arg1;
- (void)mediaUploadDidSucceedForMedia:(id)arg1;
- (int)uploadMediaTypeForMedia:(id)arg1;
- (id)uploadMediaIdForMedia:(id)arg1;
- (void)fetchMediaDidSucceedForMedia:(id)arg1;
- (void)fetchMediaIsGoneForMedia:(id)arg1;
- (void)fetchMediaDidFailForMedia:(id)arg1;
- (void)fetchMediaIsLoadingForMedia:(id)arg1;
- (BOOL)isBroadcastForMedia:(id)arg1;
- (BOOL)encrypt;
- (BOOL)persist;
- (id)encryptionDictionaryForMedia:(id)arg1;
- (id)decryptData:(id)arg1 forMedia:(id)arg2;
- (id)mediaIdForMedia:(id)arg1;
- (id)endpointParamsForMedia:(id)arg1;
- (id)endpointForMedia:(id)arg1;
- (id)persistingFailuresURLForMedia:(id)arg1;
- (void)loadPersistedFailedSnapData;
- (id)uploadSuccessUserDefaultsKey;
@property(readonly, copy) NSString *description;
- (id)secretReceivedSnapParameters;
- (id)receivedSnapParameters;
- (id)secretSentSnapParameters;
- (id)sentSnapParameters;
- (void)logSendEvent;
- (id)consistentId;
- (BOOL)veryRecentlyOpen;
- (id)username;
- (BOOL)isGroupSend;
- (id)nameForView;
- (id)recipientUsernames;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)replaceWithSnap:(id)arg1;
- (BOOL)shouldReplaceWithSnap:(id)arg1;
- (void)updateWithSnap:(id)arg1;
- (BOOL)isReadyToReplayOrReplaying;
- (BOOL)isSentSnap;
- (BOOL)isReceivedAndUnopened;
- (BOOL)isReceivedAndOpened;
- (BOOL)isViewing;
- (BOOL)isLoading;
- (BOOL)isLoaded;
- (BOOL)isNotLoaded;
- (BOOL)isScreenshotted;
- (BOOL)isSentAndOpened;
- (BOOL)isDelivered;
- (BOOL)isSentDeliveredOrOpened;
- (BOOL)isSent;
- (BOOL)isSendingOrHasFailed;
- (BOOL)isMediaProcessingOrFailedToProcess;
- (BOOL)isMediaProcessing;
- (BOOL)hasMediaProcessingFailed;
- (BOOL)hasFailed;
- (BOOL)isSending;
- (id)uploadParameters;
- (void)uploadSnap;
- (void)setUploading;
- (CDUnknownBlockType)uploadFailureBlock;
- (CDUnknownBlockType)uploadSuccessBlock;
- (void)doSend;
- (void)postSend;
- (void)send;
- (void)preSend;
- (BOOL)shouldClearSentSnap;
- (void)incNumTimesReloaded;
- (BOOL)isSentButNotYetReturned;
- (void)clearNumTimesReloaded;
- (void)markAsViewed;
- (void)replay;
- (void)initFields;
- (id)updatedSnapDictionary;
- (id)initWithJSONDictionary:(id)arg1;
- (void)assignNewClientId;
- (id)initWithClientId;
- (void)updateWithStateMessage:(id)arg1;
- (id)stateMessageWithParametersDelegate:(id)arg1 messageDelegate:(id)arg2;
- (void)videoProcessingDidFailForSnapVideoFilter:(id)arg1 error:(id)arg2;
- (void)videoProcessingDidSucceedForSnapVideoFilter:(id)arg1 data:(id)arg2;
- (void)clearFromChat;
- (BOOL)shouldDisplayInChat;
- (BOOL)shouldClearFromChat;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSDate *viewedTimestamp;

@end

