//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GPUImageMovieDelegate.h"

@class AVAssetExportSession, GPUImageMovie, GPUImageMovieWriter, GPUImagePicture, NSString, NSURL, UIImage;

@interface SnapVideoFilter : NSObject <GPUImageMovieDelegate>
{
    BOOL _audioEnabled;
    BOOL _highQuality;
    BOOL _videoAlreadySized;
    BOOL _videoAlreadyOriented;
    BOOL _exportCanceled;
    BOOL _exportCompleted;
    BOOL _processingCanceled;
    BOOL _processingCompleted;
    BOOL _shouldProcessVideo;
    NSString *_additionalFilterName;
    int _overlayImageFileSizeBits;
    UIImage *_overlayImage;
    UIImage *_overlayImageForThumbnail;
    id <SnapVideoFilterDelegate> _delegate;
    int _orientation;
    NSString *_uuid;
    NSURL *_videoUrl;
    GPUImagePicture *_captionAndDrawing;
    AVAssetExportSession *_exportSession;
    GPUImageMovie *_movieFile;
    NSURL *_movieURL;
    GPUImageMovieWriter *_movieWriter;
    CDUnknownBlockType _completion;
    UIImage *_thumbnail;
    UIImage *_additionalFilterImage;
}

+ (id)baseVideoPath;
+ (void)clearUnusedVideoFiles;
@property(retain, nonatomic) UIImage *additionalFilterImage; // @synthesize additionalFilterImage=_additionalFilterImage;
@property(retain, nonatomic) UIImage *thumbnail; // @synthesize thumbnail=_thumbnail;
@property(nonatomic) BOOL shouldProcessVideo; // @synthesize shouldProcessVideo=_shouldProcessVideo;
@property(nonatomic) BOOL processingCompleted; // @synthesize processingCompleted=_processingCompleted;
@property(nonatomic) BOOL processingCanceled; // @synthesize processingCanceled=_processingCanceled;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) GPUImageMovieWriter *movieWriter; // @synthesize movieWriter=_movieWriter;
@property(retain, nonatomic) NSURL *movieURL; // @synthesize movieURL=_movieURL;
@property(retain, nonatomic) GPUImageMovie *movieFile; // @synthesize movieFile=_movieFile;
@property(retain, nonatomic) AVAssetExportSession *exportSession; // @synthesize exportSession=_exportSession;
@property(nonatomic) BOOL exportCompleted; // @synthesize exportCompleted=_exportCompleted;
@property(nonatomic) BOOL exportCanceled; // @synthesize exportCanceled=_exportCanceled;
@property(retain, nonatomic) GPUImagePicture *captionAndDrawing; // @synthesize captionAndDrawing=_captionAndDrawing;
@property(nonatomic) BOOL videoAlreadyOriented; // @synthesize videoAlreadyOriented=_videoAlreadyOriented;
@property(nonatomic) BOOL videoAlreadySized; // @synthesize videoAlreadySized=_videoAlreadySized;
@property(retain, nonatomic) NSURL *videoUrl; // @synthesize videoUrl=_videoUrl;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(nonatomic) BOOL highQuality; // @synthesize highQuality=_highQuality;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(nonatomic) __weak id <SnapVideoFilterDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImage *overlayImageForThumbnail; // @synthesize overlayImageForThumbnail=_overlayImageForThumbnail;
@property(retain, nonatomic) UIImage *overlayImage; // @synthesize overlayImage=_overlayImage;
@property(nonatomic) int overlayImageFileSizeBits; // @synthesize overlayImageFileSizeBits=_overlayImageFileSizeBits;
@property(nonatomic) BOOL audioEnabled; // @synthesize audioEnabled=_audioEnabled;
@property(retain, nonatomic) NSString *additionalFilterName; // @synthesize additionalFilterName=_additionalFilterName;
- (void).cxx_destruct;
- (BOOL)deviceMeetsMinimumRequirementsForHighQualityVideo;
- (void)didCompletePlayingMovie;
- (void)videoProcessingDidFailForMovie:(id)arg1;
- (void)completeWithAsset:(id)arg1 url:(id)arg2 error:(id)arg3;
- (void)videoProcessingDidFailWithError:(id)arg1;
- (void)dealloc;
- (void)cancelExport;
- (void)cancelFilterVideo;
- (void)cancelProcessing;
- (void)applicationDidBecomeActive;
- (void)applicationWillResignActive;
- (void)createThumbnailWithAsset:(id)arg1;
- (void)exportProcessedVideoToFile;
- (void)filterVideoCompletion:(CDUnknownBlockType)arg1;
- (void)filterVideo;
- (id)tempFileURL;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

