//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class StoriesCell;

@protocol StoriesCellDelegate <NSObject>
- (void)mySharedStoryInfoPressedForStoriesCell:(StoriesCell *)arg1;
- (void)sharedStoryInfoPressedForStoriesCell:(StoriesCell *)arg1;
- (void)savePressedForStoriesCell:(StoriesCell *)arg1;
- (void)settingsPressedForStoriesCell:(StoriesCell *)arg1;
- (void)replySnapButtonPressedForStoriesCell:(StoriesCell *)arg1;
@end

