//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class FriendStoriesCollection, MySharedStoriesCollection, MyStories;

@interface Stories : NSObject <NSCoding>
{
    FriendStoriesCollection *_friendStoriesCollection;
    MyStories *_myStories;
    MySharedStoriesCollection *_mySharedStoriesCollection;
}

+ (id)storiesWithThumbnailsClosestToPercentages:(id)arg1 withStories:(id)arg2;
+ (unsigned int)indexOfStoryWithThumbnailPercentClosestToPercent:(float)arg1 inStories:(id)arg2;
+ (id)checksumPath;
+ (id)path;
+ (id)storiesFromResponseDictionary:(id)arg1;
+ (id)storyLoadedPredicate;
@property(retain, nonatomic) MySharedStoriesCollection *mySharedStoriesCollection; // @synthesize mySharedStoriesCollection=_mySharedStoriesCollection;
@property(retain, nonatomic) MyStories *myStories; // @synthesize myStories=_myStories;
@property(retain, nonatomic) FriendStoriesCollection *friendStoriesCollection; // @synthesize friendStoriesCollection=_friendStoriesCollection;
- (void).cxx_destruct;
- (void)prepareForResignActive;
- (id)filterFriendStories:(id)arg1;
- (void)resetRecentlyViewedState;
- (void)clearExpiredStories;
- (void)updateFriendStoriesCollectionWithFriendStories:(id)arg1 isDelta:(BOOL)arg2;
- (void)updateMySharedStoriesWithSharedStories:(id)arg1;
- (void)updateMyStoriesWithMyStories:(id)arg1;
- (BOOL)saveState;
- (void)encodeWithCoder:(id)arg1;
- (void)ensureNonNilObjects;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

