//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SwipeView <NSObject>

@optional
- (void)viewDidAppearAtOffset:(float)arg1;
- (void)viewDidPartiallyAppear;
- (void)viewCannotAppear;
- (void)viewCanAppear;
- (void)viewDidScroll;
- (void)viewDidFullyDisappear;
- (void)viewDidFullyAppear;
@end

