//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (SCColor)
+ (id)sc_ErrorStateRedWithAlpha:(float)arg1;
+ (id)sc_ErrorStateRed;
+ (id)sc_BackgroundGrayWithAlpha:(float)arg1;
+ (id)sc_BackgroundGray;
+ (id)sc_SeparatorGrayWithAlpha:(float)arg1;
+ (id)sc_SeparatorGray;
+ (id)sc_TertiaryBlackWithAlpha:(float)arg1;
+ (id)sc_TertiaryBlack;
+ (id)sc_SecondaryBlackWithAlpha:(float)arg1;
+ (id)sc_SecondaryBlack;
+ (id)sc_PrimaryBlackWithAlpha:(float)arg1;
+ (id)sc_PrimaryBlack;
+ (id)sc_DarkYellowWithAlpha:(float)arg1;
+ (id)sc_DarkYellow;
+ (id)sc_RedWithAlpha:(float)arg1;
+ (id)sc_Red;
+ (id)sc_BlueWithAlpha:(float)arg1;
+ (id)sc_Blue;
+ (id)sc_GreenWithAlpha:(float)arg1;
+ (id)sc_Green;
+ (id)sc_BrightYellowWithAlpha:(float)arg1;
+ (id)sc_BrightYellow;
+ (id)sc_PurpleWithAlpha:(float)arg1;
+ (id)sc_Purple;
@end

