//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (Filter)
+ (id)stringUUID;
+ (BOOL)shouldReportForPercentage:(float)arg1;
+ (BOOL)shouldLogPerfEvents;
+ (BOOL)shouldLogStepEvents;
+ (BOOL)shouldReportUserTrace;
+ (BOOL)shouldReportCrashes;
@end

