//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScreen.h"

@interface UIScreen (SCFixedBounds)
- (float)sc_fixedPixelHeight;
- (float)sc_fixedPixelWidth;
@property(readonly, nonatomic) struct CGRect sc_fixedBounds;
@end

