//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@interface UITableView (TableHeader)
+ (id)createLabelForHeaderWithText:(id)arg1;
+ (id)tableHeaderViewWithColor:(id)arg1 text:(id)arg2;
+ (id)tableHeaderViewForKey:(id)arg1 page:(id)arg2 text:(id)arg3 border:(BOOL)arg4;
@end

