//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (Notification)
- (void)markTimestampForChatNotificationWithInfo:(id)arg1;
- (BOOL)previouslyHandledNotificationWithInfo:(id)arg1;
- (BOOL)shouldShowNotificationInCurrentMediaState;
- (BOOL)shouldDiscardNotificationWithInfo:(id)arg1;
- (BOOL)shouldShowNotificationWithInfo:(id)arg1;
- (void)showNotificationWithInfo:(id)arg1 delegate:(id)arg2;
@end

