//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface GADCacheSet : NSObject
{
    id <NSObject> _observer;
    struct dispatch_queue_s *_lockQueue;
    NSMutableSet *_set;
    unsigned int _maxCapacity;
}

- (void).cxx_destruct;
- (void)removeAllObjects;
- (void)addObject:(id)arg1;
- (id)anyObject;
- (void)dealloc;
- (id)initWithMaxCapacity:(unsigned int)arg1;

@end

