//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADDeviceSpecifications.h"

@class GADNetwork, NSString;

@interface GADDevice : NSObject <GADDeviceSpecifications>
{
    struct dispatch_queue_s *_lockQueue;
    id <NSObject> _radioAccessTechnologyChangeObserver;
    NSString *_lastKnownRadioAccessTechnology;
    NSString *_radioAccessTechnology;
    NSString *_userAgentString;
    NSString *_cachedAdvertisingID;
    NSString *_cachedMD5AdvertisingID;
    GADNetwork *_network;
}

+ (id)currentDevice;
@property(retain, nonatomic) GADNetwork *network; // @synthesize network=_network;
- (void).cxx_destruct;
@property(copy) NSString *userAgentString;
@property(copy) NSString *radioAccessTechnology;
- (id)lastKnownRadioAccessTechnology;
- (BOOL)userInterfaceIdiomIsPhone;
@property(readonly, nonatomic) struct CGRect standardizedApplicationFrame;
@property(readonly, nonatomic) struct CGRect standardizedScreenBounds;
@property(readonly, nonatomic) float screenDensity;
@property(readonly, nonatomic, getter=isOrientationLandscape) BOOL orientationLandscape;
- (unsigned int)audioRouteUsingAudioToolkit;
- (unsigned int)audioRouteUsingAVAudioSession;
@property(readonly, nonatomic) unsigned int audioRoute;
@property(readonly, nonatomic) NSString *locale;
@property(readonly, nonatomic) NSString *deviceSubmodel;
@property(readonly, nonatomic) NSString *deviceModel;
- (id)identifierManager;
@property(readonly, nonatomic) NSString *deviceIdentifier;
@property(readonly, nonatomic) NSString *systemVersion;
@property(readonly, nonatomic, getter=isJailbroken) BOOL jailbroken;
- (id)canOpenURLs:(id)arg1;
- (BOOL)OSIsSupported;
- (BOOL)isOSAtLeastMajor:(int)arg1 minor:(int)arg2 bug:(int)arg3;
- (void)getOSMajor:(int *)arg1 minor:(int *)arg2 bugFix:(int *)arg3;
- (id)baseSDKVersion;
- (id)parameters;
- (void)disableRadioAccessTechnologyChecking;
- (void)enableRadioAccessTechnologyChecking;
- (void)dealloc;
- (id)init;

@end

