//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADNativeAd.h"

#import "GADAdLoading.h"

@class NSString, NSURL, UIImage;

@interface GADNativeContentAd : GADNativeAd <GADAdLoading>
{
    NSURL *_imageURL;
    NSURL *_logoURL;
    NSURL *_attributionIconURL;
    NSString *_headline;
    NSString *_body;
    UIImage *_attributionIcon;
    NSString *_attributionText;
    UIImage *_image;
    UIImage *_logo;
    NSString *_callToAction;
    NSString *_advertiser;
}

+ (id)requestParametersForAdLoader:(id)arg1;
+ (id)requiredDelegateProtocol;
@property(readonly, copy, nonatomic) NSString *advertiser; // @synthesize advertiser=_advertiser;
@property(copy, nonatomic) NSString *callToAction; // @synthesize callToAction=_callToAction;
@property(retain, nonatomic) UIImage *logo; // @synthesize logo=_logo;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *attributionText; // @synthesize attributionText=_attributionText;
@property(retain, nonatomic) UIImage *attributionIcon; // @synthesize attributionIcon=_attributionIcon;
@property(copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(copy, nonatomic) NSString *headline; // @synthesize headline=_headline;
- (void).cxx_destruct;
- (void)didReceiveAdForAdLoader:(id)arg1;
- (void)loadAssets;
- (id)assetsRequiredToBeDisplayed;
@property(readonly, nonatomic) BOOL hasAttributionInformation;
- (id)clickActionTemplateID;
- (id)initWithDictionary:(id)arg1;

@end

