//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADWebViewDelegate.h"

@class GADSDKCoreGMSGHandler, GADWebView, GADWebViewDelegate, NSMutableArray, NSMutableSet;

@interface GADSDKCoreWebView : NSObject <GADWebViewDelegate>
{
    int _state;
    BOOL _hasSDKCoreLoadedAtLeastOnce;
    NSMutableArray *_pendingJSCommands;
    struct dispatch_queue_s *_lockQueue;
    struct dispatch_queue_s *_commandQueue;
    NSMutableSet *_SDKCoreObservers;
    GADWebViewDelegate *_webViewDelegate;
    GADWebView *_webView;
    GADSDKCoreGMSGHandler *_SDKCoreGMSGHandler;
}

@property(readonly, nonatomic) GADSDKCoreGMSGHandler *SDKCoreGMSGHandler; // @synthesize SDKCoreGMSGHandler=_SDKCoreGMSGHandler;
@property(retain, nonatomic) GADWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)dispatchPendingJavaScriptCommands;
- (void)executePendingJavaScriptCommands;
- (void)executeJavaScriptCommand:(id)arg1;
@property BOOL hasSDKCoreLoadedAtLeastOnce;
@property int state;
- (void)notifyAllObserversOnlyOnceThatSDKCoreRequestIsFinished;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)refreshSDKCore;
- (void)removeObserver:(id)arg1;
- (void)addObserverForOneTimeNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

