//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GADAd, GADSDKCoreGMSGHandler, NSDictionary, NSString;

@protocol GADSDKCoreGMSGHandlerDelegate
- (void)SDKCoreGMSGHandler:(GADSDKCoreGMSGHandler *)arg1 didReceiveInvalidAdParameters:(NSDictionary *)arg2 requestID:(NSString *)arg3;
- (void)SDKCoreGMSGHandler:(GADSDKCoreGMSGHandler *)arg1 loadSDKConstants:(NSDictionary *)arg2;
- (void)SDKCoreGMSGHandler:(GADSDKCoreGMSGHandler *)arg1 loadAd:(GADAd *)arg2 headers:(NSDictionary *)arg3 requestID:(NSString *)arg4;
- (void)SDKCoreGMSGHandler:(GADSDKCoreGMSGHandler *)arg1 loadAdParameters:(NSDictionary *)arg2 requestID:(NSString *)arg3;
@end

