//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BCOVPlaybackSession.h"
#import "BCOVPlaybackSessionPrivate.h"

@class AVPlayer, AVPlayerLayer, BCOVBasicPlaybackProgress, BCOVSource, BCOVVideo, BCOV_RACMulticastConnection, BCOV_RACSignal, BCOV_RACSubject, NSString;

@interface BCOVBasicPlaybackSession : NSObject <BCOVPlaybackSession, BCOVPlaybackSessionPrivate>
{
    BOOL _didReceiveTerminateNotification;
    BCOVVideo *_video;
    BCOVSource *_source;
    AVPlayer *_player;
    AVPlayerLayer *_playerLayer;
    BCOV_RACSignal *_durationObserver;
    BCOV_RACSignal *_externalPlaybackActiveObserver;
    BCOV_RACSubject *_beginSubject;
    BCOV_RACSubject *_terminationSubject;
    BCOV_RACMulticastConnection *_lifecycleMulticast;
    BCOVBasicPlaybackProgress *_progressSource;
}

@property(nonatomic) BOOL didReceiveTerminateNotification; // @synthesize didReceiveTerminateNotification=_didReceiveTerminateNotification;
@property(retain, nonatomic) BCOVBasicPlaybackProgress *progressSource; // @synthesize progressSource=_progressSource;
@property(retain, nonatomic) BCOV_RACMulticastConnection *lifecycleMulticast; // @synthesize lifecycleMulticast=_lifecycleMulticast;
@property(retain, nonatomic) BCOV_RACSubject *terminationSubject; // @synthesize terminationSubject=_terminationSubject;
@property(retain, nonatomic) BCOV_RACSubject *beginSubject; // @synthesize beginSubject=_beginSubject;
@property(retain, nonatomic) BCOV_RACSignal *externalPlaybackActiveObserver; // @synthesize externalPlaybackActiveObserver=_externalPlaybackActiveObserver;
@property(retain, nonatomic) BCOV_RACSignal *durationObserver; // @synthesize durationObserver=_durationObserver;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(copy, nonatomic) BCOVSource *source; // @synthesize source=_source;
@property(copy, nonatomic) BCOVVideo *video; // @synthesize video=_video;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)lifecycleReadyFailSignal;
- (id)lifecyclePlayPauseSignal;
- (id)lifecycleEndSignal;
- (id)completeSignalOnTerminate:(id)arg1;
- (void)pauseAd;
- (void)resumeAd;
- (void)terminate;
- (void)terminateWithNotification;
- (id)progress;
- (id)lifecycle;
- (id)isExternalPlaybackActive;
- (id)durationChanges;
- (id)cuePoints;
- (void)begin;
- (id)initWithVideo:(id)arg1 source:(id)arg2 player:(id)arg3 playerLayer:(id)arg4;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

