//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BCOVAnalyticsSessionDigester, NSDictionary;

@interface BCOVAnalyticsSession : NSObject
{
    id <BCOVPlaybackSessionPrivate> _playbackSession;
    NSDictionary *_stockProperties;
    BCOVAnalyticsSessionDigester *_sessionDigester;
}

@property(retain, nonatomic) BCOVAnalyticsSessionDigester *sessionDigester; // @synthesize sessionDigester=_sessionDigester;
@property(copy, nonatomic) NSDictionary *stockProperties; // @synthesize stockProperties=_stockProperties;
@property(retain, nonatomic) id <BCOVPlaybackSessionPrivate> playbackSession; // @synthesize playbackSession=_playbackSession;
- (void).cxx_destruct;
- (void)digestVideoComplete;
- (void)digestVideoEngagement;
- (void)digestVideoView;
- (void)digestVideoImpression;
- (void)start;
- (id)initWithPlaybackSession:(id)arg1 stockProperties:(id)arg2 sessionDigester:(id)arg3;

@end

