//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "BCOVPlaybackSessionConsumer.h"

@class NSString;

@interface BCOVVideoContainerView : UIView <BCOVPlaybackSessionConsumer>
{
    BOOL _controlsEnabled;
    BOOL _controlsVisible;
    UIView *_controlsView;
    UIView *_videoView;
}

@property(nonatomic) BOOL controlsVisible; // @synthesize controlsVisible=_controlsVisible;
@property(nonatomic) __weak UIView *videoView; // @synthesize videoView=_videoView;
@property(nonatomic) __weak UIView *controlsView; // @synthesize controlsView=_controlsView;
@property(nonatomic, getter=isControlsEnabled) BOOL controlsEnabled; // @synthesize controlsEnabled=_controlsEnabled;
- (void).cxx_destruct;
- (void)didAdvanceToPlaybackSession:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithVideoView:(id)arg1 controlsView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

