//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BCOVMediaRequestFactory, NSOperationQueue;

@interface BCOVCatalogService : NSObject
{
    BCOVMediaRequestFactory *_requestFactory;
    NSOperationQueue *_jsonDeserializationQueue;
}

+ (BOOL)isNotNilOrNull:(id)arg1;
@property(retain, nonatomic) NSOperationQueue *jsonDeserializationQueue; // @synthesize jsonDeserializationQueue=_jsonDeserializationQueue;
@property(retain, nonatomic) BCOVMediaRequestFactory *requestFactory; // @synthesize requestFactory=_requestFactory;
- (void).cxx_destruct;
- (id)findVideoWithReferenceID:(id)arg1 parameters:(id)arg2;
- (id)findVideoDictionaryWithReferenceID:(id)arg1 parameters:(id)arg2;
- (id)findVideoWithVideoID:(id)arg1 parameters:(id)arg2;
- (id)findVideoDictionaryWithVideoID:(id)arg1 parameters:(id)arg2;
- (id)findPlaylistWithReferenceID:(id)arg1 parameters:(id)arg2;
- (id)findPlaylistDictionaryWithReferenceID:(id)arg1 parameters:(id)arg2;
- (id)findPlaylistWithPlaylistID:(id)arg1 parameters:(id)arg2;
- (id)findPlaylistDictionaryWithPlaylistID:(id)arg1 parameters:(id)arg2;
- (id)issueRequest:(id)arg1;
- (void)issueRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithMediaRequestFactory:(id)arg1;
- (id)initWithToken:(id)arg1;
- (void)findVideoWithReferenceID:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)findVideoWithVideoID:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)findPlaylistWithReferenceID:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)findPlaylistWithPlaylistID:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)playlistDictionaryOperationWithReferenceID:(id)arg1 parameters:(id)arg2;
- (id)playlistDictionaryOperationWithPlaylistID:(id)arg1 parameters:(id)arg2;
- (id)videoDictionaryOperationWithReferenceID:(id)arg1 parameters:(id)arg2;
- (id)videoDictionaryOperationWithVideoID:(id)arg1 parameters:(id)arg2;
- (id)playlistOperationWithReferenceID:(id)arg1 parameters:(id)arg2;
- (id)playlistOperationWithPlaylistID:(id)arg1 parameters:(id)arg2;
- (id)videoOperationWithReferenceID:(id)arg1 parameters:(id)arg2;
- (id)videoOperationWithVideoID:(id)arg1 parameters:(id)arg2;

@end

