//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface BCOV_RACBacktrace : NSObject
{
    void *_callStackAddresses[128];
    int _callStackSize;
    BCOV_RACBacktrace *_previousThreadBacktrace;
}

+ (id)backtraceIgnoringFrames:(unsigned int)arg1;
+ (id)backtrace;
+ (void)load;
@property(retain, nonatomic) BCOV_RACBacktrace *previousThreadBacktrace; // @synthesize previousThreadBacktrace=_previousThreadBacktrace;
- (void).cxx_destruct;
- (id)description;
- (void)dealloc;
@property(readonly, copy, nonatomic) NSArray *callStackSymbols;

@end

