//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BCOVMutablePlaylist.h"
#import "BCOVPlaylist.h"
#import "NSCopying.h"

@class NSArray, NSDictionary, NSString;

@interface BCOVPlaylist : NSObject <BCOVMutablePlaylist, BCOVPlaylist, NSCopying>
{
    NSArray *_videos;
    NSDictionary *_properties;
}

+ (id)playlistFromJSONDictionary:(id)arg1;
- (void)setProperties:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *properties;
- (void)setVideos:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *videos;
- (void).cxx_destruct;
- (unsigned int)count;
- (id)update:(CDUnknownBlockType)arg1;
- (id)objectAtIndexedSubscript:(unsigned int)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
- (BOOL)isEqualToPlaylist:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (id)init;
- (id)initWithVideo:(id)arg1;
- (id)initWithVideo:(id)arg1 properties:(id)arg2;
- (id)initWithVideos:(id)arg1;
- (id)initWithVideos:(id)arg1 properties:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

